### ISSUE TITLE
Hardcoded default Cassandra keyspace name (reaper_db) in CassandraStorage.java

### ISSUE THREAD

**Issue by gpaggi** [thelastpickle/cassandra-reaper#1023]
This commit https://github.com/thelastpickle/cassandra-reaper/commit/26c710b2a32bea6add9a0ab25807c28ef942e490# has changes to CassandraStorage.java which assume the keyspace name to be the default one, i.e. `reaper_db`.  
If the user configured it to anything else:
```
cassandra:
   clusterName: "reaper"
   contactPoints: [ "cass-reaper.service.consul" ]
   keyspace: reaper
```
Reaper will fail to start
```

INFO   [2021-02-25 10:10:50,832] [main] o.c.c.m.MigrationRepository - Found 12 migration scripts 
INFO   [2021-02-25 10:10:50,832] [main] i.c.s.CassandraStorage - Keyspace reaper already at schema version 27 
ERROR  [2021-02-25 10:10:51,071] [main] i.c.ReaperApplication - Storage is not ready yet, trying again to connect shortly... 
com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace reaper_db does not exist
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:86)
	at io.cassandrareaper.storage.CassandraStorage.prepareMetricStatements(CassandraStorage.java:569)
	at io.cassandrareaper.storage.CassandraStorage.prepareStatements(CassandraStorage.java:523)
	at io.cassandrareaper.storage.CassandraStorage.<init>(CassandraStorage.java:242)
	at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:480)
	at io.cassandrareaper.ReaperApplication.tryInitializeStorage(ReaperApplication.java:303)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:181)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:98)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:117)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace reaper_db does not exist
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:181)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:249)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:218)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:221)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:210)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:952)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by adejanovski** [comment]
Hi, 

yes that was fixed in v2.2.1 which was released yesterday.
Sorry for this, pretty lame mistake 😅
