### ISSUE TITLE
Create repair for single table give 500 internal server error

### ISSUE THREAD

**Issue by JacobStruiksma** [thelastpickle/cassandra-reaper#1033]
When creating a new repair for a single table, an error is shown with http status code 500
If the same repair without the table specified, the repair run fine.

Reaper version 2.2.1 
postgres db as backend
Running the instance in a container

Log for repair run request when it fails with table specified 
I have replaced the clustername, keyspacename, owner name and the tablename  with placeholders for security resons

```
2021-03-09T10:25:07.461575562Z ERROR  [2021-03-09 10:25:07,460] [dw-193 - POST /repair_run?clusterName={clustername}&keyspace={keyspacename}&owner={owner}&tables={tablename}&segmentCount=1&repairParallelism=PARALLEL&intensity=1&cause=again&incrementalRepair=false&repairThreadCount=1] i.d.j.e.LoggingExceptionMapper - Error handling a request: a1cf3efe32df4fe0 
2021-03-09T10:25:07.461635164Z java.lang.IllegalArgumentException: unit conflicts with existing in {clustername}:{keyspacename}
2021-03-09T10:25:07.461646064Z 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
2021-03-09T10:25:07.461655865Z 	at io.cassandrareaper.service.RepairUnitService.createRepairUnit(RepairUnitService.java:134)
2021-03-09T10:25:07.461664265Z 	at io.cassandrareaper.service.RepairUnitService.getOrCreateRepairUnit(RepairUnitService.java:72)
2021-03-09T10:25:07.461742768Z 	at io.cassandrareaper.resources.RepairRunResource.addRepairRun(RepairRunResource.java:210)
2021-03-09T10:25:07.461753968Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-03-09T10:25:07.461762068Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-03-09T10:25:07.461769969Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-03-09T10:25:07.461777869Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2021-03-09T10:25:07.461785769Z 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
2021-03-09T10:25:07.461793869Z 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
2021-03-09T10:25:07.461801970Z 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
2021-03-09T10:25:07.461822570Z 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
2021-03-09T10:25:07.461830271Z 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
2021-03-09T10:25:07.461837471Z 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
2021-03-09T10:25:07.461844571Z 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
2021-03-09T10:25:07.461893073Z 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
2021-03-09T10:25:07.461902573Z 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
2021-03-09T10:25:07.461909573Z 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
2021-03-09T10:25:07.461916573Z 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
2021-03-09T10:25:07.461923374Z 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
2021-03-09T10:25:07.461930474Z 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
2021-03-09T10:25:07.461939574Z 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
2021-03-09T10:25:07.461946574Z 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
2021-03-09T10:25:07.461953575Z 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
2021-03-09T10:25:07.461960475Z 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
2021-03-09T10:25:07.461967275Z 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
2021-03-09T10:25:07.461974275Z 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
2021-03-09T10:25:07.461981176Z 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
2021-03-09T10:25:07.461988176Z 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
2021-03-09T10:25:07.461994976Z 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
2021-03-09T10:25:07.462001876Z 	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
2021-03-09T10:25:07.462008776Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
2021-03-09T10:25:07.462015777Z 	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
2021-03-09T10:25:07.462022577Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
2021-03-09T10:25:07.462029677Z 	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
2021-03-09T10:25:07.462036677Z 	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
2021-03-09T10:25:07.462076879Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
2021-03-09T10:25:07.462084079Z 	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311)
2021-03-09T10:25:07.462090879Z 	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265)
2021-03-09T10:25:07.462098579Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
2021-03-09T10:25:07.462105680Z 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
2021-03-09T10:25:07.462112780Z 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
2021-03-09T10:25:07.462119680Z 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
2021-03-09T10:25:07.462126780Z 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
2021-03-09T10:25:07.462134181Z 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
2021-03-09T10:25:07.462141481Z 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
2021-03-09T10:25:07.462148381Z 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
2021-03-09T10:25:07.462155281Z 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
2021-03-09T10:25:07.462162282Z 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
2021-03-09T10:25:07.462169382Z 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
2021-03-09T10:25:07.462176382Z 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
2021-03-09T10:25:07.462183282Z 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
2021-03-09T10:25:07.462190382Z 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
2021-03-09T10:25:07.462197483Z 	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
2021-03-09T10:25:07.462204583Z 	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
2021-03-09T10:25:07.462211483Z 	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
2021-03-09T10:25:07.462218683Z 	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
2021-03-09T10:25:07.462225784Z 	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
2021-03-09T10:25:07.462232884Z 	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
2021-03-09T10:25:07.462239884Z 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
2021-03-09T10:25:07.462246884Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
2021-03-09T10:25:07.462258785Z 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
2021-03-09T10:25:07.462265885Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
2021-03-09T10:25:07.462273485Z 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
2021-03-09T10:25:07.462280485Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
2021-03-09T10:25:07.462287486Z 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
2021-03-09T10:25:07.462294386Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
2021-03-09T10:25:07.462301386Z 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
2021-03-09T10:25:07.462308186Z 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
2021-03-09T10:25:07.462315187Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
2021-03-09T10:25:07.462322087Z 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
2021-03-09T10:25:07.462329087Z 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
2021-03-09T10:25:07.462335987Z 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
2021-03-09T10:25:07.462342888Z 	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
2021-03-09T10:25:07.462349988Z 	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
2021-03-09T10:25:07.462356888Z 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:703)
2021-03-09T10:25:07.462363788Z 	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
2021-03-09T10:25:07.462370688Z 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
2021-03-09T10:25:07.462377689Z 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
2021-03-09T10:25:07.462384589Z 	at org.eclipse.jetty.server.Server.handle(Server.java:505)
2021-03-09T10:25:07.462391589Z 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
2021-03-09T10:25:07.462398589Z 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
2021-03-09T10:25:07.462405490Z 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
2021-03-09T10:25:07.462412490Z 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
2021-03-09T10:25:07.462419290Z 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
2021-03-09T10:25:07.462426190Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
2021-03-09T10:25:07.462433391Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
2021-03-09T10:25:07.462445591Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
2021-03-09T10:25:07.462452891Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
2021-03-09T10:25:07.462459991Z 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
2021-03-09T10:25:07.462467192Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
2021-03-09T10:25:07.462474192Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
2021-03-09T10:25:07.462481192Z 	at java.lang.Thread.run(Thread.java:748)
```
In case if the table is not specified:
```
2021-03-09T10:25:30.930685516Z INFO   [2021-03-09 10:25:30,930] [dw-195 - POST /repair_run?clusterName={clusterName}&keyspace={keyspacename}&owner={owner}&segmentCount=1&repairParallelism=PARALLEL&intensity=1&cause=again&incrementalRepair=false&repairThreadCount=1] i.c.s.SegmentGenerator - Less segments required than there are vnode. Coalescing eligible token ranges... 
```

**Comment by adejanovski** [comment]
Yes, that happens when repair units overlap on at least one table (meaning you already have a schedule that repairs that keyspace and table).
We'll deal with it in #1008 and allow such overlaps with a warning.
