### ISSUE TITLE
cassandra-reaper-2.3.1- Storage is not ready yet, trying again to connect shortly

### ISSUE THREAD

**Issue by rashmimisal07** [thelastpickle/cassandra-reaper#1050]
Unable to install reaper on open source apache cassandra 3.0.13 version. its giving error mentioned below
ERROR  [2021-04-17 16:05:03,798] [main] i.c.ReaperApplication - Storage is not ready yet, trying again to connect shortly...
org.cognitor.cassandra.migration.MigrationException: Found two different files for version 23
        at org.cognitor.cassandra.migration.collector.FailOnDuplicatesCollector.collect(FailOnDuplicatesCollector.java:41)
        at org.cognitor.cassandra.migration.MigrationRepository.scanForScripts(MigrationRepository.java:185)
        at org.cognitor.cassandra.migration.MigrationRepository.<init>(MigrationRepository.java:131)
        at org.cognitor.cassandra.migration.MigrationRepository.<init>(MigrationRepository.java:114)
        at org.cognitor.cassandra.migration.MigrationRepository.<init>(MigrationRepository.java:102)
        at io.cassandrareaper.storage.CassandraStorage.initializeCassandraSchema(CassandraStorage.java:276)
        at io.cassandrareaper.storage.CassandraStorage.initializeAndUpgradeSchema(CassandraStorage.java:252)
        at io.cassandrareaper.storage.CassandraStorage.<init>(CassandraStorage.java:240)
        at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:480)
        at io.cassandrareaper.ReaperApplication.tryInitializeStorage(ReaperApplication.java:303)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:181)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:98)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:117)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-215) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-215

**Comment by adejanovski** [comment]
well, that's an interesting one 🤔 There's clearly a single migration 23: https://github.com/thelastpickle/cassandra-reaper/tree/2.2.3/src/server/src/main/resources/db/cassandra

Are you performing a fresh install or is it an upgrade?
I'd recommend to start from scratch by recreating the reaper_db keyspace and uninstalling/reinstalling reaper (try 2.2.4 which was just released).

**Comment by rashmimisal07** [comment]
Thanks for suggestion this works for me as have successfully installed reaper on my VM machine.
[root@cass-t3-01.prod.cre.az-eastus2 bin]# ./cassandra-reaper
Looking for reaper under /usr
WARN   [2021-04-20 07:43:57,312] [main] i.c.ReaperApplication - Reaper is ready to get things done!

However, am unable to connect webui with same ip & below mentioned error while connecting with http://10.1
79.230.50:8080/webui/
This site can’t be reached 10.179.230.50 took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

Could you please help me out with this.

**Comment by adejanovski** [comment]
I'll close this ticket as it's been inactive for a while.
Feel free to reopen it if you're still experiencing this issue.
