### ISSUE TITLE
An I/O error has occured while writing a response message entity to container output stream

### ISSUE THREAD

**Issue by brianpham** [thelastpickle/cassandra-reaper#1068]
I recently upgraded our cassandra-reaper docker image from 1.4.8 to 2.2.4 and seeing this error in the logs. Cassandra reaper seems to be running properly, but was curious if anyone else is seeing this error or has a fix for this issue. 

```
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]: ERROR  [2021-05-14 17:08:34,352] [dw-75 - GET /cluster/dev-fatline] o.g.j.s.ServerRuntime$Responder - An I/O error has occurred while writing a response message entity to the container output stream.
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]: org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:92)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.Server.handle(Server.java:505)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at java.lang.Thread.run(Thread.java:748)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]: Caused by: org.eclipse.jetty.io.EofException: null
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:284)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:826)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:550)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:850)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:921)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor$GzipBufferCB.process(GzipHttpOutputInterceptor.java:398)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.gzip(GzipHttpOutputInterceptor.java:148)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.write(GzipHttpOutputInterceptor.java:117)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:249)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:225)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:524)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:325)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2085)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:549)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ser.std.EnumSerializer.serialize(EnumSerializer.java:132)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ser.std.EnumSerializer.serialize(EnumSerializer.java:27)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.module.afterburner.ser.ObjectMethodPropertyWriter.serializeAsField(ObjectMethodPropertyWriter.java:87)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContentsUsing(IndexedListSerializer.java:142)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:88)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.module.afterburner.ser.ObjectFieldPropertyWriter.serializeAsField(ObjectFieldPropertyWriter.java:87)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:913)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:625)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         ... 74 common frames omitted
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]: Caused by: java.io.IOException: Broken pipe
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at sun.nio.ch.IOUtil.write(IOUtil.java:65)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:262)
May 14 17:08:34 ip-10-0-2-115.ec2.internal docker[9931]:         ... 119 common frames omitted
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-202) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-202

**Comment by adejanovski** [comment]
I'll close this ticket since it's been inactive for a while.
Feel free to reopen you're still experiencing this on the latest release.
