### ISSUE TITLE
HTTP 550 is being returned when repair run is deleted

### ISSUE THREAD

**Issue by adutra** [thelastpickle/cassandra-reaper#1090]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13937767)

The following REST call:

```
DELETE /repair_run/{id}
```

Is causing Reaper to return HTTP 500 to the client, and the following stack trace is logged:

```
i.d.j.e.LoggingExceptionMapper - Error handling a request: 28aa7519bbc77c3d
java.lang.IllegalStateException: startTime only valid when runState is not NOT_STARTED. DELETED null
at com.google.common.base.Preconditions.checkState(Preconditions.java:737)
at io.cassandrareaper.core.RepairRun$Builder.build(RepairRun.java:303)
at io.cassandrareaper.storage.MemoryStorage.deleteRepairRun(MemoryStorage.java:258)
at io.cassandrareaper.resources.RepairRunResource.deleteRepairRun(RepairRunResource.java:761)
```

As far as I can tell, it seems that the repair run is deleted, only the HTTP 500 status code makes the client think that something bad happened.

The error above also happens when using the Web UI, although the Web UI does not surface the error to the user.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-108) by [Unito](https://www.unito.io)
┆Issue Number: REAP-108

**Comment by Rooks103** [comment]
@adutra Could you clarify a bit more about your setup? I tried validating this on a version 3.1.1 with the following:

1. Tried calling `DELETE /repair_run/<Invalid ID>`. This gave me a 400 response with an error `required query parameter "owner" is missing`. 
2. Tried calling `DELETE /repair_run/<Valid ID>`. Same as above. 400 saying it needed the owner value.
3. Tried calling `DELETE /repair_run/<Valid ID>?owner=<Valid Owner>`. This returned a 200 and the repair was deleted. The repair was in the Paused state when I issued the delete.
4. Tried calling `DELETE /repair_run/<Valid ID>?owner=<Invalid Owner>`. This returned a 409 with an error `Repair run <Valid ID> is not owned by the user you defined <Invalid Owner>`.
5.  Tried calling `DELETE /repair_run/<Valid ID>?owner=<Valid Owner>` while the repair was running. This returned a 409 with an error `Repair run with id "<Valid ID>" is currently running, and must be stopped before deleting`.
