### ISSUE TITLE
Reaper throws javax.management.InstanceNotFoundException against C* 4.0

### ISSUE THREAD

**Issue by adutra** [thelastpickle/cassandra-reaper#1155]
Using Reaper 3.1.0 and Cassandra 4.0.1, Reaper repeatedly logs the following stack trace:

```
ERROR  [2022-01-02 20:42:42,972] [ForkJoinPool-1-worker-29] i.c.j.JmxProxy - Error getting pending compactions attribute from JMX
javax.management.InstanceNotFoundException: org.apache.cassandra.metrics:type=Compaction,name=PendingTasks
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
	at jdk.remoteref/jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source)
	at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:904)
	at io.cassandrareaper.jmx.JmxProxyImpl.getPendingCompactions(JmxProxyImpl.java:404)
	at io.cassandrareaper.jmx.CompactionProxy.getPendingCompactions(CompactionProxy.java:100)
	at io.cassandrareaper.jmx.ClusterFacade.listCompactionStatsDirect(ClusterFacade.java:493)
	at io.cassandrareaper.service.MetricsService.grabAndStoreCompactionStats(MetricsService.java:165)
	at io.cassandrareaper.service.Heart.updateMetricsForNode(Heart.java:272)
	at io.cassandrareaper.service.Heart.lambda$updateMetricsForClusters$6(Heart.java:218)
```

This doesn't seem to prevent Reaper from functioning properly, but definitely bloats the logs.

This could be related to [CASSANDRA-16083](https://issues.apache.org/jira/browse/CASSANDRA-16083): some MBeans were redesigned in C* 4.0. Maybe the Compaction MBean is one of them.

**Comment by adejanovski** [comment]
I'm unable to reproduce this issue running Reaper's latest master locally with ccm on 4.0.1.
Also, the Compaction MBean seems unchanged in Cassandra 4.x: 

![Capture d’écran 2022-01-05 à 10 56 19](https://user-images.githubusercontent.com/5096002/148223168-0d8249c3-e285-4667-af71-29a9c4adb11f.png)

Could you post some steps to reproduce the issue?
Thanks!

**Comment by adutra** [comment]
@adejanovski I initially spotted it working on K8ssandra support for Reaper. 

I confirm that I'm still seeing the issue unfortunately, but it seems to happen only in multi-dc deployments. For example, the following `K8ssandraCluster` definition exhibits the issue:

https://github.com/k8ssandra/k8ssandra-operator/blob/506d8dae3a3044ee30f0edc485ddab680787b3aa/test/testdata/fixtures/multi-dc-reaper/k8ssandra.yaml

I am going to try to come up with a more concise test case that reproduces the issue.

Ont of the specificities of multi-dc Reaper deployments is that each Reaper instance is started with datacenter availability EACH. Could that be part of the problem?

**Comment by adutra** [comment]
I've spent an insane amount of time trying to create a reproducer for this, with no success. It turns out that only that specific K8ssandra test exhibits the described behavior, so it's probably something wrong in K8ssandra's test infrastructure. I'm closing this.
