### ISSUE TITLE
Schedule repairs often stuck

### ISSUE THREAD

**Issue by rkozlo** [thelastpickle/cassandra-reaper#1271]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=19748096)

Hi
Running already repairs on all my clusters via reaper. Did monitoring on zabbix and often have alert about stuck repairs. Indeed it stuck on one or two segments. One segment processing for day or two without any fail increment. What i do then is abort this segments, and after that it is processing without problems

```
INFO   [2023-02-05 08:53:29,204] [xxclusterxx:11c2e1a0-a529-11ed-96c7-7b75a05906e8] i.c.s.RepairRunner - Next segment to run : 11c3f31c-a529-11ed-96c7-7b75a05906e8 
INFO   [2023-02-05 08:53:29,555] [xxclusterxx:11c2e1a0-a529-11ed-96c7-7b75a05906e8:11c3f31c-a529-11ed-96c7-7b75a05906e8] i.c.j.JmxProxy - Triggering repair of range (-5872107358247029913,-5829083245281671680] for keyspace "keyspace" on host 10.96.38.19, with repair parallelism dc_parallel, in cluster with Cassandra version '3.11.4' (can use DATACENTER_AWARE 'true'), for column families: ["cols"] 
INFO   [2023-02-05 08:53:29,555] [xxclusterxx:11c2e1a0-a529-11ed-96c7-7b75a05906e8:11c3f31c-a529-11ed-96c7-7b75a05906e8] i.c.j.JmxProxy - Triggering repair for ranges -5872107358247029913:-5829083245281671680,8097276572200661501:8103100846682401961,600454922283040533:627875566288457831,-3460958998763646825:-3435484225780747876,-5436553444301958598:-5425737226655283325 
INFO   [2023-02-05 08:53:30,327] [xxclusterxx:11c2e1a0-a529-11ed-96c7-7b75a05906e8:11c3f31c-a529-11ed-96c7-7b75a05906e8] i.c.s.RepairRunner - Triggered repair of segment 11c3f31c-a529-11ed-96c7-7b75a05906e8 via host 10.96.38.19 
INFO   [2023-02-05 08:53:30,327] [xxclusterxx:11c2e1a0-a529-11ed-96c7-7b75a05906e8:11c3f31c-a529-11ed-96c7-7b75a05906e8] i.c.s.SegmentRunner - Repair for segment 11c3f31c-a529-11ed-96c7-7b75a05906e8 started, status wait will timeout in 1800000 millis 
INFO   [2023-02-05 08:54:08,314] [xxclusterxx:11c2e1a0-a529-11ed-96c7-7b75a05906e8:11c3f31c-a529-11ed-96c7-7b75a05906e8] i.c.s.SegmentRunner - Repair command 6684 on segment 11c3f31c-a529-11ed-96c7-7b75a05906e8 returned with state STARTED 
INFO   [2023-02-05 08:54:08,314] [xxclusterxx:11c2e1a0-a529-11ed-96c7-7b75a05906e8:11c3f31c-a529-11ed-96c7-7b75a05906e8] i.c.s.SegmentRunner - Repair command 6684 on segment 11c3f31c-a529-11ed-96c7-7b75a05906e8 has been cancelled while running 
INFO   [2023-02-05 08:54:08,314] [xxclusterxx:11c2e1a0-a529-11ed-96c7-7b75a05906e8:11c3f31c-a529-11ed-96c7-7b75a05906e8] i.c.s.SegmentRunner - Postponing segment 11c3f31c-a529-11ed-96c7-7b75a05906e8 
WARN   [2023-02-05 08:54:20,339] [xxclusterxx:11c2e1a0-a529-11ed-96c7-7b75a05906e8:11c3f31c-a529-11ed-96c7-7b75a05906e8] i.c.s.SegmentRunner - Failed to connect to a coordinator node for segment 11c3f31c-a529-11ed-96c7-7b75a05906e8 
INFO   [2023-02-05 08:54:32,442] [xxclusterxx:11c2e1a0-a529-11ed-96c7-7b75a05906e8:11c3f31c-a529-11ed-96c7-7b75a05906e8] i.c.s.RepairRunner - Postponed a segment because no coordinator was reachable 
INFO   [2023-02-05 08:54:32,447] [xxclusterxx:11c2e1a0-a529-11ed-96c7-7b75a05906e8:11c3f31c-a529-11ed-96c7-7b75a05906e8] i.c.s.SegmentRunner - Postponing segment 11c3f31c-a529-11ed-96c7-7b75a05906e8 
ERROR  [2023-02-05 08:54:44,556] [xxclusterxx:11c2e1a0-a529-11ed-96c7-7b75a05906e8:11c3f31c-a529-11ed-96c7-7b75a05906e8] i.c.s.RepairRunner - Executing SegmentRunner failed 
```

![reaper!UNITO-UNDERSCORE!issue](https://user-images.githubusercontent.com/44550015/216913967-20c034b2-6563-4b97-bd98-e714b7c6c53b.png)

```
{"cause": "scheduled run (schedule id 89ef4a20-a136-11ed-96c7-7b75a05906e8)", "owner": "owner", "id": "11c2e1a0-a529-11ed-96c7-7b75a05906e8", "state": "RUNNING", "intensity": 0.8999999761581421, "duration": "23 hours 42 minutes 54 seconds", "cluster_name": "xxckysterxx", "column_families": ["cols"], "keyspace_name": "keyspace", "incremental_repair": false, "total_segments": 235, "repair_parallelism": "DATACENTER_AWARE", "segments_repaired": 234, "last_event": "All nodes are busy or have too many pending compactions for the remaining candidate segments.", "nodes": [], "datacenters": [], "blacklisted_tables": [], "repair_thread_count": 1, "repair_unit_id": "89eeade0-a136-11ed-96c7-7b75a05906e8", "segment_timeout": 30, "adaptive_schedule": true, "creation_time": "2023-02-05T07:45:32Z", "start_time": "2023-02-05T07:45:32Z", "end_time": null, "pause_time": null, "current_time": "2023-02-06T07:28:27Z", "estimated_time_of_arrival": "2023-02-06T07:34:32Z"}
```

Shouldn't it timeout with fail and give another try?

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-71) by [Unito](https://www.unito.io)
┆Issue Number: REAP-71

**Comment by rkozlo** [comment]
One maybe usefule info. In cassandra-reaper logs infos about this segment only at time when it started. After that not even one occurence

**Comment by lapo-luchini** [comment]
Same here, I often have segments older than the 120 minutes that I have configured as timeout.

**Comment by pedro-gordo** [comment]
I might have hit a bug related to this. We're running 3.2. I had a repair that was not getting completed even though there was only one segment left to go. Even though there were no pending compactions, and the nodes had a lot of headroom, there were always two of these messages:

```
Attempting to run new segment...
All nodes are busy or have too many pending compactions for the remaining candidate segments.
All nodes are busy or have too many pending compactions for the remaining candidate segments.
Repair amount done 179.0
```

After aborting the segment, pausing the repair, and then re-activating it, I noticed the following error on the log:

```
ERROR  [2023-05-18 14:45:53,642] [<CLUSTER NAME>:<CLUSTER UUID>] i.c.s.RepairRunner - RepairRun FAILURE, scheduling retry 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at io.cassandrareaper.service.RepairRunner.isAllowedToRun(RepairRunner.java:267)
	at io.cassandrareaper.service.RepairRunner.run(RepairRunner.java:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66)
	at java.base/java.lang.Thread.run(Unknown Source)
```
