### ISSUE TITLE
Exceptions in Cassandra logs while repairing

### ISSUE THREAD

**Issue by beevee** [thelastpickle/cassandra-reaper#133]
Not actually an issue, just a question. I couldn't find any mailing list or chat to ask.

I'm currently repairing two separate clusters running Cassandra 2.2.8 and 2.2.9. An error appears in Cassandra logs in both clusters from time to time, something like this:

```
Repair session 16814280-6174-11e7-99ee-57693e6498d2 for range (-2834815707274975924,-2830421819290266676] failed with error Terminate session is called
java.io.IOException: Terminate session is called
	at org.apache.cassandra.service.ActiveRepairService.terminateSessions(ActiveRepairService.java:191) ~[apache-cassandra-2.2.9.jar:2.2.9]
	at org.apache.cassandra.service.StorageService.forceTerminateAllRepairSessions(StorageService.java:3139) [apache-cassandra-2.2.9.jar:2.2.9]
	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71) [na:1.8.0_121]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275) [na:1.8.0_121]
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112) [na:1.8.0_121]
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46) [na:1.8.0_121]
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237) [na:1.8.0_121]
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138) [na:1.8.0_121]
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252) [na:1.8.0_121]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) [na:1.8.0_121]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [na:1.8.0_121]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468) [na:1.8.0_121]
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76) [na:1.8.0_121]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309) [na:1.8.0_121]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401) [na:1.8.0_121]
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829) [na:1.8.0_121]
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346) [na:1.8.0_121]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) [na:1.8.0_121]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) [na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_121]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) [na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568) [na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826) [na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683) [na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
```

...or this:

```
ERROR [AntiEntropyStage:1] 2017-07-05 15:59:45,171 RepairMessageVerbHandler.java:180 - Got error, removing parent repair session
```

...or this:

```
Exception in thread Thread[AntiEntropyStage:1,5,main]
java.lang.RuntimeException: Parent repair session with id = 6c7175e0-6181-11e7-b890-1368b2e507cf has failed.
	at org.apache.cassandra.service.ActiveRepairService.getParentRepairSession(ActiveRepairService.java:378) ~[apache-cassandra-2.2.8.jar:2.2.8]
	at org.apache.cassandra.service.ActiveRepairService.removeParentRepairSession(ActiveRepairService.java:393) ~[apache-cassandra-2.2.8.jar:2.2.8]
	at org.apache.cassandra.repair.RepairMessageVerbHandler.doVerb(RepairMessageVerbHandler.java:182) ~[apache-cassandra-2.2.8.jar:2.2.8]
	at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:67) ~[apache-cassandra-2.2.8.jar:2.2.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
```

Should I be worried that Cassandra failed to repair some of the segments? Can Reaper detect these kinds of failures and retry repairs?

**Comment by beevee** [comment]
"From time to time" means that we see around 100-150 of these log records while repairing a 5TB cluster (1537 segments).

**Comment by beevee** [comment]
There is also a DEBUG-level message just before an ERROR:

```
DEBUG [AntiEntropyStage:1] 2017-07-05 15:59:45,170 RepairMessageVerbHandler.java:143 - Syncing SyncRequest{initiator=/192.168.191.187, src=/192.168.191.209, dst=/192.168.191.211, ranges=[(3081609092902515550,3081625323981369878], (3082079794189291039,3082096025268145366], (3082388184687523256,3082404415766377584], (3082420646845231911,3082436877924086238], (3082615419791483837,3082631650870338164], (3082810192737735764,3082826423816590091], (3083199738630239617,3083215969709093944], (3083248431866802599,3083264662945656926], (3083297125103365580,3083313356182219908], (3083313356182219908,3083329587261074235], (3083362049418782889,3083378280497637217], (3083410742655345871,3083426973734200198], (3083556822365034816,3083573053443889144], (3083654208838160779,3083670439917015106], (3083767826390141070,3083784057468995397], (3084092447967227615,3084108679046081942], (3084319683071188195,3084335914150042522], (3084628073569420413,3084644304648274740], (3084676766805983394,3084692997884837721], (3085082543777341575,3085098774856195902], (3085342241039010810,3085358472117865137], (3085618169379534373,3085634400458388700], (3085666862616097355,3085683093694951682], (3085731786931514663,3085748018010368990], (3085877866641203608,3085894097720057935], (3085991484193183899,3086007715272038226], (3086072639587455535,3086088870666309862], (3086251181454853134,3086267412533707461], (3086348567927979097,3086364799006833425], (3086559571953085352,3086575803031939679], (3086770575978191605,3086786807057045932], (3086835500293608914,3086851731372463241], (3086851731372463241,3086867962451317568], (3087014042161006514,3087030273239860841], (3087078966476423823,3087095197555278150], (3087241277264967095,3087257508343821422], (3087468512368927676,3087484743447782003], (3088458608179041636,3088474839257895963], (3088653381125293563,3088669612204147890], (3088702074361856545,3088718305440710872], (3088913078386962798,3088929309465817125], (3088978002702380107,3088994233781234434], (3089221468885195016,3089237699964049343], (3089513628304572905,3089529859383427232], (3089643476935407523,3089659708014261850], (3089724632329679159,3089740863408533487], (3089903174197076758,3089919405275931085], (3090065484985620031,3090081716064474358], (3090195333616454648,3090211564695308975], (3090292720089580611,3090325182247289266], (3090503724114686864,3090519955193541192], (3090552417351249846,3090568648430104173], (3090682265982084464,3090698497060938791], (3091477588845946497,3091493819924800825], (3092143063078973914,3092159294157828241], (3092289142788662859,3092305373867517186], (3092305373867517186,3092337836025225841], (3092354067104080168,3092370298182934495], (3092435222498351804,3092451453577206131], (3092646226523458057,3092662457602312385], (3092954617021690275,3092970848100544602], (3093327931835339801,3093344162914194128], (3093717477727843654,3093733708806697981], (3093798633122115290,3093814864200969617], (3094058330383784525,3094074561462638852], (3094253103330036452,3094269334408890779], (3094512800591705688,3094545262749414342], (3094837422168792232,3094853653247646559], (3095162043745878776,3095178274824733103], (3095876211215469174,3095892442294323501], (3096038522004012447,3096054753082866774], (3096070984161721101,3096087215240575428], (3096119677398284082,3096135908477138409], (3096298219265681682,3096314450344536009], (3096720227315894189,3096736458394748516], (3096882538104437462,3096898769183291789], (3097126004287252370,3097142235366106697], (3097369470470067278,3097385701548921605], (3097694092047153822,3097710323126008149], (3097726554204862477,3097742785283716804], (3097775247441425458,3097791478520279786]]} org.apache.cassandra.repair.messages.SyncRequest@549dfc05
```

I'm running Reaper version 0.6.1

**Comment by adejanovski** [comment]
Reaper has a 30mn timeout by default to repair each segment. If a segment doesn't complete within the timeout, Reaper will force terminate then repair session and reschedule the segment later.

If you have frequent terminations, it means you either have not enough segments or have a timeout that is too short.
You can try adjusting both to match your cluster's specific requirements.

**Comment by beevee** [comment]
OK, that's fine. I just wanted to know whether Reaper drops these segments altogether or just reschedules them. Thanks!
