### ISSUE TITLE
Cassandra 5x: removal of deprecated dateof function causes startup failure in cassandra-migration library

### ISSUE THREAD

**Issue by denniskline** [thelastpickle/cassandra-reaper#1436]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=44159237)

Running reaper against a 5.0.0-alpha2 cluster fails performing Database migration due to the removal of "dateof".

`2023-11-09 14:50:59,509 [ERROR] [main] i.c.ReaperApplication - Storage is not ready yet, trying again to connect shortly...
com.datastax.driver.core.exceptions.InvalidQueryException: Unknown function dateof called
        at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
        at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:86)
        at org.cognitor.cassandra.migration.Database.<init>(Database.java:142)
        at org.cognitor.cassandra.migration.Database.<init>(Database.java:127)
        at org.cognitor.cassandra.migration.Database.<init>(Database.java:123)
        at io.cassandrareaper.storage.cassandra.MigrationManager.initializeCassandraSchema(MigrationManager.java:75)
        at io.cassandrareaper.storage.cassandra.MigrationManager.initializeAndUpgradeSchema(MigrationManager.java:59)
        at io.cassandrareaper.storage.cassandra.CassandraStorageFacade.<init>(CassandraStorageFacade.java:144)
        at io.cassandrareaper.storage.InitializeStorage.initializeStorageBackend(InitializeStorage.java:66)
        at io.cassandrareaper.ReaperApplication.tryInitializeStorage(ReaperApplication.java:438)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:177)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:87)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:99)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Unknown function dateof called
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:181)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:249)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:218)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:111)
        at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:992)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
`

This is an issue in a dependent library:
https://github.com/patka/cassandra-migration/blob/v2.4.0/cassandra-migration/src/main/java/org/cognitor/cassandra/migration/Database.java#L71

Once cassandra-migration is updated, this issue can be resolved with a change to the reaper pom.xml

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-24) by [Unito](https://www.unito.io)
┆Issue Number: REAP-24

**Comment by denniskline** [comment]
Corresponding issue:  https://github.com/patka/cassandra-migration/issues/83

**Comment by tuomari** [comment]
It seems that the [fix](/patka/cassandra-migration/pull/84) is available only for driver version 4+, ie the cassandra driver would need to be upgraded to use it, which would require refactoring and upgrading of the entire reaper project. 

In addition to migrating everything to use the new driver version, there are few libraries that do not have a direct upgrade path to driver version 4+, for example https://github.com/composable-systems/dropwizard-cassandra, which has been deprecated in 2018

**Comment by smarsching** [comment]
I found a workaround for using Reaper 3.6.1 with C* 5.0 as the storage for the Reaper meta-data:

When upgrading a cluster that has alrady been used for Reaper, simply setting the `REAPER_SKIP_SCHEMA_MIGRATION` environment variable for the Reaper process to `true` fixes the issue.

When using a new cluster for Reaper, one also has to manually create the necessary tables, because skipping the schema migration means that no tables are being created. The easiest way of doing this is first configuring Reaper to use a C* 4.1 cluster and then using the output of `DESCRIBE KEYSPACE` on the C* 5.0 cluster.

For convenience, I uploaded the [file with the relevant CQL statements](https://github.com/user-attachments/files/17465359/reaper-3.6.1-cql.txt), so that they can directly be applied on the C* 5.0 cluster. These commands assume that the empty keyspace for Reaper already exists and has the name `cassandra_reaper`.

This alone should be enough to make Reaper work with C* 5.0, but one might also want to populate the `schema_migrations` table, so that when a new version of Reaper is released that updates cassandra-migration, one can reenable schema migration. Populating the table can done by issuing the following statement in the CQL shell to load the data from the 
[reaper-3.6.1-schema_migration.csv](https://github.com/user-attachments/files/17465383/reaper-3.6.1-schema_migration.csv) file:

```
COPY cassandra_reaper.schema_migration FROM 'reaper-3.6.1-schema_migration.csv';
```

**Comment by soheilrahsaz** [comment]
in addition to @smarsching `reaper-3.6.1-cql.txt` file, in newer versions of reaper, a new field has been added to `repair_unit_v1` table: `subrange_incremental boolean`

**Comment by sivanand101** [comment]
Is there any update on the fix yet ? 
We are using latest Cassandra 5.X and Reaper 3.6.1 which are deployed as separate K8s pods. Since upgrading Reaper to 3.6.1, we are seeing this issue. 
Fix is already delivered in the migration-library. Waiting for Reaper to adopt the fix soon.

**Comment by kapilgit123** [comment]
I tried to modify the MigrationManager class in the reaper source code . I passed the CQLSession to the Database Constructor. The migration steps were performed , but after that the reaper server was forcefully shutdown.

Database database = new Database(cqlSession, config.getCassandraFactory().getKeyspace())) {

**Comment by adejanovski** [comment]
I'm working on a more ambitious plan which upgrades the cassandra bundle to the official dropwizard-cassandra and use the v4 Cassandra driver instead of v3.
That would allow upgrading to a newer version of the migration library, and is something we need to do at some point anyway.
The blast radius isn't small though and I'm not done with it yet.

**Comment by eranbetzalel** [comment]
After running all the needed CQL scripts from [Reaper Server DB Resources](https://github.com/thelastpickle/cassandra-reaper/tree/master/src/server/src/main/resources/db/cassandra) and setting up the `REAPER_SKIP_SCHEMA_MIGRATION` environment variable, I get the following error.

Now what?

```
INFO   [2025-02-24 11:34:51,382] [main] i.c.s.c.CassandraStorageFacade - Skipping schema migration as requested. 
com.datastax.driver.core.exceptions.InvalidQueryException: Some clustering keys are missing: segment_id
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:86)
	at io.cassandrareaper.storage.repairrun.CassandraRepairRunDao.prepareStatements(CassandraRepairRunDao.java:99)
	at io.cassandrareaper.storage.repairrun.CassandraRepairRunDao.<init>(CassandraRepairRunDao.java:93)
	at io.cassandrareaper.storage.cassandra.CassandraStorageFacade.<init>(CassandraStorageFacade.java:160)
	at io.cassandrareaper.storage.InitializeStorage.initializeStorageBackend(InitializeStorage.java:68)
	at io.cassandrareaper.ReaperDbMigrationCommand.run(ReaperDbMigrationCommand.java:53)
	at io.cassandrareaper.ReaperDbMigrationCommand.run(ReaperDbMigrationCommand.java:30)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:100)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Some clustering keys are missing: segment_id
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:181)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:249)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:218)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:111)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:992)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
