### ISSUE TITLE
Schema migration is broken for Cassandra 2.0

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#191]
When using the Cassandra backend for Reaper with C* 2.0, the schema migration will fail because caching options are using the 2.1 syntax : 
```
INFO   [2017-09-07 11:42:29,004] [main] o.c.c.m.MigrationRepository - Found 5 migration scripts 
Exception in thread "main" org.cognitor.cassandra.migration.MigrationException: Error during migration of script 002_table_properties.cql while executing 'ALTER TABLE cluster    WITH compaction = {'class': 'LeveledCompactionStrategy'}    AND caching = {'rows_per_partition': 'ALL'}'
	at org.cognitor.cassandra.migration.Database.execute(Database.java:159)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.cognitor.cassandra.migration.MigrationTask.migrate(MigrationTask.java:52)
	at com.spotify.reaper.storage.CassandraStorage.<init>(CassandraStorage.java:132)
	at com.spotify.reaper.ReaperApplication.initializeStorage(ReaperApplication.java:235)
	at com.spotify.reaper.ReaperApplication.run(ReaperApplication.java:142)
	at com.spotify.reaper.ReaperApplication.run(ReaperApplication.java:70)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:79)
	at com.spotify.reaper.ReaperApplication.main(ReaperApplication.java:91)
Caused by: com.datastax.driver.core.exceptions.SyntaxError: Invalid value for property 'caching'. It should be a string
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:64)
	at org.cognitor.cassandra.migration.Database.executeStatement(Database.java:167)
	at org.cognitor.cassandra.migration.Database.execute(Database.java:151)
	... 11 more
```

**Comment by treenerd** [comment]
I have the same issue.

**Comment by adejanovski** [comment]
@michaelsembwever, do we want to support 2.0 for the backend storage?

**Comment by michaelsembwever** [comment]
No. We can ask users that the Reaper storage is minimum 2.1 Cassandra.
