### ISSUE TITLE
Cassandra 3.0.x + Cassandra Storage bug

### ISSUE THREAD

**Issue by neogenix** [thelastpickle/cassandra-reaper#21]
I've setup my cassandra-reaper config as follows: 

```
segmentCount: 200
repairParallelism: DATACENTER_AWARE
repairIntensity: 0.9
repairRunThreadCount: 15
hangingRepairTimeoutMins: 30
incrementalRepair: false
scheduleDaysBetween: 7
storageType: cassandra
enableCrossOrigin: true

logging:
  level: DEBUG
  loggers:
    io.dropwizard: INFO
    org.eclipse.jetty: WARN
  appenders:
    - type: console
      logFormat: "%-6level [%d] [%t] %logger{5} - %msg %n"

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 0.0.0.0
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 0.0.0.0

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://127.0.0.1/reaper

cassandra:
  clusterName: "StageCassandra"
  contactPoints: ["<ip>", "<ip>", "<ip>"]
  keyspace: reaper_db
```

And, after creating the keyspace per https://github.com/thelastpickle/cassandra-reaper/blob/master/src/main/db/reaper_cassandra_db.cql

I get this error after trying to add my first repair. 

```ERROR  [2016-11-15 23:28:49,461] [dw-39 - GET /repair_run] i.d.j.e.LoggingExceptionMapper - Error handling a request: dc2c3db88de0809b
java.lang.IllegalArgumentException: No enum constant org.apache.cassandra.repair.RepairParallelism.dc_parallel
	at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_111]
	at org.apache.cassandra.repair.RepairParallelism.valueOf(RepairParallelism.java:26) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.spotify.reaper.storage.CassandraStorage.buildRepairRunFromRow(CassandraStorage.java:703) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.spotify.reaper.storage.CassandraStorage.getRepairRunsAsync(CassandraStorage.java:260) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.spotify.reaper.storage.CassandraStorage.getRepairRunsForCluster(CassandraStorage.java:223) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.spotify.reaper.resources.RepairRunResource.listRepairRuns(RepairRunResource.java:447) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at io.dropwizard.jersey.guava.OptionalResourceMethodDispatchAdapter$OptionalRequestDispatcher.dispatch(OptionalResourceMethodDispatchAdapter.java:37) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.server.impl.uri.rules.ResourceObjectRule.accept(ResourceObjectRule.java:100) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:348) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:127) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:44) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:248) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:211) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:175) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:92) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:162) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.server.Server.handle(Server.java:446) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

With memory storage, I don't get said errors. 

Here's the respective versions: 

Cassandra:
```
apt-cache policy cassandra
cassandra:
  Installed: 3.0.9
  Candidate: 3.0.9
  Version table:
 *** 3.0.9 0
        500 http://www.apache.org/dist/cassandra/debian/ 30x/main amd64 Packages
        100 /var/lib/dpkg/status
```

Oracle Java:
```
apt-cache policy oracle-java8-installer
oracle-java8-installer:
  Installed: 8u111+8u111arm-1~webupd8~0
  Candidate: 8u111+8u111arm-1~webupd8~0
  Version table:
 *** 8u111+8u111arm-1~webupd8~0 0
        500 http://ppa.launchpad.net/webupd8team/java/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

Cassandra-Reaper:
```
apt-cache policy reaper
reaper:
  Installed: 0.3.2-SNAPSHOT
  Candidate: 0.3.2-SNAPSHOT
  Version table:
 *** 0.3.2-SNAPSHOT 0
        100 /var/lib/dpkg/status
```

The reaper was built from master yesterday using `make deb` and oracle Java (plus my two PR's).

**Comment by adejanovski** [comment]
I pushed a fix into master for that issue.
Could you check that it works for you now ?

**Comment by neogenix** [comment]
@adejanovski Great news! That def. fixed the cassandra storage / exception stuff(s)
