### ISSUE TITLE
maxFileSize property to limit log file size is not working 

### ISSUE THREAD

**Issue by Ritu-Thakur** [thelastpickle/cassandra-reaper#224]
We are trying to use maxFileSize property in cassandra-reaper.yaml to limit the size of log files:
logging:
level: WARN
loggers:
io.dropwizard: INFO
org.eclipse.jetty: INFO
appenders:

* type: file
  currentLogFilename: /reaper/logs/cassandra-reaper.log
  threshold: ALL
  queueSize: 512
  discardingThreshold: 0
  archive: true
  archivedLogFilenamePattern: /reaper/logs/cassandra-reaper-%i.log
  archivedFileCount: 20
  maxFileSize:  20MB
  timeZone: UTC
  logFormat: "%-6level [%d] [%t] %logger{5} - %msg %n"

But when running reaper we get :
Exception in thread "main" java.lang.NoSuchMethodError: ch/qos/logback/core/rolling/SizeBasedTriggeringPolicy.setMaxFileSize(Ljava/lang/String;)V (loaded from file:/reaper/lib/cassandra-reaper-0.6.2.jar by sun.misc.Launcher$AppClassLoader@fd79c01e) called from class io.dropwizard.logging.FileAppenderFactory (loaded from file:/reaper/lib/cassandra-reaper-0.6.2.jar by sun.misc.Launcher$AppClassLoader@fd79c01e).
at io.dropwizard.logging.FileAppenderFactory.buildAppender(FileAppenderFactory.java:231)
at io.dropwizard.logging.FileAppenderFactory.build(FileAppenderFactory.java:198)
at io.dropwizard.logging.DefaultLoggingFactory.configure(DefaultLoggingFactory.java:134)
at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:81)
at io.dropwizard.cli.Cli.run(Cli.java:75)
at io.dropwizard.Application.run(Application.java:79)
at com.spotify.reaper.ReaperApplication.main(ReaperApplication.java:84)

It is coming because io.dropwizard.logging.FileAppenderFactory in dropwizard-logging-1.0.7.jar calls ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy.SizeBasedTriggeringPolicy.setMaxFileSize(String) which is not present in logback-core-1.2.2(getting used in 0.6.2/0.7 reaper versions)

logback-core-1.2.2.jar has SizeBasedTriggeringPolicy.setMaxFileSize(FileSize) and not SizeBasedTriggeringPolicy.setMaxFileSize(String)
Earlier versions like logback-core-1.0.7 had SizeBasedTriggeringPolicy.setMaxFileSize(String) method.

I checked dropwizard-logging jars and found that starting from dropwizard-logging-1.1.0.jar release they have included call to SizeBasedTriggeringPolicy.setMaxFileSize(FileSize).
So reaper needs to be updated to dropwizard-logging version to 1.1.0 or later.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-309) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-309

**Comment by Ritu-Thakur** [comment]
@adejanovski is there any schedule to resolve this issue?

**Comment by michaelsembwever** [comment]
could be addressed via https://github.com/thelastpickle/cassandra-reaper/pull/259 as it rotates logfiles (which is not explicitly setting a max size but may still solve many users problems)

**Comment by michaelsembwever** [comment]
@gundy1ab @ritu0407 should be addressed by https://github.com/thelastpickle/cassandra-reaper/pull/434
