### ISSUE TITLE
Possible to create duplicate RepairRuns (which are not started) within the same RepairUnit

### ISSUE THREAD

**Issue by michaelsembwever** [thelastpickle/cassandra-reaper#266]
Currently it is possible to create multiple (and duplicate) repair runs within the same RepairUnit.

Is this something we want to be possible?

The following test failure (see below) demonstrates this.
A call to `POST /repair_run?owner=test_user&keyspace=booya&clusterName=test&blacklistedTables=booya` happens twice, and both requests create new repair runs.
This test fails because it then expects only one repair run to have been created. (Because the jersey client can send off speculative duplicate requests under the cover, and expects the REST interface to be idempotent.)

While the test can be fixed to only check and assert that there is one repair running: therefore just ignoring the duplicate created repair run (that never gets restarted); the REST resource `RepairRunResource` should identify duplicate NOT_STARTED repair runs and return `409 Conflict`.

```

127.0.0.1 - - [02/Nov/2017:22:17:40 +0000] "GET /cluster/test HTTP/1.1" 404 34 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 3
127.0.0.1 - - [02/Nov/2017:22:17:40 +0000] "GET /cluster/test HTTP/1.1" 404 34 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 3
127.0.0.1 - - [02/Nov/2017:22:17:47 +0000] "GET /cluster/ HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 5
127.0.0.1 - - [02/Nov/2017:22:17:47 +0000] "GET /cluster/ HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 7
127.0.0.1 - - [02/Nov/2017:22:17:47 +0000] "POST /cluster?seedHost=127.0.0.1 HTTP/1.1" 403 29 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 60
127.0.0.1 - - [02/Nov/2017:22:17:47 +0000] "POST /cluster?seedHost=127.0.0.1 HTTP/1.1" 201 661 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 231
127.0.0.1 - - [02/Nov/2017:22:17:47 +0000] "GET /cluster/test HTTP/1.1" 200 676 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 95
127.0.0.1 - - [02/Nov/2017:22:17:47 +0000] "GET /cluster/test HTTP/1.1" 200 676 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 108
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "GET /cluster/test HTTP/1.1" 200 661 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 124
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "GET /cluster/test HTTP/1.1" 200 661 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 153
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "GET /repair_run/cluster/test HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 5
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "GET /repair_run/cluster/test HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 3
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "POST /repair_run?owner=test_user&keyspace=booya&clusterName=test&blacklistedTables=booya2 HTTP/1.1" 201 542 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 268
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "POST /repair_run?owner=test_user&keyspace=booya&clusterName=test&blacklistedTables=booya2 HTTP/1.1" 201 542 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 276
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "GET /repair_run/cluster/test HTTP/1.1" 200 1209 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 33
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "GET /repair_run/cluster/test HTTP/1.1" 200 1209 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 21
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "DELETE /cluster/test HTTP/1.1" 403 65 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 6
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "DELETE /cluster/test HTTP/1.1" 403 65 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 10
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "PUT /repair_run/a8b0d2a0-c01b-11e7-a7f9-49a58b4bdc58?state=RUNNING HTTP/1.1" 200 599 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 89
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "PUT /repair_run/a8b0d2a0-c01b-11e7-a7f9-49a58b4bdc58?state=RUNNING HTTP/1.1" 200 599 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 108
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "PUT /repair_run/a8b0d2a0-c01b-11e7-a7f9-49a58b4bdc58?state=RUNNING HTTP/1.1" 304 46 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 15
127.0.0.1 - - [02/Nov/2017:22:17:48 +0000] "PUT /repair_run/a8b0d2a0-c01b-11e7-a7f9-49a58b4bdc58?state=RUNNING HTTP/1.1" 304 46 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 11
WARN  [2017-11-02 22:17:49,780] io.cassandrareaper.service.RepairRunner: RepairRun "9779c780-c01b-11e7-a7f9-49a58b4bdc58" does not exist. Killing RepairRunner for this run instance.
WARN  [2017-11-02 22:17:51,235] io.cassandrareaper.service.RepairRunner: RepairRun "9779c780-c01b-11e7-a7f9-49a58b4bdc58" does not exist. Killing RepairRunner for this run instance.
127.0.0.1 - - [02/Nov/2017:22:17:58 +0000] "GET /repair_run/a8b0d2a0-c01b-11e7-a7f9-49a58b4bdc58 HTTP/1.1" 200 691 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 15
127.0.0.1 - - [02/Nov/2017:22:17:58 +0000] "GET /repair_run/a8b0d2a0-c01b-11e7-a7f9-49a58b4bdc58 HTTP/1.1" 200 691 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 14
127.0.0.1 - - [02/Nov/2017:22:17:59 +0000] "GET /repair_run/cluster/test HTTP/1.1" 200 1297 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 30
127.0.0.1 - - [02/Nov/2017:22:17:59 +0000] "GET /repair_run/cluster/test HTTP/1.1" 200 1297 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 46
127.0.0.1 - - [02/Nov/2017:22:18:06 +0000] "GET /cluster/ HTTP/1.1" 200 8 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 9
127.0.0.1 - - [02/Nov/2017:22:18:06 +0000] "GET /cluster/ HTTP/1.1" 200 8 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_144)" 4
Failed scenarios:
io.cassandrareaper.acceptance/integration_reaper_functionality.feature:50 # Scenario: Create a cluster and a repair run and delete them
io.cassandrareaper.acceptance/integration_reaper_functionality.feature:67 # Scenario: Create a cluster and an incremental repair run and delete them
5 Scenarios (2 failed, 3 passed)
72 Steps (2 failed, 15 skipped, 55 passed)
1m44.816s
java.lang.AssertionError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at io.cassandrareaper.acceptance.BasicSteps.reaper_has_repairs_for_the_last_added_cluster(BasicSteps.java:933)
	at ✽.Then reaper has 1 repairs for the last added cluster(io.cassandrareaper.acceptance/integration_reaper_functionality.feature:61)
Caused by: java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at io.cassandrareaper.acceptance.BasicSteps.lambda$reaper_has_repairs_for_the_last_added_cluster$23(BasicSteps.java:938)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at io.cassandrareaper.acceptance.BasicSteps.lambda$reaper_has_no_cluster_in_storage$3(BasicSteps.java:270)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at io.cassandrareaper.acceptance.BasicSteps.reaper_has_no_cluster_in_storage(BasicSteps.java:265)
	at ✽.And reaper has no cluster in storage(io.cassandrareaper.acceptance/integration_reaper_functionality.feature:69)
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-316) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-316

**Comment by adejanovski** [comment]
I think we should indeed prevent creating another repair run on the same unit as a repair run that is in a non final state.

**Comment by adejanovski** [comment]
This had been handled correctly for a while now.
Closing the issue.
