### ISSUE TITLE
 SegmentRunner already exists for segment with ID

### ISSUE THREAD

**Issue by agoetz00** [thelastpickle/cassandra-reaper#277]
We recently upgraded our lab environment to reaper-1.0.0_RC1.  Since the upgrade we have noticed that the repairs stall after processing a couple of segments.  We are seeing the below error then reaper stops processing segments and the logs fill up with RepairRunner messages.

Logs:

ERROR  [2017-11-09 03:11:22,862] [dovecot-qa_openstack:00000000-0000-0038-0000-000000000000] i.c.s.SegmentRunner - SegmentRunner already exists for segment with ID: 00000000-0002-99d8-0000-000000000000 
ERROR  [2017-11-09 03:11:22,863] [dovecot-qa_openstack:00000000-0000-0038-0000-000000000000] i.c.s.RepairRunner - Executing SegmentRunner failed 
io.cassandrareaper.ReaperException: SegmentRunner already exists for segment with ID: 00000000-0002-99d8-0000-000000000000
	at io.cassandrareaper.service.SegmentRunner.<init>(SegmentRunner.java:114)
	at io.cassandrareaper.service.RepairRunner.repairSegment(RepairRunner.java:390)
	at io.cassandrareaper.service.RepairRunner.startNextSegment(RepairRunner.java:290)
	at io.cassandrareaper.service.RepairRunner.run(RepairRunner.java:171)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
DEBUG  [2017-11-09 03:11:22,864] [dovecot-qa_openstack:00000000-0000-0038-0000-000000000000] i.c.s.RepairRunner - run() exiting for repair run #00000000-0000-0038-0000-000000000000 
DEBUG  [2017-11-09 03:11:24,111] [dw-94 - GET /ping] i.c.r.ClusterResource - ping called 
DEBUG  [2017-11-09 03:11:24,111] [dw-89 - GET /cluster] i.c.r.ClusterResource - get cluster list called 
DEBUG  [2017-11-09 03:11:24,176] [dw-416 - GET /cluster] i.c.r.ClusterResource - get cluster list called 
DEBUG  [2017-11-09 03:11:26,110] [dw-88 - GET /ping] i.c.r.ClusterResource - ping called 
DEBUG  [2017-11-09 03:11:26,110] [dw-367 - GET /cluster] i.c.r.ClusterResource - get cluster list called 
DEBUG  [2017-11-09 03:11:26,166] [dw-94 - GET /cluster] i.c.r.ClusterResource - get cluster list called 
DEBUG  [2017-11-09 03:11:27,184] [dovecot-qa_openstack:00000000-0000-0039-0000-000000000000] i.c.s.RepairRunner - run() called for repair run #00000000-0000-0039-0000-000000000000 with run state RUNNING 
DEBUG  [2017-11-09 03:11:27,304] [dovecot-qa_openstack:00000000-0000-0039-0000-000000000000] i.c.s.RepairRunner - run() exiting for repair run #00000000-0000-0039-0000-000000000000 
DEBUG  [2017-11-09 03:11:27,864] [dovecot-qa_openstack:00000000-0000-0038-0000-000000000000] i.c.s.RepairRunner - run() called for repair run #00000000-0000-0038-0000-000000000000 with run state RUNNING 
DEBUG  [2017-11-09 03:11:27,972] [dovecot-qa_openstack:00000000-0000-0038-0000-000000000000] i.c.s.RepairRunner - run() exiting for repair run #00000000-0000-0038-0000-000000000000 
DEBUG  [2017-11-09 03:11:28,101] [dw-416 - GET /ping] i.c.r.ClusterResource - ping called

**Comment by powellchristoph** [comment]
I am running into the same issue. Very basic 3 node QA cluster with really nothing on it. Repairs start and the slowly just hang.

`SegmentRunner already exists for segment with ID: 7d9cafd6-cdfd-11e7-8039-27532fbb6f9f`

https://gist.github.com/powellchristoph/c9294a54c5c578d7d05915f3f47964d2

Cassandra: 2.1.14
OS: Ubuntu 14.04.3 LTS
Java: 1.8.0_65
Reaper: 1.0.0

**Comment by adejanovski** [comment]
@agoetz00 @powellchristoph : thanks for opening the issue.

There should be some other errors in the logs that could help us analyze the issue. Any chance you could send us the full logs at reaper@thelastpickle.com ?

Thanks !

**Comment by agoetz00** [comment]
I deployed the latest release (1.0.1-SNAPSHOT) and so far I am not seeing this issue.

**Comment by adejanovski** [comment]
Thanks for the feedback @agoetz00.

I'll close the ticket, and feel free to re-open if the issue pops up again.
