### ISSUE TITLE
Unobvious stacktrace in case of missing configuration parameter

### ISSUE THREAD

**Issue by cazorla19** [thelastpickle/cassandra-reaper#288]
I tried to install the reaper with custom configuration. I've read this and faced with [the folowing message](http://cassandra-reaper.io/docs/configuration/reaper_specific/) about the `segmentCount` parameter.

> WARNING this setting is DEPRECATED and its usage should be avoided.

So, I removed this parameter in configuration and tried to run reaper but got the error with the following stacktrace.

```
Exception in thread "main" java.lang.NullPointerException
        at io.cassandrareaper.ReaperApplicationConfiguration.getSegmentCount(ReaperApplicationConfiguration.java:115)
        at io.cassandrareaper.ReaperApplication.checkConfiguration(ReaperApplication.java:257)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:116)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:67)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:75)
        at io.dropwizard.Application.run(Application.java:79)
        at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:87)
```

So, I haven't figured out immediately trying to make the issue in log parsing (for example, count int as string and so on). What I want to say is that this error handling doesn't look clear and I'd be happy if you will agree with me to catch this exception with message like:

> Error! Required parameter `param` is not set! Please, check your configuration.

And also make the docs more straightforward, because from the first view it looks like "the next update will break your app because of deprecated configuration parameter and you would be better to erase it".

Thanks for attention!

**Comment by eslng** [comment]
have exactly same issue. Also `segmentCountPerNode` doesn't seem to affect anything

**Comment by adejanovski** [comment]
Indeed, `segmentCount` being deprecated, it should be ok to remove it from the config file.

I just ninja-fixed it in master.

@eslng : `segmentCountPerNode` is used as a default if it's not overriden at runtime for each repair job.
Currently it's mistakenly overriden by the number of token ranges per node which creates more segments than we would want it to.
It's been fixed in master though and will be part of the 1.1.0 release.
