### ISSUE TITLE
PostgreSQL driver (9.3-1100-jdbc41) does not support server version 10.2

### ISSUE THREAD

**Issue by zdenekott** [thelastpickle/cassandra-reaper#347]
**Spotted on 1.0.1-SNAPSHOT (cbad80e)**

ERROR  [2018-02-16 10:27:54,541] [dw-5443 - POST /repair_schedule?clusterName=business_console-test&keyspace=bc_av_management_dev&owner=puppet&scheduleDaysBetween=30&segmentCount=200&repairParallelism=PARALLE
L&intensity=0.9&scheduleDaysBetween=30] i.d.j.e.LoggingExceptionMapper - Error handling a request: aaae1b07ad671c76
org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: org.postgresql.util.PSQLException: Returning autogenerated keys is only supported for 8.2 and later servers. [statement:"INSERT INTO repair_unit
(cluster_name, keyspace_name, column_families, incremental_repair, nodes, datacenters, blacklisted_tables) VALUES (:clusterName, :keyspaceName, :columnFamilies, :incrementalRepair, :nodes, :datacenters, :blac
klistedTables)", located:"INSERT INTO repair_unit (cluster_name, keyspace_name, column_families, incremental_repair, nodes, datacenters, blacklisted_tables) VALUES (:clusterName, :keyspaceName, :columnFamilie
s, :incrementalRepair, :nodes, :datacenters, :blacklistedTables)", rewritten:"/* IStoragePostgreSql.insertRepairUnit */ INSERT INTO repair_unit (cluster_name, keyspace_name, column_families, incremental_repai
r, nodes, datacenters, blacklisted_tables) VALUES (?, ?, ?, ?, ?, ?, ?)", arguments:{ positional:{}, named:{datacenters:io.cassandrareaper.storage.postgresql.PostgresArrayArgumentFactory$$Lambda$67/248534864@
3e6b5a1,keyspaceName:'bc_av_management_dev',nodes:io.cassandrareaper.storage.postgresql.PostgresArrayArgumentFactory$$Lambda$67/248534864@3edb9555,clusterName:'business_console-test',columnFamilies:io.cassand
rareaper.storage.postgresql.PostgresArrayArgumentFactory$$Lambda$67/248534864@293d0089,id:null,blacklistedTables:io.cassandrareaper.storage.postgresql.PostgresArrayArgumentFactory$$Lambda$67/24853486410c9bbb
e,incrementalRepair:false,class:class io.cassandrareaper.core.RepairUnit}, finder:[]}]
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1307)
        at org.skife.jdbi.v2.Update.executeAndReturnGeneratedKeys(Update.java:82)
        at org.skife.jdbi.v2.sqlobject.UpdateHandler$1.value(UpdateHandler.java:57)
        at org.skife.jdbi.v2.sqlobject.UpdateHandler.invoke(UpdateHandler.java:81)
        at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:212)
        at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:127)
        at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$8547864e.insertRepairUnit(<generated>)
        at io.cassandrareaper.storage.PostgresStorage.addRepairUnit(PostgresStorage.java:261)
        at io.cassandrareaper.service.RepairUnitService.getNewOrExistingRepairUnit(RepairUnitService.java:107)
        at io.cassandrareaper.resources.RepairScheduleResource.addRepairSchedule(RepairScheduleResource.java:186)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
        at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:50)
        at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:44)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308)
        at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:262)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240)
        at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:396)
        at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: Returning autogenerated keys is only supported for 8.2 and later servers.
        at org.postgresql.jdbc3.AbstractJdbc3Statement.addReturning(AbstractJdbc3Statement.java:151)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.prepareStatement(AbstractJdbc3Connection.java:362)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
        at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
        at com.sun.proxy.$Proxy35.prepareStatement(Unknown Source)
        at org.skife.jdbi.v2.DefaultStatementBuilder.create(DefaultStatementBuilder.java:48)
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1303)
        ... 69 common frames omitted

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-342) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-342

**Comment by adejanovski** [comment]
Postgres support was removed in 3.0.
