### ISSUE TITLE
Exception on run of scheduled job 

### ISSUE THREAD

**Issue by zdenekott** [thelastpickle/cassandra-reaper#348]
**Spotted on 1.1.0-SNAPSHOT (00a3fd0)**

ERROR  [2018-02-21 12:50:23,086] [SchedulingManagerTimer] i.c.s.SchedulingManager - failed managing schedule for run with id: 00000000-0000-0015-0000-000000000000
ERROR  [2018-02-21 12:50:23,086] [SchedulingManagerTimer] i.c.s.SchedulingManager - catch exception
java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at io.cassandrareaper.service.SchedulingManager.equal(SchedulingManager.java:209)
        at io.cassandrareaper.service.SchedulingManager.manageSchedule(SchedulingManager.java:159)
        at io.cassandrareaper.service.SchedulingManager.run(SchedulingManager.java:97)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

psql (PostgreSQL) 10.2

PostgreSQL JDBC driver version: 42.2.1

SchedulingManager.java:209: 
   Preconditions.checkArgument(s1.getIntensity() == s2.getIntensity());

In my case s1.getIntensity() sometimes has value 0.8999999761581421 and s2.getIntensity() has value 0.899999976 . In db in repair_schedule table is value 0.9 .

I'm not sure if it's correct to compare doubles this way. I think it is better to use something like this:
   Preconditions.checkArgument(Math.abs(s1.getIntensity()-s2.getIntensity())<0.001);

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-343) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-343

**Comment by adejanovski** [comment]
Postgres support was removed in 3.0
