### ISSUE TITLE
Cassandra on Kubernetes and unreachable JMX connexion

### ISSUE THREAD

**Issue by deimosfr** [thelastpickle/cassandra-reaper#429]
Hi,

I'm using Cassandra on Kubernetes and recently added Cassandra Reaper. At first try, it works like a charm. However, when I perform a rolling restart, I completely loss Cassandra Reaper because there is no update on JMX address. Here are some logs:

```
Caused by: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 10.233.121.150:7199
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:268)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:176)
	at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:195)
	... 64 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at io.cassandrareaper.jmx.JmxProxyImpl.connectWithTimeout(JmxProxyImpl.java:286)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:233)
	... 66 common frames omitted
INFO   [2018-05-30 05:49:27,985] [dw-1646 - GET /cluster/mysocialapp/tables] i.c.j.JmxConnectionFactory - Unreachable host: Failure when establishing JMX connection to 10.233.121.150:7199: null 
ERROR  [2018-05-30 05:49:28,781] [dw-1539 - GET /cluster/observability/tables] i.c.j.JmxConnectionFactory - Failed creating a new JMX connection to 10.233.68.22
```

From the documentation (http://cassandra-reaper.io/docs/configuration/docker_vars/), I saw REAPER_USE_ADDRESS_TRANSLATOR which may fix same kind of issue issue (as far as I understood) but it looks like EC2 specific.

Is there any way for Cassandra Reaper to handle IP changes in a Cassandra cluster?

Thanks

**Comment by deimosfr** [comment]
Thanks for your quick reply @adejanovski.

All IP of a clusters can change in a few min. So yes no old IP will remain. I'll use the API as you suggested to fix my problem.

Thanks
