### ISSUE TITLE
Reaper Not working on Apache Cassandra - 

### ISSUE THREAD

**Issue by kptnew3** [thelastpickle/cassandra-reaper#432]
**Spotted on 1.1.0 (03ce27f)**
Hi - After trying for so long the reaper refused to work. Here is the error from cassandra-reaper.log file. Your help would be greatly appreciated. 
---------------------------------------------------
  ERROR  [2018-05-31 10:08:34,040] [pool-8-thread-2] i.c.j.JmxConnectionFactory - Failed creating a new JMX connection to 234.56.78.99
java.lang.RuntimeException: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 234.56.78.99:7199
        at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:201)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at io.cassandrareaper.jmx.JmxConnectionFactory.connect(JmxConnectionFactory.java:91)
        at io.cassandrareaper.jmx.JmxConnectionFactory.connect(JmxConnectionFactory.java:113)
        at io.cassandrareaper.service.SegmentRunner.lambda$getNodeMetrics$3(SegmentRunner.java:579)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 234.56.78.99:7199
        at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:268)
        at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:176)
        at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:195)
        ... 8 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is:
        java.net.ConnectException: Connection refused
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at io.cassandrareaper.jmx.JmxProxyImpl.connectWithTimeout(JmxProxyImpl.java:286)
        at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:233)
        ... 10 common frames omitted
Caused by: java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is:
        java.net.ConnectException: Connection refused
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:130)
        at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(Unknown Source)
        at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at io.cassandrareaper.jmx.JmxProxyImpl.lambda$connectWithTimeout$0(JmxProxyImpl.java:285)
        ... 4 common frames omitted
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
        at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
        ... 12 common frames omitted
INFO   [2018-05-31 10:08:34,040] [testcluster:a8dd6060-64ec-11e8-a0e2-6f7da1d2f428:a8dd6061-64ec-11e8-a0e2-6f7da1d2f428] i.c.s.SegmentRunner - Not ok to repair segment 'a8dd6061-64ec-11e8-a0e2-6f7da1d2f428' on repair run with id 'a8dd6060-64ec-11e8-a0e2-6f7da1d2f428' because we couldn't get all hosts metrics :'(
INFO   [2018-05-31 10:08:34,040] [testcluster:a8dd6060-64ec-11e8-a0e2-6f7da1d2f428:a8dd6061-64ec-11e8-a0e2-6f7da1d2f428] i.c.s.SegmentRunner - Cannot run segment a8dd6061-64ec-11e8-a0e2-6f7da1d2f428 for repair a8dd6060-64ec-11e8-a0e2-6f7da1d2f428 at the moment. Will try again later

**Comment by adejanovski** [comment]
Hi, 

by default Cassandra restricts JMX access to localhost, so you can't connect to it from a remote server.
Please adjust your `cassandra-env.sh` settings and/or firewall settings so that JMX is accessible from outside the Cassandra nodes.
Check the documentation if you're setting up Reaper in a multi region Cassandra cluster : http://cassandra-reaper.io/docs/usage/multi_dc/

**Comment by amorton** [comment]
@kptnew3 thanks for the report, we are closing as no updates, pls re-open if you have a reproduction case.

**Comment by kptnew3** [comment]
Hi,

I am sorry for the late reply. Your solution worked. I enabled the remote
jmx authentication and it worked.

Thanks a lot!

Regards,
Gagan
