### ISSUE TITLE
Does Cassandra-Reaper Web UI Support Active Directory Services Authentication?

### ISSUE THREAD

**Issue by kptnew3** [thelastpickle/cassandra-reaper#443]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13937815)

**Spotted on 1.2.0-BETA-20180607 (21edbeb)**
Hello Reaper Team,

Can you please let me know if Cassandra-Reaper Web UI Support Active Directory Services Authentication? I am able to use the file authentication on Beta version however not able to find documentation for ADS authentication. Your help would be greatly appreciated. 

Thanks,
Gagan

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-170) by [Unito](https://www.unito.io)
┆Issue Number: REAP-170

**Comment by a-boynton** [comment]
+1

**Comment by adejanovski** [comment]
If it's compatible with LDAP, yes, otherwise no.

**Comment by sb116** [comment]
@adejanovski  can you please share ldap settings for cassandra-reaper?
I have setup ldap, but I am not able to get it work

**Comment by adejanovski** [comment]
You can find an example of setting up ldap in shiro [here](https://github.com/jhegg/shiro-ad-ssl-example).

**Comment by sb116** [comment]
hi @adejanovski I followed the steps mentioned in that link -- but I get an exception:

```
DEBUG  [dw-50 - POST /login] o.a.s.r.l.JndiLdapContextFactory - Initializing LDAP context using URL [ldaps://ldap-address:636] and principal [username] with pooling disabled
DEBUG  [Thread-19] j.e.security - X509Certificate: Alg:SHA256withRSA, <snip
....
TRACE  [dw-50 - POST /login] o.a.s.w.s.SimpleCookie - calculated path: /
DEBUG  [dw-50 - POST /login] o.a.s.w.s.SimpleCookie - Added HttpServletResponse Cookie [rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Thu, 18-May-2023 20:57:07 GMT; SameSite=lax]
TRACE  [dw-50 - POST /login] o.a.s.w.s.SimpleCookie - Removed 'rememberMe' cookie by setting maxAge=0
DEBUG  [dw-50 - POST /login] o.g.j.s.ServerRuntime$Responder - Starting mapping of the exception.
org.glassfish.jersey.server.internal.process.MappableException: org.apache.shiro.authc.IncorrectCredentialsException: Invalid credentials combination for user: username
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.mapTargetToRuntimeEx(AbstractJavaResourceMethodDispatcher.java:185)

Caused by: org.apache.shiro.authc.IncorrectCredentialsException: Invalid credentials combination for user: username
        at io.cassandrareaper.resources.auth.LoginResource.login(LoginResource.java:50)
..
INFO   [dw-50 - POST /login] i.c.r.a.ShiroExceptionMapper - Authentication failed
org.apache.shiro.authc.IncorrectCredentialsException: Invalid credentials combination for user: username

```

i can access ldap server/service account via ldapsearch utility
