### ISSUE TITLE
Unable to use pgbouncer as a connection pooling solution for cassandra-reaper -> postgres

### ISSUE THREAD

**Issue by nethisandeep** [thelastpickle/cassandra-reaper#464]
Hello,

Recently when i tried to use pgbouncer for pooing my connections from cassandra-reaper to postgresql it failed with below error. 

pool_mode used : transaction

```
Exception in thread "main" org.flywaydb.core.api.FlywayException: Unable to commit transaction
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:76)
        at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:136)
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:1002)
        at org.flywaydb.core.Flyway.access$100(Flyway.java:72)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:921)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
        at io.cassandrareaper.ReaperApplication.initDatabase(ReaperApplication.java:299)
        at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:244)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:140)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:67)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:75)
        at io.dropwizard.Application.run(Application.java:79)
        at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:87)
Caused by: org.postgresql.util.PSQLException: ERROR: prepared statement "S_1" already exists
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.executeTransactionCommand(AbstractJdbc2Connection.java:804)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.commit(AbstractJdbc2Connection.java:828)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:73)
        ... 16 more
```

It works fine with pool_mode: sessions but not seeing any benefit of using pgbouncer because it's still using same connections as direct connection to postgresql.

There can be some code changed/optimized to make cassandra-reaper to use pgbouncer to utilize pooling benefits? 

I have observed that some of the health check queries with connections are going into idle state without performing any operations.

Thanks

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-358) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-358

**Comment by nethisandeep** [comment]
We are currently on 1.0.2

**Comment by JacobJohansen** [comment]
adding '?prepareThreshold=0' to the end of the jdbc url should fix that

**Comment by adejanovski** [comment]
Postgres support was removed in 3.0.
