### ISSUE TITLE
Column "repair_thread_count" not found

### ISSUE THREAD

**Issue by rborer** [thelastpickle/cassandra-reaper#478]
Hi,

I just upgraded my reaper installation from 1.1.0 to 1.2.0, and now when I browse the clusters view I see a spinning wheel at the place of the nodes list:

<img width="311" alt="screen shot 2018-07-12 at 09 39 32" src="https://user-images.githubusercontent.com/361403/42619149-810439c4-85b7-11e8-840a-7e1ed5aad88b.png">

And I see the following SQL error in the logs:

```
ERROR  [2018-07-12 07:36:40,541] [dw-45 - GET /cluster/staging-cluster] i.d.j.e.LoggingExceptionMapper - Error handling a request: fdf21aeec807ed9c
org.skife.jdbi.v2.exceptions.ResultSetException: Exception thrown while attempting to traverse the result set [statement:"SELECT repair_run.id, repair_unit.cluster_name, keyspace_name, column_families
, nodes, datacenters, blacklisted_tables, (SELECT COUNT(case when state = 2 then 1 else null end) FROM repair_segment WHERE run_id = repair_run.id) AS segments_repaired, (SELECT COUNT(*) FROM repair_s
egment WHERE run_id = repair_run.id) AS segments_total, repair_run.state, repair_run.start_time, repair_run.end_time, cause, owner, last_event, creation_time, pause_time, intensity, repair_parallelism
, incremental_repair FROM repair_run JOIN repair_unit ON repair_unit_id = repair_unit.id WHERE repair_unit.cluster_name = :clusterName ORDER BY COALESCE(end_time, start_time) DESC, start_time DESC LIM
IT :limit", located:"SELECT repair_run.id, repair_unit.cluster_name, keyspace_name, column_families, nodes, datacenters, blacklisted_tables, (SELECT COUNT(case when state = 2 then 1 else null end) FRO
M repair_segment WHERE run_id = repair_run.id) AS segments_repaired, (SELECT COUNT(*) FROM repair_segment WHERE run_id = repair_run.id) AS segments_total, repair_run.state, repair_run.start_time, repa
ir_run.end_time, cause, owner, last_event, creation_time, pause_time, intensity, repair_parallelism, incremental_repair FROM repair_run JOIN repair_unit ON repair_unit_id = repair_unit.id WHERE repair
_unit.cluster_name = :clusterName ORDER BY COALESCE(end_time, start_time) DESC, start_time DESC LIMIT :limit", rewritten:"/* IStoragePostgreSql.getClusterRunOverview */ SELECT repair_run.id, repair_un
it.cluster_name, keyspace_name, column_families, nodes, datacenters, blacklisted_tables, (SELECT COUNT(case when state = 2 then 1 else null end) FROM repair_segment WHERE run_id = repair_run.id) AS se
gments_repaired, (SELECT COUNT(*) FROM repair_segment WHERE run_id = repair_run.id) AS segments_total, repair_run.state, repair_run.start_time, repair_run.end_time, cause, owner, last_event, creation_
time, pause_time, intensity, repair_parallelism, incremental_repair FROM repair_run JOIN repair_unit ON repair_unit_id = repair_unit.id WHERE repair_unit.cluster_name = ? ORDER BY COALESCE(end_time, s
tart_time) DESC, start_time DESC LIMIT ?", arguments:{ positional:{}, named:{clusterName:'staging-cluster',limit:2147483647}, finder:[]}]
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1352)
        at org.skife.jdbi.v2.Query.fold(Query.java:173)
        at org.skife.jdbi.v2.Query.list(Query.java:82)
        at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:253)
        at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:43)
        at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:41)
        at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:224)
        at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:133)
        at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$a9489863.getClusterRunOverview(<generated>)
        at io.cassandrareaper.storage.PostgresStorage.getClusterRunStatuses(PostgresStorage.java:506)
        at io.cassandrareaper.resources.ClusterResource.getCluster(ClusterResource.java:117)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:50)
        at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:44)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308)
        at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:262)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:241)
        at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:521)
        at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:69)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Column "repair_thread_count" not found [42122-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3148)
        at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3247)
        at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:346)
        at io.cassandrareaper.storage.postgresql.RepairRunStatusMapper.map(RepairRunStatusMapper.java:75)
        at io.cassandrareaper.storage.postgresql.RepairRunStatusMapper.map(RepairRunStatusMapper.java:33)
        at org.skife.jdbi.v2.Query$4.munge(Query.java:183)
        at org.skife.jdbi.v2.QueryResultSetMunger.munge(QueryResultSetMunger.java:41)
        at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1344)
        ... 74 common frames omitted
```

I'm using an H2 database (I cannot use my C* cluster since it's running version 1.2.19), here is what I have within `cassandra-reaper.yaml`:

```
h2:
  url: jdbc:h2:/etc/cassandra-reaper/database/reaper-db;MODE=PostgreSQL
  user:
  password:
```

Here are also the Flyway DB migration logs:

```
INFO   [2018-07-12 07:36:06,762] [main] i.c.ReaperApplication - initializing storage of type: h2
INFO   [2018-07-12 07:36:06,813] [main] o.f.c.i.u.VersionPrinter - Flyway Community Edition 5.1.0 by Boxfuse
INFO   [2018-07-12 07:36:06,950] [main] o.f.c.i.d.DatabaseFactory - Database: jdbc:h2:/etc/cassandra-reaper/database/reaper-db (H2 1.4)
WARN   [2018-07-12 07:36:06,992] [main] o.f.c.i.s.JdbcTableSchemaHistory - Could not find schema history table "PUBLIC"."flyway_schema_history", but found "PUBLIC"."schema_version" instead. You are seeing this message because Flyway changed its default for flyway.table in version 5.0.0 to flyway_schema_history and you are still relying on the old default (schema_version). Set flyway.table=schema_version in your configuration to fix this. This fallback mechanism will be removed in Flyway 6.0.0.
INFO   [2018-07-12 07:36:07,047] [main] o.f.c.i.s.JdbcTableSchemaHistory - Repair of failed migration in Schema History table "PUBLIC"."schema_version" not necessary. No failed migration detected.
INFO   [2018-07-12 07:36:07,058] [main] o.f.c.i.s.JdbcTableSchemaHistory - Repairing Schema History table for version 1.0.1 (Description: Initial reaper h2 db, Type: SQL, Checksum: -1235440596)  ...
INFO   [2018-07-12 07:36:07,061] [main] o.f.c.i.s.JdbcTableSchemaHistory - Repairing Schema History table for version 2.0.0 (Description: specific nodes repair, Type: SQL, Checksum: -848215015)  ...
INFO   [2018-07-12 07:36:07,061] [main] o.f.c.i.s.JdbcTableSchemaHistory - Repairing Schema History table for version 3.0.0 (Description: table blacklist, Type: SQL, Checksum: -750397564)  ...
INFO   [2018-07-12 07:36:07,062] [main] o.f.c.i.c.DbRepair - Successfully repaired schema history table "PUBLIC"."schema_version" (execution time 00:00.028s).
INFO   [2018-07-12 07:36:07,062] [main] o.f.c.i.c.DbRepair - Manual cleanup of the remaining effects the failed migration may still be required.
WARN   [2018-07-12 07:36:07,085] [main] o.f.c.i.s.JdbcTableSchemaHistory - Could not find schema history table "PUBLIC"."flyway_schema_history", but found "PUBLIC"."schema_version" instead. You are seeing this message because Flyway changed its default for flyway.table in version 5.0.0 to flyway_schema_history and you are still relying on the old default (schema_version). Set flyway.table=schema_version in your configuration to fix this. This fallback mechanism will be removed in Flyway 6.0.0.
INFO   [2018-07-12 07:36:07,116] [main] o.f.c.i.c.DbValidate - Successfully validated 8 migrations (execution time 00:00.007s)
INFO   [2018-07-12 07:36:07,131] [main] o.f.c.i.c.DbMigrate - Current version of schema "PUBLIC": 5.0.0
INFO   [2018-07-12 07:36:07,134] [main] o.f.c.i.c.DbMigrate - Migrating schema "PUBLIC" to version 6.0.0 - snapshots
INFO   [2018-07-12 07:36:07,148] [main] o.f.c.i.c.DbMigrate - Migrating schema "PUBLIC" to version 7.0.0 - coalesce segments
INFO   [2018-07-12 07:36:07,288] [main] o.f.c.i.c.DbMigrate - Migrating schema "PUBLIC" to version 8.0.0 - multithreaded repair
INFO   [2018-07-12 07:36:07,305] [main] o.f.c.i.c.DbMigrate - Successfully applied 3 migrations to schema "PUBLIC" (execution time 00:00.183s)
```

**Comment by michaelsembwever** [comment]
I can confirm this. I had to fix it in https://github.com/thelastpickle/cassandra-reaper/commit/a2403d8b54b595e2f91d84b12ee47ecc99a637e3#diff-3930e080258f9f71346284f4e5f0c937R214

Was broken by https://github.com/thelastpickle/cassandra-reaper/commit/a53c1f160e00720604ef97d3698ec6a8bd112ab4

**Comment by rborer** [comment]
Thanks!

Any plan to cut a new release with this fix?

Cheers,
Reynald

**Comment by adejanovski** [comment]
yes, I'm working on it @rborer :)

**Comment by rborer** [comment]
Awesome, I just installed 1.2.1 and I can confirm the issue is fixed. Thanks a lot!
