### ISSUE TITLE
Nodes references after decommission is not getting refreshed accordingly in the backend (postgres).

### ISSUE THREAD

**Issue by nethisandeep** [thelastpickle/cassandra-reaper#490]
On version 1.1:

We have observed that backend storage for cassandra-reaper is not removing decommissioned node references from cluster table and causing repair sessions to fail with following error.

INFO   [2018-07-19 18:45:54,063] [CLUSTER_NAME:00000000-0000-00ae-0000-000000000000:00000000-0003-fef7-0000-000000000000] i.c.s.SegmentRunner - Repair for segment 00000000-0003-fef7-0000-000000000000 started, status wait will timeout in 1800000 millis 
ERROR  [2018-07-19 18:45:54,163] [SchedulingManagerTimer] i.c.s.SchedulingManager - failed managing schedule for run with id: 00000000-0000-0009-0000-000000000000 
ERROR  [2018-07-19 18:45:54,167] [SchedulingManagerTimer] i.c.s.SchedulingManager - catch exception 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:657)
    at java.util.ArrayList.get(ArrayList.java:433)
    at io.cassandrareaper.service.RepairRunService.getClusterNodes(RepairRunService.java:316)
    at io.cassandrareaper.service.RepairRunService.registerRepairRun(RepairRunService.java:97)
    at io.cassandrareaper.service.SchedulingManager.createNewRunForUnit(SchedulingManager.java:247)
    at io.cassandrareaper.service.SchedulingManager.manageSchedule(SchedulingManager.java:152)
    at io.cassandrareaper.service.SchedulingManager.run(SchedulingManager.java:97)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
ERROR  [2018-07-19 18:45:54,167] [SchedulingManagerTimer] i.c.s.SchedulingManager - SchedulingManager failed. Exiting JVM.  

Is there a way to update cluster (ring) information in cluster table without actually recreating from scratch?

It would be great if we can have a feature to auto update peers information in clusters table automatically.

Thanks

**Comment by adejanovski** [comment]
Hi @nethisandeep,

This has been implemented in 1.2 with this commit : https://github.com/thelastpickle/cassandra-reaper/commit/65984ae6ca091507947a8f6bec27b8bda2429ba2

I recommend an upgrade to fix your issue.
