### ISSUE TITLE
Stream tracking doesn't seem to work with the latest trunk

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#542]
The streaming API has been re-worked in 4.0 and our implementation of stream tracking breaks : 

```
ERROR  [2018-08-30 16:49:01,596] [dw-45 - GET /node/streams/inc-repair-4.0/127.0.0.1] i.d.j.e.LoggingExceptionMapper - Error handling a request: 6df9651f09dbd006 
javax.management.openmbean.InvalidKeyException: Argument key="cfId" is not an existing item name for this CompositeData instance.
	at javax.management.openmbean.CompositeDataSupport.get(CompositeDataSupport.java:269)
	at javax.management.openmbean.CompositeDataSupport.getAll(CompositeDataSupport.java:291)
	at org.apache.cassandra.streaming.management.StreamSummaryCompositeData.fromCompositeData(StreamSummaryCompositeData.java:77)
	at org.apache.cassandra.streaming.management.SessionInfoCompositeData$3.apply(SessionInfoCompositeData.java:137)
	at org.apache.cassandra.streaming.management.SessionInfoCompositeData$3.apply(SessionInfoCompositeData.java:134)
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.Iterators.addAll(Iterators.java:367)
	at com.google.common.collect.Lists.newArrayList(Lists.java:163)
	at com.google.common.collect.Lists.newArrayList(Lists.java:146)
```

**Comment by adejanovski** [comment]
Fixed in `master`
