### ISSUE TITLE
Ec2MultiRegionAddressTranslator not working

### ISSUE THREAD

**Issue by mattheworiordan** [thelastpickle/cassandra-reaper#564]
### Reaper details

Cassandra: 2.2
Reaper: 1.2.2 (using Cassandra backend for storage)
Environment: EC2 (VPC), with Reaper & Cassandra running in Docker containers

### Problem

We run Cassandra in three datacenters. Cross-region, there is no default Native RPC communication, however we have some routers that TLS terminate connections and use client-certificate authentication.  However, within each region, port 9042 is unencrypted and only restricted by basic auth / plain text authentication.

We have just set up a Reaper container running on a new instance in one of our dev regions, and we seed it with the private IP addresses of all the Cassandra nodes in that region, such as:

```
"REAPER_CASS_CONTACT_POINTS=[\"10.10.109.9\", \"10.10.45.18\", \"10.10.19.157\"]",
```

When the Reaper starts up, it correctly connects to one of the seeds and proceeds to get the `system.peers` info, using the Datastax driver.  However, immediately after it detects the public RPC addresses for the Cassandra instances, which are in fact not publicly accessible.  See below:

```
INFO   [2018-09-25 00:34:26,250] [main] o.e.j.u.log - Logging initialized @1920ms to org.eclipse.jetty.util.log.Slf4jLog
INFO   [2018-09-25 00:34:26,469] [main] i.d.s.DefaultServerFactory - Registering jersey handler with root path prefix: /
INFO   [2018-09-25 00:34:26,471] [main] i.d.s.DefaultServerFactory - Registering admin handler with root path prefix: /
INFO   [2018-09-25 00:34:26,471] [main] i.d.a.AssetsBundle - Registering AssetBundle with name: assets for path /webui/*
INFO   [2018-09-25 00:34:26,538] [main] i.c.ReaperApplication - initializing runner thread pool with 15 threads
INFO   [2018-09-25 00:34:26,553] [main] i.c.ReaperApplication - initializing storage of type: cassandra
INFO   [2018-09-25 00:34:26,567] [main] c.d.d.core - DataStax Java driver 3.5.0 for Apache Cassandra
INFO   [2018-09-25 00:34:26,570] [main] c.d.d.c.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
INFO   [2018-09-25 00:34:26,809] [main] c.d.d.c.ClockFactory - Using native clock to generate timestamps.
INFO   [2018-09-25 00:34:26,978] [main] c.d.d.c.NettyUtil - Found Netty's native epoll transport in the classpath, using it
WARN   [2018-09-25 00:34:27,199] [main] c.d.d.c.Cluster - You listed /10.10.19.157:9042 in your contact points, but it wasn't found in the control host's system.peers at startup
WARN   [2018-09-25 00:34:27,204] [main] c.d.d.c.Cluster - You listed /10.10.45.18:9042 in your contact points, but it wasn't found in the control host's system.peers at startup
INFO   [2018-09-25 00:34:27,511] [main] c.d.d.c.p.DCAwareRoundRobinPolicy - Using provided data-center name 'cassandra-eu-west-1-A' for DCAwareRoundRobinPolicy
INFO   [2018-09-25 00:34:27,512] [main] c.d.d.c.Cluster - New Cassandra host /10.10.109.9:9042 added
INFO   [2018-09-25 00:34:27,512] [main] c.d.d.c.Cluster - New Cassandra host /34.245.12.110:9042 added
INFO   [2018-09-25 00:34:27,512] [main] c.d.d.c.Cluster - New Cassandra host /54.194.179.214:9042 added
WARN   [2018-09-25 00:34:32,554] [Ably-nio-worker-0] c.d.d.c.HostConnectionPool - Error creating connection to /34.245.12.110:9042
com.datastax.driver.core.exceptions.TransportException: [/34.245.12.110:9042] Cannot connect
        at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:171)
        at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:154)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
```

Having [looked at a commit back in May 2017 where support for the Ec2MultiRegionAddressTranslator was added](https://github.com/thelastpickle/cassandra-reaper/pull/91/files), I assumed this would solve the problem.

However, after setting up the following env vars:

```
REAPER_CASS_LOCAL_DC=cassandra-eu-west-1-A # that's the data center used by Cassandra in this region
REAPER_DATACENTER_AVAILABILITY=LOCAL
REAPER_USE_ADDRESS_TRANSLATOR=true
```

I still get the same problem.  The Reaper continues to try and connect to public IPs for servers that are in the same region.

Peers table from one Cass node looks like:

```
 peer         | data_center           | host_id                              | preferred_ip | rack       | release_version | rpc_address    | schema_version
--------------+-----------------------+--------------------------------------+--------------+------------+-----------------+----------------+--------------------------------------
 10.10.19.157 | cassandra-eu-west-1-A | a8847e67-7b36-4eb3-b166-6487b79b3e73 |         null | eu-west-1c |          2.2.12 |  34.245.12.110 | 8b8e9eb6-9c82-3cf9-be98-34196c345ccd
  10.10.45.18 | cassandra-eu-west-1-A | c0f160f3-e9b4-4518-8262-24f527ac0826 |         null | eu-west-1c |          2.2.12 | 54.194.179.214 | 8b8e9eb6-9c82-3cf9-be98-34196c345ccd
```

And doing a  reverse DNS lookup on those IPs, it confirms the translator should be able to determine these IPs are the same and use the local JMX IPs.

```
ubuntu 01:16 / $ dig +noall +answer -x  34.245.12.110
110.12.245.34.in-addr.arpa. 60  IN      PTR     ec2-34-245-12-110.eu-west-1.compute.amazonaws.com.
ubuntu 01:16 / $ dig +noall +answer -x  54.194.179.214
214.179.194.54.in-addr.arpa. 60 IN      PTR     ec2-54-194-179-214.eu-west-1.compute.amazonaws.com.
```

I have also enabled verbose logging to see if I can identify where it's going wrong, but I am a bit stumped.  Detailed log below:

<details>

```
DEBUG  [2018-09-25 00:39:36,567] [main] o.e.j.u.log - Logging to Logger[org.eclipse.jetty.util.log] via org.eclipse.jetty.util.log.Slf4jLog 
INFO   [2018-09-25 00:39:36,573] [main] o.e.j.u.log - Logging initialized @1927ms to org.eclipse.jetty.util.log.Slf4jLog 
DEBUG  [2018-09-25 00:39:36,583] [main] o.e.j.u.DecoratedObjectFactory - Adding Decorator: org.eclipse.jetty.util.DeprecationWarning@7a389761 
DEBUG  [2018-09-25 00:39:36,588] [main] o.e.j.u.c.ContainerLifeCycle - i.d.j.MutableServletContextHandler@772861aa{/,null,UNAVAILABLE} added {org.eclipse.jetty.servlet.ServletHandler@6631cb64,MANAGED} 
DEBUG  [2018-09-25 00:39:36,590] [main] o.e.j.u.DecoratedObjectFactory - Adding Decorator: org.eclipse.jetty.util.DeprecationWarning@383864d5 
DEBUG  [2018-09-25 00:39:36,591] [main] o.e.j.u.c.ContainerLifeCycle - i.d.j.MutableServletContextHandler@3dd818e8{/,null,UNAVAILABLE} added {org.eclipse.jetty.servlet.ServletHandler@4cb40e3b,MANAGED} 
DEBUG  [2018-09-25 00:39:36,738] [main] o.e.j.u.c.ContainerLifeCycle - org.eclipse.jetty.servlet.ServletHandler@4cb40e3b added {tasks@6907b8e==io.dropwizard.servlets.tasks.TaskServlet,jsp=null,order=1,inst=true,AUTO} 
DEBUG  [2018-09-25 00:39:36,740] [main] o.e.j.u.c.ContainerLifeCycle - org.eclipse.jetty.servlet.ServletHandler@4cb40e3b added {[/tasks/*]=>tasks,POJO} 
INFO   [2018-09-25 00:39:36,796] [main] i.d.s.DefaultServerFactory - Registering jersey handler with root path prefix: / 
INFO   [2018-09-25 00:39:36,798] [main] i.d.s.DefaultServerFactory - Registering admin handler with root path prefix: / 
INFO   [2018-09-25 00:39:36,798] [main] i.d.a.AssetsBundle - Registering AssetBundle with name: assets for path /webui/* 
DEBUG  [2018-09-25 00:39:36,832] [main] o.e.j.u.c.ContainerLifeCycle - org.eclipse.jetty.servlet.ServletHandler@6631cb64 added {assets@ac107383==io.dropwizard.servlets.assets.AssetServlet,jsp=null,order=1,inst=true,AUTO} 
DEBUG  [2018-09-25 00:39:36,832] [main] o.e.j.u.c.ContainerLifeCycle - org.eclipse.jetty.servlet.ServletHandler@6631cb64 added {[/webui/*]=>assets,POJO} 
DEBUG  [2018-09-25 00:39:36,833] [main] i.c.ReaperApplication - repairIntensity: 0.9 
DEBUG  [2018-09-25 00:39:36,833] [main] i.c.ReaperApplication - incrementalRepair: false 
DEBUG  [2018-09-25 00:39:36,833] [main] i.c.ReaperApplication - repairRunThreadCount: 15 
DEBUG  [2018-09-25 00:39:36,834] [main] i.c.ReaperApplication - segmentCount: 200 
DEBUG  [2018-09-25 00:39:36,834] [main] i.c.ReaperApplication - repairParallelism: dc_parallel 
DEBUG  [2018-09-25 00:39:36,834] [main] i.c.ReaperApplication - hangingRepairTimeoutMins: 30 
DEBUG  [2018-09-25 00:39:36,835] [main] i.c.ReaperApplication - jmxPorts: {} 
DEBUG  [2018-09-25 00:39:36,835] [main] i.c.ReaperApplication - adding signal handler for SIGHUP 
DEBUG  [2018-09-25 00:39:36,840] [main] o.e.j.u.c.ContainerLifeCycle - org.eclipse.jetty.servlet.ServletHandler@4cb40e3b added {prometheusMetrics@5c89d479==io.prometheus.client.exporter.MetricsServlet,jsp=null,order=1,inst=true,AUTO} 
DEBUG  [2018-09-25 00:39:36,841] [main] o.e.j.u.c.ContainerLifeCycle - org.eclipse.jetty.servlet.ServletHandler@4cb40e3b added {[/prometheusMetrics]=>prometheusMetrics,POJO} 
INFO   [2018-09-25 00:39:36,871] [main] i.c.ReaperApplication - initializing runner thread pool with 15 threads 
INFO   [2018-09-25 00:39:36,884] [main] i.c.ReaperApplication - initializing storage of type: cassandra 
INFO   [2018-09-25 00:39:36,898] [main] c.d.d.core - DataStax Java driver 3.5.0 for Apache Cassandra 
INFO   [2018-09-25 00:39:36,901] [main] c.d.d.c.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer 
DEBUG  [2018-09-25 00:39:36,902] [main] c.d.d.c.SystemProperties - com.datastax.driver.NEW_NODE_DELAY_SECONDS is undefined, using default value 1 
DEBUG  [2018-09-25 00:39:36,902] [main] c.d.d.c.SystemProperties - com.datastax.driver.NOTIF_LOCK_TIMEOUT_SECONDS is undefined, using default value 60 
DEBUG  [2018-09-25 00:39:36,926] [main] c.d.d.c.SystemProperties - com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true 
INFO   [2018-09-25 00:39:37,140] [main] c.d.d.c.ClockFactory - Using native clock to generate timestamps. 
DEBUG  [2018-09-25 00:39:37,142] [main] c.d.d.c.SystemProperties - com.datastax.driver.NON_BLOCKING_EXECUTOR_SIZE is undefined, using default value 2 
DEBUG  [2018-09-25 00:39:37,179] [main] s.c.d.c.CassandraFactory - Registering MyBiz Cassandra health check 
DEBUG  [2018-09-25 00:39:37,179] [main] c.d.d.c.Cluster - Starting new cluster with contact points [/10.10.109.9:9042, /10.10.45.18:9042, /10.10.19.157:9042] 
DEBUG  [2018-09-25 00:39:37,196] [main] i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework 
DEBUG  [2018-09-25 00:39:37,213] [main] i.n.u.i.PlatformDependent - -Dio.netty.noUnsafe: false 
DEBUG  [2018-09-25 00:39:37,215] [main] i.n.u.i.PlatformDependent0 - java.nio.Buffer.address: available 
DEBUG  [2018-09-25 00:39:37,215] [main] i.n.u.i.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available 
DEBUG  [2018-09-25 00:39:37,215] [main] i.n.u.i.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available 
DEBUG  [2018-09-25 00:39:37,216] [main] i.n.u.i.PlatformDependent0 - direct buffer constructor: available 
DEBUG  [2018-09-25 00:39:37,216] [main] i.n.u.i.PlatformDependent0 - java.nio.Bits.unaligned: available, true 
DEBUG  [2018-09-25 00:39:37,216] [main] i.n.u.i.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available 
DEBUG  [2018-09-25 00:39:37,217] [main] i.n.u.i.Cleaner0 - java.nio.ByteBuffer.cleaner(): available 
DEBUG  [2018-09-25 00:39:37,217] [main] i.n.u.i.PlatformDependent - Java version: 8 
DEBUG  [2018-09-25 00:39:37,218] [main] i.n.u.i.PlatformDependent - sun.misc.Unsafe: available 
DEBUG  [2018-09-25 00:39:37,218] [main] i.n.u.i.PlatformDependent - -Dio.netty.noJavassist: false 
DEBUG  [2018-09-25 00:39:37,276] [main] i.n.u.i.PlatformDependent - Javassist: available 
DEBUG  [2018-09-25 00:39:37,276] [main] i.n.u.i.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir) 
DEBUG  [2018-09-25 00:39:37,276] [main] i.n.u.i.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model) 
DEBUG  [2018-09-25 00:39:37,276] [main] i.n.u.i.PlatformDependent - -Dio.netty.noPreferDirect: false 
DEBUG  [2018-09-25 00:39:37,276] [main] i.n.u.i.PlatformDependent - io.netty.maxDirectMemory: 452984832 bytes 
DEBUG  [2018-09-25 00:39:37,282] [main] c.d.d.c.SystemProperties - com.datastax.driver.FORCE_NIO is undefined, using default value false 
DEBUG  [2018-09-25 00:39:37,285] [main] i.n.u.i.NativeLibraryLoader - -Dio.netty.tmpdir: /tmp (java.io.tmpdir) 
DEBUG  [2018-09-25 00:39:37,285] [main] i.n.u.i.NativeLibraryLoader - -Dio.netty.native.workdir: /tmp (io.netty.tmpdir) 
DEBUG  [2018-09-25 00:39:37,295] [main] i.n.u.NetUtil - Loopback interface: lo (lo, 127.0.0.1) 
DEBUG  [2018-09-25 00:39:37,296] [main] i.n.u.NetUtil - /proc/sys/net/core/somaxconn: 128 
INFO   [2018-09-25 00:39:37,298] [main] c.d.d.c.NettyUtil - Found Netty's native epoll transport in the classpath, using it 
DEBUG  [2018-09-25 00:39:37,312] [main] i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4 
DEBUG  [2018-09-25 00:39:37,322] [main] i.n.u.i.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available 
DEBUG  [2018-09-25 00:39:37,330] [main] i.n.u.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple 
DEBUG  [2018-09-25 00:39:37,330] [main] i.n.u.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4 
DEBUG  [2018-09-25 00:39:37,330] [main] i.n.u.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@267cde2e 
DEBUG  [2018-09-25 00:39:37,334] [main] i.n.u.i.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0x8803330def489820 (took 0 ms) 
DEBUG  [2018-09-25 00:39:37,337] [main] c.d.d.c.SystemProperties - com.datastax.driver.EXTENDED_PEER_CHECK is undefined, using default value true 
DEBUG  [2018-09-25 00:39:37,350] [main] c.d.d.c.H.STATES - [/10.10.45.18:9042] preparing to open 1 new connections, total = 1 
DEBUG  [2018-09-25 00:39:37,353] [main] c.d.d.c.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false 
DEBUG  [2018-09-25 00:39:37,353] [main] c.d.d.c.SystemProperties - com.datastax.driver.FLUSHER_SCHEDULE_PERIOD_NS is undefined, using default value 10000 
DEBUG  [2018-09-25 00:39:37,353] [main] c.d.d.c.SystemProperties - com.datastax.driver.FLUSHER_RUN_WITHOUT_WORK_TIMES is undefined, using default value 5 
DEBUG  [2018-09-25 00:39:37,358] [main] i.n.u.i.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.com.datastax.driver.core.Message$ResponseMatcher 
DEBUG  [2018-09-25 00:39:37,377] [main] i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4 
DEBUG  [2018-09-25 00:39:37,377] [main] i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 4 
DEBUG  [2018-09-25 00:39:37,377] [main] i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192 
DEBUG  [2018-09-25 00:39:37,377] [main] i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11 
DEBUG  [2018-09-25 00:39:37,377] [main] i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216 
DEBUG  [2018-09-25 00:39:37,378] [main] i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512 
DEBUG  [2018-09-25 00:39:37,378] [main] i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256 
DEBUG  [2018-09-25 00:39:37,378] [main] i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64 
DEBUG  [2018-09-25 00:39:37,378] [main] i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768 
DEBUG  [2018-09-25 00:39:37,378] [main] i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192 
DEBUG  [2018-09-25 00:39:37,378] [main] i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true 
DEBUG  [2018-09-25 00:39:37,390] [main] i.n.u.i.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.com.datastax.driver.core.FrameMatcher 
DEBUG  [2018-09-25 00:39:37,392] [main] i.n.u.i.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.com.datastax.driver.core.Message$RequestMatcher 
DEBUG  [2018-09-25 00:39:37,415] [main] i.n.b.ByteBufUtil - -Dio.netty.allocator.type: unpooled 
DEBUG  [2018-09-25 00:39:37,415] [main] i.n.b.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536 
DEBUG  [2018-09-25 00:39:37,415] [main] i.n.b.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384 
DEBUG  [2018-09-25 00:39:37,439] [MyBiz-nio-worker-0] c.d.d.c.Connection - Connection[/10.10.45.18:9042-1, inFlight=0, closed=false] Connection established, initializing transport 
DEBUG  [2018-09-25 00:39:37,450] [MyBiz-nio-worker-0] i.n.u.Recycler - -Dio.netty.recycler.maxCapacity.default: 32768 
DEBUG  [2018-09-25 00:39:37,450] [MyBiz-nio-worker-0] i.n.u.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2 
DEBUG  [2018-09-25 00:39:37,450] [MyBiz-nio-worker-0] i.n.u.Recycler - -Dio.netty.recycler.linkCapacity: 16 
DEBUG  [2018-09-25 00:39:37,450] [MyBiz-nio-worker-0] i.n.u.Recycler - -Dio.netty.recycler.ratio: 8 
DEBUG  [2018-09-25 00:39:37,460] [MyBiz-nio-worker-0] i.n.b.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true 
DEBUG  [2018-09-25 00:39:37,460] [MyBiz-nio-worker-0] i.n.u.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@12a2f324 
DEBUG  [2018-09-25 00:39:37,467] [MyBiz-nio-worker-0] c.d.d.c.SystemProperties - com.datastax.driver.NATIVE_TRANSPORT_MAX_FRAME_SIZE_IN_MB is undefined, using default value 256 
DEBUG  [2018-09-25 00:39:37,473] [MyBiz-nio-worker-0] c.d.d.c.H.STATES - [/10.10.45.18:9042] Connection[/10.10.45.18:9042-1, inFlight=0, closed=false] Transport initialized, connection ready 
DEBUG  [2018-09-25 00:39:37,474] [main] c.d.d.c.ControlConnection - [Control connection] Refreshing node list and token map 
WARN   [2018-09-25 00:39:37,521] [main] c.d.d.c.Cluster - You listed /10.10.109.9:9042 in your contact points, but it wasn't found in the control host's system.peers at startup 
WARN   [2018-09-25 00:39:37,521] [main] c.d.d.c.Cluster - You listed /10.10.19.157:9042 in your contact points, but it wasn't found in the control host's system.peers at startup 
DEBUG  [2018-09-25 00:39:37,527] [main] c.d.d.c.ControlConnection - [Control connection] Refreshing schema 
DEBUG  [2018-09-25 00:39:37,751] [main] c.d.d.c.ReplicationStrategy$NetworkTopologyStrategy - Computing token to replica map for keyspace: reaper_db. 
DEBUG  [2018-09-25 00:39:37,768] [main] c.d.d.c.ReplicationStrategy$NetworkTopologyStrategy - Token to replica map computation for keyspace reaper_db completed in 17 milliseconds 
DEBUG  [2018-09-25 00:39:37,850] [main] c.d.d.c.H.STATES - [Control connection] established to /10.10.45.18:9042 
INFO   [2018-09-25 00:39:37,850] [main] c.d.d.c.p.DCAwareRoundRobinPolicy - Using provided data-center name 'cassandra-eu-west-1-A' for DCAwareRoundRobinPolicy 
INFO   [2018-09-25 00:39:37,851] [main] c.d.d.c.Cluster - New Cassandra host /54.154.171.184:9042 added 
INFO   [2018-09-25 00:39:37,851] [main] c.d.d.c.Cluster - New Cassandra host /34.245.12.110:9042 added 
INFO   [2018-09-25 00:39:37,851] [main] c.d.d.c.Cluster - New Cassandra host /10.10.45.18:9042 added 
DEBUG  [2018-09-25 00:39:37,855] [main] c.d.d.c.SystemProperties - com.datastax.driver.CHECK_IO_DEADLOCKS is undefined, using default value true 
DEBUG  [2018-09-25 00:39:37,861] [main] c.d.d.c.H.STATES - [/54.154.171.184:9042] preparing to open 1 new connections, total = 1 
DEBUG  [2018-09-25 00:39:37,867] [main] c.d.d.c.H.STATES - [/34.245.12.110:9042] preparing to open 1 new connections, total = 1 
DEBUG  [2018-09-25 00:39:37,868] [main] c.d.d.c.H.STATES - [/10.10.45.18:9042] preparing to open 1 new connections, total = 2 
DEBUG  [2018-09-25 00:39:37,870] [MyBiz-nio-worker-2] c.d.d.c.Connection - Connection[/10.10.45.18:9042-2, inFlight=0, closed=false] Connection established, initializing transport 
DEBUG  [2018-09-25 00:39:37,878] [MyBiz-nio-worker-2] c.d.d.c.H.STATES - [/10.10.45.18:9042] Connection[/10.10.45.18:9042-2, inFlight=0, closed=false] Transport initialized, connection ready 
DEBUG  [2018-09-25 00:39:37,879] [MyBiz-nio-worker-2] c.d.d.c.HostConnectionPool - Created connection pool to host /10.10.45.18:9042 (1 connections needed, 1 successfully opened) 
DEBUG  [2018-09-25 00:39:37,879] [MyBiz-nio-worker-2] c.d.d.c.Session - Added connection pool for /10.10.45.18:9042 
DEBUG  [2018-09-25 00:39:42,872] [MyBiz-nio-worker-0] c.d.d.c.Connection - Connection[/34.245.12.110:9042-1, inFlight=0, closed=false] Error connecting to /34.245.12.110:9042 (connection timed out: /34.245.12.110:9042) 
DEBUG  [2018-09-25 00:39:42,873] [MyBiz-nio-worker-0] c.d.d.c.H.STATES - Defuncting Connection[/34.245.12.110:9042-1, inFlight=0, closed=false] because: [/34.245.12.110:9042] Cannot connect 
DEBUG  [2018-09-25 00:39:42,874] [MyBiz-nio-worker-0] c.d.d.c.H.STATES - [/34.245.12.110:9042] preventing new connections for the next 1000 ms 
DEBUG  [2018-09-25 00:39:42,874] [MyBiz-nio-worker-0] c.d.d.c.H.STATES - [/34.245.12.110:9042] Connection[/34.245.12.110:9042-1, inFlight=0, closed=false] failed, remaining = 0 
DEBUG  [2018-09-25 00:39:42,876] [MyBiz-nio-worker-2] c.d.d.c.Connection - Connection[/54.154.171.184:9042-1, inFlight=0, closed=false] Error connecting to /54.154.171.184:9042 (connection timed out: /54.154.171.184:9042) 
DEBUG  [2018-09-25 00:39:42,877] [MyBiz-nio-worker-2] c.d.d.c.H.STATES - Defuncting Connection[/54.154.171.184:9042-1, inFlight=0, closed=false] because: [/54.154.171.184:9042] Cannot connect 
DEBUG  [2018-09-25 00:39:42,877] [MyBiz-nio-worker-2] c.d.d.c.H.STATES - [/54.154.171.184:9042] preventing new connections for the next 1000 ms 
DEBUG  [2018-09-25 00:39:42,877] [MyBiz-nio-worker-2] c.d.d.c.H.STATES - [/54.154.171.184:9042] Connection[/54.154.171.184:9042-1, inFlight=0, closed=false] failed, remaining = 0 
DEBUG  [2018-09-25 00:39:42,878] [MyBiz-worker-0] c.d.d.c.H.STATES - [/34.245.12.110:9042] marking host DOWN 
DEBUG  [2018-09-25 00:39:42,878] [MyBiz-nio-worker-0] c.d.d.c.Connection - Connection[/34.245.12.110:9042-1, inFlight=0, closed=true] closing connection 
DEBUG  [2018-09-25 00:39:42,881] [MyBiz-worker-0] c.d.d.c.AbstractReconnectionHandler - First reconnection scheduled in 1000ms 
DEBUG  [2018-09-25 00:39:42,884] [MyBiz-nio-worker-2] c.d.d.c.Connection - Connection[/54.154.171.184:9042-1, inFlight=0, closed=true] closing connection 
DEBUG  [2018-09-25 00:39:42,886] [MyBiz-worker-0] c.d.d.c.H.STATES - [/34.245.12.110:9042] starting reconnection attempt 
WARN   [2018-09-25 00:39:42,890] [MyBiz-nio-worker-2] c.d.d.c.HostConnectionPool - Error creating connection to /54.154.171.184:9042 
com.datastax.driver.core.exceptions.TransportException: [/54.154.171.184:9042] Cannot connect
  at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:171)
  at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:154)
  at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
  at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
  at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
  at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
  at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
  at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe$1.run(AbstractEpollStreamChannel.java:762)
  at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
  at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399)
  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
  at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /54.154.171.184:9042
  at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe$1.run(AbstractEpollStreamChannel.java:760)
  ... 7 common frames omitted
DEBUG  [2018-09-25 00:39:42,892] [MyBiz-worker-1] c.d.d.c.H.STATES - [/54.154.171.184:9042] marking host DOWN 
```

</details>

I'd love to resolve this problem and get the Reaper running. @adejanovski as you worked on https://github.com/thelastpickle/cassandra-reaper/pull/91/files, I am hoping you can offer some advice that may help me get around this issue.

Thanks loads in advance for any help!

Happy to provide whatever you need to help resolve this.

**Comment by adejanovski** [comment]
Hi @mattheworiordan,

there are actually 2 places where the address translator can be used : 

1. When Reaper needs to connect through JMX to perform actions on the nodes, and it needs to find out the public address although all it gets are private IPs
2. When Reaper uses Cassandra as a backend on a multi region cluster, which is a Datastax Java Driver setting.

What you've set here is case number 1, but you're trying to handle case number 2 as well (how Reaper connects to its backend).
The thing is we didn't allow to set the address translator on the backend connection in the Docker container yet : https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/docker/configure-persistence.sh#L24-L36

It would be necessary to add the right setting in the yaml as exposed by dropwizard-cassandra : https://github.com/composable-systems/dropwizard-cassandra : 
```
addressTranslator:
  type:
```

If you could push a PR for this it would be much appreciated!

**Comment by mattheworiordan** [comment]
@adejanovski thanks for your response.  That all makes sense.

I'll see what I can do resolve this.  I do very little work in the Java env though, so it's going to be slow.  I'll be in touch when I have time to look at this.

**Comment by mattheworiordan** [comment]
@spodkowinski thanks, #586 works for me.  For anyone else who comes to this, I also had to configure  the following in Cassandra as the JMX connections weren't working from within a Docker container (they were getting the container IP, not the host IP):

In `cassandra-env.sh`:

```
JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=$JMX_HOST_IP"
```

**Comment by adejanovski** [comment]
The fix was merged in master.
