### ISSUE TITLE
Could not create snapshot

### ISSUE THREAD

**Issue by bwmills** [thelastpickle/cassandra-reaper#575]
Hi TLP,

We have `cassandra-reaper` deployed and working well in general. However we have intermittent repair failures that are proving a challenge to debug - any help is much appreciated, thank you.

### Environment

* Google Cloud Platform: `Kubernetes`
* Container type: `Docker`
* OS: `Ubuntu 16.04.3 LTS`

### cassandra-reaper

* Version: `1.2.2` 
* Configs: see below

### Cassandra

* Version: `3.7`
* DCs: `1`
* Cluster Size: `3 nodes` (zone spread across a single GKE region)
* Compaction Strategy: `SizeTieredCompactionStrategy`
* Number of Non-System Keyspaces: `15`

### Kubernetes Manifest 

Just the `ConfigMap` portion with the reaper configs:

* segmentCountPerNode: `16`
* clusterName: `cluster_name`
* localDC: `dc_name`
* contactPoints: `2 of 3 nodes are listed`
* keyspace: `reaper_db`
* autoSchedulingEnabled: `true`
* scheduleSpreadPeriod: `PT2H`
* periodBetweenPolls: `PT10M`
* datacenterAvailability: `local`
* hangingRepairTimeoutMins: `100`
* loggingRootLevel: `DEBUG` (atm)
* loggingAppendersConsoleThreshold: `DEBUG` (atm)
* loggingAppendersLogFormat: `%-6level [%d] [%t] %logger{5} - %msg %n`
* repairIntensity: `0.75` 
* repairManagerSchedulingIntervalSeconds: `30`
* repairParallelism: `SEQUENTIAL`
* repairRunThreadCount: `1`
* scheduleDaysBetween: `1`
* storageType: `cassandra`

### Behavior

Most repairs across most keyspaces are successful and complete without issue. 

Often but not exclusively, in one keyspace, reaper runs repairs for 54 segments, where typically 2 segments fail, each with a fail count of 2. This behavior is reproducible in the sense that we can adjust the regular schedule to test repairs against this keyspace and will encounter these failures, though the token ranges will differ across failures.

### Reaper Logs

A typical set of messages relating to the repair failures:

* debug is enabled
* scrolling down is forward in time
* disk space is not an issue for the C* pods/nodes

```
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.SegmentRunner - It is ok to repair segment '796f4139-d185-11e8-95ec-972a439f3f62' on repair run with id '796dba90-d185-11e8-95ec-972a439f3f62'
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.SegmentRunner - Enter synchronized section with segment ID 796f4139-d185-11e8-95ec-972a439f3f62
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.j.JmxProxy - Triggering repair of range (6878104809564599690,7221031860869113597] for keyspace "test_users" on host 10.2.3.5, with repair parallelism sequential, in cluster with Cassandra version '3.7' (can use DATACENTER_AWARE 'true'), for column families: []
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.j.JmxProxy - Triggering repair for ranges 6878104809564599690:7221031860869113597
[cluster_name–progress–4974] i.c.j.JmxProxy - Received notification: javax.management.Notification[source=repair:4974][type=progress][message=Starting repair command #4974, repairing keyspace test_users with repair options (parallelism: sequential, primary range: false, incremental: false, job threads: 1, ColumnFamilies: [], dataCenters: [], hosts: [], # of ranges: 1)] with type progress
[cluster_name–progress–4974] i.c.j.JmxProxy - Handling notification javax.management.Notification[source=repair:4974][type=progress][message=Starting repair command #4974, repairing keyspace test_users with repair options (parallelism: sequential, primary range: false, incremental: false, job threads: 1, ColumnFamilies: [], dataCenters: [], hosts: [], # of ranges: 1)] with repair handler io.cassandrareaper.service.SegmentRunner@229eb8a9
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.SegmentRunner - Repair for segment 796f4139-d185-11e8-95ec-972a439f3f62 started, status wait will timeout in 6000000 millis
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.SegmentRunner - handle called for repairCommandId 4974, outcome Optional.empty / Optional[START] and message: Starting repair command #4974, repairing keyspace test_users with repair options (parallelism: sequential, primary range: false, incremental: false, job threads: 1, ColumnFamilies: [], dataCenters: [], hosts: [], # of ranges: 1)
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.CassandraStorage - Renewed lead on segment 796f4139-d185-11e8-95ec-972a439f3f62
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.SegmentRunner - updated segment 796f4139-d185-11e8-95ec-972a439f3f62 with state RUNNING
[cluster_name–progress–4974] i.c.j.JmxProxy - Received notification: javax.management.Notification[source=repair:4974][type=progress][message=Repair session bc2e1680-d186-11e8-b17e-ad45a32fc5b8 for range [(6878104809564599690,7221031860869113597]] failed with error Could not create snapshot at /10.2.3.4] with type progress
[cluster_name–progress–4974] i.c.j.JmxProxy - Handling notification javax.management.Notification[source=repair:4974][type=progress][message=Repair session bc2e1680-d186-11e8-b17e-ad45a32fc5b8 for range [(6878104809564599690,7221031860869113597]] failed with error Could not create snapshot at /10.2.3.4] with repair handler io.cassandrareaper.service.SegmentRunner@229eb8a9
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.SegmentRunner - handle called for repairCommandId 4974, outcome Optional.empty / Optional[PROGRESS] and message: Repair session bc2e1680-d186-11e8-b17e-ad45a32fc5b8 for range [(6878104809564599690,7221031860869113597]] failed with error Could not create snapshot at /10.2.3.4 
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.SegmentRunner - Unidentified progressStatus PROGRESS for segment with id '796f4139-d185-11e8-95ec-972a439f3f62' and repair number '4974'
[cluster_name–progress–4974] i.c.j.JmxProxy - Received notification: javax.management.Notification[source=repair:4974][type=progress][message=Some repair failed] with type progress
[cluster_name–progress–4974] i.c.j.JmxProxy - Handling notification javax.management.Notification[source=repair:4974][type=progress][message=Some repair failed] with repair handler io.cassandrareaper.service.SegmentRunner@229eb8a9
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.SegmentRunner - handle called for repairCommandId 4974, outcome Optional.empty / Optional[ERROR] and message: Some repair failed
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.SegmentRunner - repair session failed for segment with id '796f4139-d185-11e8-95ec-972a439f3f62' and repair number '4974'
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.CassandraStorage - Trying to take lead on segment 796f4139-d185-11e8-95ec-972a439f3f62
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.CassandraStorage - Could not take lead on segment 796f4139-d185-11e8-95ec-972a439f3f62
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.CassandraStorage - Renewed lead on segment 796f4139-d185-11e8-95ec-972a439f3f62
[cluster_name:796dba90-d185-11e8-95ec-972a439f3f62:796f4139-d185-11e8-95ec-972a439f3f62] i.c.s.SegmentRunner - Postponing segment 796f4139-d185-11e8-95ec-972a439f3f62

```

**Comment by bwmills** [comment]
Changed title in hopes that someone has insight on:

```
failed with error Could not create snapshot at ...
```
@adejanovski

**Comment by adejanovski** [comment]
@bwmills, the problem seems to be related to Cassandra.
You're using `sequential` as repair parallelism, which requires the nodes to take a snapshot, and apparently that fails.

Could you check the Cassandra logs to see what error message pops up there? We should be able to find an explanation there.

You can change the parallelism to `parallel` if you want to repair without snapshots. All nodes will compute the Merkle trees at the same time so it'll be more intensive for the cluster.

**Comment by bwmills** [comment]
@adejanovski - before deploying `cassandra-reaper`, we automated repairs in the GKE environment with a cron job script that rotated between --full and incremental, both of which were run with `parallelism: parallel`. Here are some of the C* repair errors that occurred at that time:

(C* version and cluster size unchanged)

*repair output*
```
[2018-09-06 15:05:35,255] Starting repair command #269, repairing keyspace test_users with repair options (parallelism: parallel, primary range: false, incremental: false, job threads: 1, ColumnFamilies: [], dataCenters: [], hosts: [], # of ranges: 12)
[2018-09-06 15:05:35,552] Repair session 4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4 for range [(-1890954128429545684,2847510199483651721], (8249813014782655320,-8746483007209345011], (4299912178579297893,6811748355903297393], (-8746483007209345011,-8628999431140554276], (-5865769407232506956,-4746990901966533744], (-4470950459111056725,-1890954128429545684], (4001531392883953257,4299912178579297893], (6811748355903297393,6878104809564599690], (6878104809564599690,8249813014782655320], (-4746990901966533744,-4470950459111056725], (-8628999431140554276,-5865769407232506956], (2847510199483651721,4001531392883953257]] failed with error [repair #4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4 on test_users/access_tokens_v2, [(-1890954128429545684,2847510199483651721], (8249813014782655320,-8746483007209345011], (4299912178579297893,6811748355903297393], (-8746483007209345011,-8628999431140554276], (-5865769407232506956,-4746990901966533744], (-4470950459111056725,-1890954128429545684], (4001531392883953257,4299912178579297893], (6811748355903297393,6878104809564599690], (6878104809564599690,8249813014782655320], (-4746990901966533744,-4470950459111056725], (-8628999431140554276,-5865769407232506956], (2847510199483651721,4001531392883953257]]] Validation failed in /10.48.1.3 (progress: 26%)
[2018-09-06 15:05:35,555] Some repair failed
[2018-09-06 15:05:35,555] Repair command #269 finished in 0 seconds
```

*logs*
```
{"message":"1207280292 o.apache.cassandra.repair.Validator - Failed creating a merkle tree for [repair #4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4 on test_users/access_tokens_v2, [(-1890954128429545684,2847510199483651721], (8249813014782655320,-8746483007209345011], (4299912178579297893,6811748355903297393], (-8746483007209345011,-8628999431140554276], (-5865769407232506956,-4746990901966533744], (-4470950459111056725,-1890954128429545684], (4001531392883953257,4299912178579297893], (6811748355903297393,6878104809564599690], (6878104809564599690,8249813014782655320], (-4746990901966533744,-4470950459111056725], (-8628999431140554276,-5865769407232506956], (2847510199483651721,4001531392883953257]]], /10.38.1.3 (see log for details)","timestamp":{"seconds":1536246335,"nanos":547000000},"severity":"ERROR","thread":"ValidationExecutor:52"}
{"message":"1207280293 o.a.cassandra.repair.RepairSession - [repair #4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4] Received merkle tree for access_tokens_v2 from /10.38.1.3","timestamp":{"seconds":1536246335,"nanos":548000000},"severity":"INFO","thread":"AntiEntropyStage:1"}
{"message":"1207280294 o.apache.cassandra.repair.RepairJob - [repair #4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4] access_tokens_v2 sync failed","timestamp":{"seconds":1536246335,"nanos":549000000},"severity":"WARN","thread":"RepairJobTask:1"}
{"message":"1207280295 o.a.cassandra.repair.RepairSession - [repair #4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4] Session completed with the following errororg.apache.cassandra.exceptions.RepairException: [repair #4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4 on test_users/access_tokens_v2, [(-1890954128429545684,2847510199483651721], (8249813014782655320,-8746483007209345011], (4299912178579297893,6811748355903297393], (-8746483007209345011,-8628999431140554276], (-5865769407232506956,-4746990901966533744], (-4470950459111056725,-1890954128429545684], (4001531392883953257,4299912178579297893], (6811748355903297393,6878104809564599690], (6878104809564599690,8249813014782655320], (-4746990901966533744,-4470950459111056725], (-8628999431140554276,-5865769407232506956], (2847510199483651721,4001531392883953257]]] Validation failed in /10.38.1.3\n\tat org.apache.cassandra.repair.ValidationTask.treesReceived(ValidationTask.java:68)\n\tat org.apache.cassandra.repair.RepairSession.validationComplete(RepairSession.java:183)\n\tat org.apache.cassandra.service.ActiveRepairService.handleMessage(ActiveRepairService.java:439)\n\tat org.apache.cassandra.repair.RepairMessageVerbHandler.doVerb(RepairMessageVerbHandler.java:169)\n\tat org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:64)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","timestamp":{"seconds":1536246335,"nanos":550000000},"severity":"ERROR","thread":"RepairJobTask:1"}
{"message":"1207280295 o.a.cassandra.repair.RepairRunnable - Repair session 4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4 for range [(-1890954128429545684,2847510199483651721], (8249813014782655320,-8746483007209345011], (4299912178579297893,6811748355903297393], (-8746483007209345011,-8628999431140554276], (-5865769407232506956,-4746990901966533744], (-4470950459111056725,-1890954128429545684], (4001531392883953257,4299912178579297893], (6811748355903297393,6878104809564599690], (6878104809564599690,8249813014782655320], (-4746990901966533744,-4470950459111056725], (-8628999431140554276,-5865769407232506956], (2847510199483651721,4001531392883953257]] failed with error [repair #4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4 on test_users/access_tokens_v2, [(-1890954128429545684,2847510199483651721], (8249813014782655320,-8746483007209345011], (4299912178579297893,6811748355903297393], (-8746483007209345011,-8628999431140554276], (-5865769407232506956,-4746990901966533744], (-4470950459111056725,-1890954128429545684], (4001531392883953257,4299912178579297893], (6811748355903297393,6878104809564599690], (6878104809564599690,8249813014782655320], (-4746990901966533744,-4470950459111056725], (-8628999431140554276,-5865769407232506956], (2847510199483651721,4001531392883953257]]] Validation failed in /10.38.1.3org.apache.cassandra.exceptions.RepairException: [repair #4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4 on test_users/access_tokens_v2, [(-1890954128429545684,2847510199483651721], (8249813014782655320,-8746483007209345011], (4299912178579297893,6811748355903297393], (-8746483007209345011,-8628999431140554276], (-5865769407232506956,-4746990901966533744], (-4470950459111056725,-1890954128429545684], (4001531392883953257,4299912178579297893], (6811748355903297393,6878104809564599690], (6878104809564599690,8249813014782655320], (-4746990901966533744,-4470950459111056725], (-8628999431140554276,-5865769407232506956], (2847510199483651721,4001531392883953257]]] Validation failed in /10.38.1.3\n\tat org.apache.cassandra.repair.ValidationTask.treesReceived(ValidationTask.java:68)\n\tat org.apache.cassandra.repair.RepairSession.validationComplete(RepairSession.java:183)\n\tat org.apache.cassandra.service.ActiveRepairService.handleMessage(ActiveRepairService.java:439)\n\tat org.apache.cassandra.repair.RepairMessageVerbHandler.doVerb(RepairMessageVerbHandler.java:169)\n\tat org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:64)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","timestamp":{"seconds":1536246335,"nanos":550000000},"severity":"ERROR","thread":"RepairJobTask:1"}
```
```
{"message":"1207280296 o.a.c.service.CassandraDaemon - Exception in thread Thread[Repair#269:1,5,RMI Runtime]com.google.common.util.concurrent.UncheckedExecutionException: org.apache.cassandra.exceptions.RepairException: [repair #4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4 on test_users/access_tokens_v2, [(-1890954128429545684,2847510199483651721], (8249813014782655320,-8746483007209345011], (4299912178579297893,6811748355903297393], (-8746483007209345011,-8628999431140554276], (-5865769407232506956,-4746990901966533744], (-4470950459111056725,-1890954128429545684], (4001531392883953257,4299912178579297893], (6811748355903297393,6878104809564599690], (6878104809564599690,8249813014782655320], (-4746990901966533744,-4470950459111056725], (-8628999431140554276,-5865769407232506956], (2847510199483651721,4001531392883953257]]] Validation failed in /10.38.1.3\n\tat com.google.common.util.concurrent.Futures.wrapAndThrowUnchecked(Futures.java:1525)\n\tat com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1511)\n\tat org.apache.cassandra.repair.RepairJob.run(RepairJob.java:160)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.cassandra.exceptions.RepairException: [repair #4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4 on test_users/access_tokens_v2, [(-1890954128429545684,2847510199483651721], (8249813014782655320,-8746483007209345011], (4299912178579297893,6811748355903297393], (-8746483007209345011,-8628999431140554276], (-5865769407232506956,-4746990901966533744], (-4470950459111056725,-1890954128429545684], (4001531392883953257,4299912178579297893], (6811748355903297393,6878104809564599690], (6878104809564599690,8249813014782655320], (-4746990901966533744,-4470950459111056725], (-8628999431140554276,-5865769407232506956], (2847510199483651721,4001531392883953257]]] Validation failed in /10.38.1.3\n\tat org.apache.cassandra.repair.ValidationTask.treesReceived(ValidationTask.java:68)\n\tat org.apache.cassandra.repair.RepairSession.validationComplete(RepairSession.java:183)\n\tat org.apache.cassandra.service.ActiveRepairService.handleMessage(ActiveRepairService.java:439)\n\tat org.apache.cassandra.repair.RepairMessageVerbHandler.doVerb(RepairMessageVerbHandler.java:169)\n\tat org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:64)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\t... 3 common frames omitted\n","timestamp":{"seconds":1536246335,"nanos":551000000},"severity":"ERROR","thread":"Repair#269:1"}
{"message":"1207280296 o.apache.cassandra.repair.RepairJob - [repair #4e82a7a0-b1e6-11e8-bcb1-21ebfd9b27f4] Requesting merkle trees for invitations (to [/10.38.3.3, /10.38.2.3, /10.38.1.3])","timestamp":{"seconds":1536246335,"nanos":551000000},"severity":"INFO","thread":"Repair#269:2"}
{"message":"1207280298 o.a.cassandra.repair.RepairRunnable - Repair command #269 finished in 0 seconds"
```
We also had these errors (only have partial logs on this)
```
Streaming error occurred on session with peer 10.38.2.3
...
{"message":"1016344498 o.a.c.streaming.StreamResultFuture - [Stream #bff03ba0-b029-11e8-bcb1-21ebfd9b27f4] Session with /10.38.2.3 is complete","timestamp":{"seconds":1536055399,"nanos":753000000},"severity":"INFO","thread":"StreamReceiveTask:25"}
{"message":"1016344498 o.a.c.streaming.StreamResultFuture - [Stream #bff03ba0-b029-11e8-bcb1-21ebfd9b27f4] Stream failed","timestamp":{"seconds":1536055399,"nanos":753000000},"severity":"WARN","thread":"StreamReceiveTask:25"}
{"message":"1016344500 o.a.cassandra.repair.RepairSession - [repair #c00d1270-b029-11e8-bcb1-21ebfd9b27f4] Received merkle tree for resource_role_permissons_index from /10.38.2.3","timestamp":{"seconds":1536055399,"nanos":755000000},"severity":"INFO","thread":"AntiEntropyStage:1"}
{"message":"1016344501 o.a.cassandra.repair.RepairSession - [repair #c00d1270-b029-11e8-bcb1-21ebfd9b27f4] Received merkle tree for resource_role_permissons_index from /10.38.1.3","timestamp":{"seconds":1536055399,"nanos":756000000},"severity":"INFO","thread":"AntiEntropyStage:1"}
  Sep 04, 2018 10:03:19 AM com.google.common.util.concurrent.Futures$CombinedFuture setExceptionAndMaybeLog
  SEVERE: input future failed.
  org.apache.cassandra.streaming.StreamException: Stream failed
```

Then after reading [Should you use incremental repair?](http://thelastpickle.com/blog/2017/12/14/should-you-use-incremental-repair.html), the repair method used by `cassandra-reaper` sounded like a better / safer approach. Prior to deploying reaper v1.2.2, we did update the sstable metadata like so:

```
./sstablerepairedset --really-set --is-unrepaired -f markAllSSTablesAsUnrepaired.txt
``` 
Since running repairs with reaper, we still have failures on the `test_users` keyspace (often the `access_tokens_v2` table) though of course the log output has changed per the segmented, `parallelism: sequential` (mostly default) config we have with reaper.

Here is a sample from recent C* logs during sequential repairs managed by reaper:

```
2018-10-16T16:13:41.607995243Z {"message":"404055900 o.a.c.r.RepairMessageVerbHandler - Got error, removing parent repair session","timestamp":{"seconds":1539706421,"nanos":597000000},"severity":"ERROR","thread":"AntiEntropyStage:1"}
2018-10-16T16:13:41.608001247Z {"message":"404055900 o.a.c.service.CassandraDaemon - Exception in thread Thread[AntiEntropyStage:1,5,main]java.lang.RuntimeException: java.lang.RuntimeException: Parent repair session with id = 72926d50-d15e-11e8-902a-13dcccbb0063 has failed.\n\tat org.apache.cassandra.repair.RepairMessageVerbHandler.doVerb(RepairMessageVerbHandler.java:178)\n\tat org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:64)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.RuntimeException: Parent repair session with id = 72926d50-d15e-11e8-902a-13dcccbb0063 has failed.\n\tat org.apache.cassandra.service.ActiveRepairService.getParentRepairSession(ActiveRepairService.java:372)\n\tat org.apache.cassandra.repair.RepairMessageVerbHandler.doVerb(RepairMessageVerbHandler.java:103)\n\t... 6 common frames omitted\n","timestamp":{"seconds":1539706421,"nanos":597000000},"severity":"ERROR","thread":"AntiEntropyStage:1"}
2018-10-16T16:13:41.608046007Z Oct 16, 2018 4:13:41 PM com.google.common.util.concurrent.Futures$CombinedFuture setExceptionAndMaybeLog
2018-10-16T16:13:41.608074154Z SEVERE: input future failed.
2018-10-16T16:13:41.608079603Z java.lang.RuntimeException: Could not create snapshot at /10.38.6.5
2018-10-16T16:13:41.608083875Z 	at org.apache.cassandra.repair.SnapshotTask$SnapshotCallback.onFailure(SnapshotTask.java:79)
2018-10-16T16:13:41.608087953Z 	at org.apache.cassandra.net.ResponseVerbHandler.doVerb(ResponseVerbHandler.java:47)
2018-10-16T16:13:41.608103273Z 	at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:64)
2018-10-16T16:13:41.608107161Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2018-10-16T16:13:41.608111054Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-10-16T16:13:41.608114582Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-10-16T16:13:41.608118199Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-10-16T16:13:41.608121812Z 	at java.lang.Thread.run(Thread.java:748)
2018-10-16T16:13:41.60812534Z
2018-10-16T16:13:41.608128938Z Oct 16, 2018 4:13:41 PM com.google.common.util.concurrent.Futures$CombinedFuture setExceptionAndMaybeLog
2018-10-16T16:13:41.608132772Z SEVERE: input future failed.
2018-10-16T16:13:41.60813641Z java.lang.RuntimeException: Could not create snapshot at /10.38.6.5
2018-10-16T16:13:41.608140487Z 	at org.apache.cassandra.repair.SnapshotTask$SnapshotCallback.onFailure(SnapshotTask.java:79)
2018-10-16T16:13:41.608144348Z 	at org.apache.cassandra.net.ResponseVerbHandler.doVerb(ResponseVerbHandler.java:47)
2018-10-16T16:13:41.608148133Z 	at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:64)
2018-10-16T16:13:41.608151685Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2018-10-16T16:13:41.608155058Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-10-16T16:13:41.608158397Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-10-16T16:13:41.608162018Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-10-16T16:13:41.608166002Z 	at java.lang.Thread.run(Thread.java:748)
2018-10-16T16:13:41.608169859Z
2018-10-16T16:13:41.629246414Z {"message":"404055931 o.a.c.service.CassandraDaemon - Exception in thread Thread[CompactionExecutor:183,1,main]java.lang.AssertionError: null\n\tat org.apache.cassandra.io.sstable.SSTableRewriter.moveStarts(SSTableRewriter.java:262)\n\tat org.apache.cassandra.io.sstable.SSTableRewriter.switchWriter(SSTableRewriter.java:318)\n\tat org.apache.cassandra.io.sstable.SSTableRewriter.doPrepare(SSTableRewriter.java:364)\n\tat org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.prepareToCommit(Transactional.java:173)\n\tat org.apache.cassandra.db.compaction.writers.CompactionAwareWriter.doPrepare(CompactionAwareWriter.java:111)\n\tat org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.prepareToCommit(Transactional.java:173)\n\tat org.apache.cassandra.utils.concurrent.Transactional$AbstractTransactional.finish(Transactional.java:184)\n\tat org.apache.cassandra.db.compaction.writers.CompactionAwareWriter.finish(CompactionAwareWriter.java:121)\n\tat org.apache.cassandra.db.compaction.CompactionTask.runMayThrow(CompactionTask.java:198)\n\tat org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28)\n\tat org.apache.cassandra.db.compaction.CompactionTask.executeInternal(CompactionTask.java:82)\n\tat org.apache.cassandra.db.compaction.AbstractCompactionTask.execute(AbstractCompactionTask.java:60)\n\tat org.apache.cassandra.db.compaction.CompactionManager$BackgroundCompactionCandidate.run(CompactionManager.java:264)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","timestamp":{"seconds":1539706421,"nanos":628000000},"severity":"ERROR","thread":"CompactionExecutor:183"}
2018-10-16T16:14:11.473409395Z {"message":"404085776 o.a.cassandra.repair.RepairRunnable - Starting repair command #1276, repairing keyspace test_users with repair options (parallelism: sequential, primary range: false, incremental: false, job threads: 1, ColumnFamilies: [], dataCenters: [], hosts: [], # of ranges: 1)","timestamp":{"seconds":1539706451,"nanos":473000000},"severity":"INFO","thread":"Thread-9363"}
2018-10-16T16:14:11.475727189Z {"message":"404085778 o.a.cassandra.repair.RepairSession - [repair #847d8630-d15e-11e8-902a-13dcccbb0063] new session: will sync /10.38.6.5, /10.38.3.42, /10.38.1.44 on range [(2483012943490328843,2847510199483651721]] for test_users.[testaccesstokens, cassandra_migration_version_counts, clients, cassandra_migration_version, clientgranttypes, clients_by_id, roles, users_v2, access_tokens_v2, invitations]","timestamp":{"seconds":1539706451,"nanos":475000000},"severity":"INFO","thread":"Thread-9363"}
```

I realize the issue here is with our C* and not with reaper - any feedback is much appreciated.

**Comment by bwmills** [comment]
@adejanovski - any thoughts on above?

**Comment by bwmills** [comment]
@adejanovski - thanks again for your input earlier - feel free to close this of course as it's not an issue with reaper.
