### ISSUE TITLE
Unable schedule repairs

### ISSUE THREAD

**Issue by r4fek** [thelastpickle/cassandra-reaper#59]
Hi,

I'm trying to schedule repair on my cluster, but with no luck. I get `{"message":"There was an error processing your request. It has been logged (ID af6991042de7f785)."}` response in UI and here's the log:

```
INFO   [2017-03-10 08:18:11,384] [dw-172 - POST /repair_schedule?clusterName=productioncluster&keyspace=accounts&owner=rfurmanski&scheduleTriggerTime=2017-03-10T23%3A59&scheduleDaysBetween=3&repairParallelism=SEQUENTIAL&intensity=0.95&incrementalRepair=false] c.s.r.r.RepairScheduleResource - add repair schedule called with: clusterName = Optional.of(productioncluster), keyspace = Optional.of(accounts), tables = Optional.absent(), owner = Optional.of(rfurmanski), segmentCount = Optional.absent(), repairParallelism = Optional.of(SEQUENTIAL), intensity = Optional.of(0.95), incrementalRepair = Optional.of(false), scheduleDaysBetween = Optional.of(3), scheduleTriggerTime = Optional.of(2017-03-10T23:59) 
INFO   [2017-03-10 08:18:11,431] [dw-172 - POST /repair_schedule?clusterName=productioncluster&keyspace=accounts&owner=rfurmanski&scheduleTriggerTime=2017-03-10T23%3A59&scheduleDaysBetween=3&repairParallelism=SEQUENTIAL&intensity=0.95&incrementalRepair=false] c.s.r.r.RepairScheduleResource - first schedule activation will be: 2017-03-10T23:59:00Z 
ERROR  [2017-03-10 08:18:11,436] [dw-172 - POST /repair_schedule?clusterName=productioncluster&keyspace=accounts&owner=rfurmanski&scheduleTriggerTime=2017-03-10T23%3A59&scheduleDaysBetween=3&repairParallelism=SEQUENTIAL&intensity=0.95&incrementalRepair=false] i.d.j.e.LoggingExceptionMapper - Error handling a request: c42c96a4a6402f4b 
java.lang.NullPointerException: null
	at com.spotify.reaper.resources.RepairScheduleResource.addRepairSchedule(RepairScheduleResource.java:152) ~[cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at io.dropwizard.jersey.guava.OptionalResourceMethodDispatchAdapter$OptionalRequestDispatcher.dispatch(OptionalResourceMethodDispatchAdapter.java:37) ~[cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.server.impl.uri.rules.ResourceObjectRule.accept(ResourceObjectRule.java:100) ~[cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:295) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:127) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:44) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:248) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:211) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:175) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:92) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:162) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.server.Server.handle(Server.java:446) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [cassandra-reaper-0.4.0.jar:0.4.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```
Can you help me?

**Comment by adejanovski** [comment]
Hi, 

it looks like `scheduleDaysBetween` is not set in your yaml config file. Can you try to set it to 7 like in the defaults and see if it works ?

Thanks

**Comment by r4fek** [comment]
Thanks for such quick response! It indeed helped :+1:
