### ISSUE TITLE
Cassandra Reaper v1.4.0 won't start after upgrading from v1.3.0

### ISSUE THREAD

**Issue by rsaffi** [thelastpickle/cassandra-reaper#613]
I've been running v.1.3.0 without any issues but today after upgrading it to v.1.4.0 the service won't start. No changes in configuration were made; simply upgraded the package version via `apt`.

System is Ubuntu Server 16.04; package installed using `https://dl.bintray.com/thelastpickle/reaper-deb` repository.

Here are the logs for starting the service with v.1.3.0 (working):

```
Feb 12 16:53:00 rpr01 cassandra-reaper[23190]: ls: cannot access 'server/target/cassandra-reaper-*.jar': No such file or directory
Feb 12 16:53:00 rpr01 cassandra-reaper[23190]: Looking for reaper in /usr/share/cassandra-reaper/
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:02,075] [main] i.c.ReaperApplication - initializing runner thread pool with 15 threads
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:02,091] [main] i.c.ReaperApplication - initializing storage of type: postgres
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:02,154] [main] o.f.c.i.u.VersionPrinter - Flyway Community Edition 5.1.0 by Boxfuse
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:02,284] [main] o.f.c.i.d.DatabaseFactory - Database: jdbc:postgresql://pg01.node.consul/cassandra_reaper (PostgreSQL 9.4)
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,326] [main] o.f.c.i.s.JdbcTableSchemaHistory - Could not find schema history table "public"."flyway_schema_history", but found "public"."schema_version" instead. You are seeing this message because Flyway changed its default for flyway.table in version 5.0.0 to flyway_schema_history and you are still relying on the old default (schema_version). Set flyway.table=schema_version in your configuration to fix this. This fallback mechanism will be removed in Flyway 6.0.0.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:02,395] [main] o.f.c.i.s.JdbcTableSchemaHistory - Repair of failed migration in Schema History table "public"."schema_version" not necessary. No failed migration detected.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:02,417] [main] o.f.c.i.c.DbRepair - Successfully repaired schema history table "public"."schema_version" (execution time 00:00.036s).
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,429] [main] o.f.c.i.s.JdbcTableSchemaHistory - Could not find schema history table "public"."flyway_schema_history", but found "public"."schema_version" instead. You are seeing this message because Flyway changed its default for flyway.table in version 5.0.0 to flyway_schema_history and you are still relying on the old default (schema_version). Set flyway.table=schema_version in your configuration to fix this. This fallback mechanism will be removed in Flyway 6.0.0.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:02,470] [main] o.f.c.i.c.DbValidate - Successfully validated 11 migrations (execution time 00:00.010s)
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:02,483] [main] o.f.c.i.c.DbMigrate - Current version of schema "public": 11.0.0
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,484] [main] o.f.c.i.c.DbMigrate - Schema "public" has a version (11.0.0) that is newer than the latest available migration (10.0.0) !
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:02,485] [main] o.f.c.i.c.DbMigrate - Schema "public" is up to date. No migration necessary.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,497] [main] o.a.t.j.p.PooledConnection - Not loading a JDBC driver as driverClassName property is null.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,503] [main] o.a.t.j.p.PooledConnection - Not loading a JDBC driver as driverClassName property is null.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,512] [main] o.a.t.j.p.PooledConnection - Not loading a JDBC driver as driverClassName property is null.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,521] [main] o.a.t.j.p.PooledConnection - Not loading a JDBC driver as driverClassName property is null.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,531] [main] o.a.t.j.p.PooledConnection - Not loading a JDBC driver as driverClassName property is null.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,542] [main] o.a.t.j.p.PooledConnection - Not loading a JDBC driver as driverClassName property is null.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,551] [main] o.a.t.j.p.PooledConnection - Not loading a JDBC driver as driverClassName property is null.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,565] [main] o.a.t.j.p.PooledConnection - Not loading a JDBC driver as driverClassName property is null.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,575] [main] o.a.t.j.p.PooledConnection - Not loading a JDBC driver as driverClassName property is null.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:02,584] [main] o.a.t.j.p.PooledConnection - Not loading a JDBC driver as driverClassName property is null.
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:02,786] [main] i.c.ReaperApplication - no JMX connection factory given in context, creating default
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:02,791] [main] i.c.ReaperApplication - creating and registering health checks
Feb 12 16:53:02 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:02,792] [main] i.c.ReaperApplication - creating resources and registering endpoints
Feb 12 16:53:03 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:03,826] [main] i.c.s.SchedulingManager - Starting new SchedulingManager instance
Feb 12 16:53:03 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:03,827] [main] i.c.s.AutoSchedulingManager - Starting new AutoSchedulingManager instance. First check in 15000ms. Subsequent polls every 300000ms
Feb 12 16:53:03 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:03,828] [main] i.c.ReaperApplication - Initializing JMX seed list for all clusters...
Feb 12 16:53:03 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:03,888] [main] i.c.ReaperApplication - Initialized JMX seed list for all clusters.
Feb 12 16:53:03 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:03,888] [main] i.c.ReaperApplication - resuming pending repair runs
Feb 12 16:53:03 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:03,907] [main] i.c.ReaperApplication - Initialization complete!
Feb 12 16:53:03 rpr01 cassandra-reaper[23190]: WARN   [2019-02-12 16:53:03,907] [main] i.c.ReaperApplication - Reaper is ready to get things done!
Feb 12 16:53:04 rpr01 cassandra-reaper[23190]: INFO   [2019-02-12 16:53:04,141] [ReaperApplication-scheduler] i.c.ReaperApplication - Purged 0 repair runs from history
```

And here's the service logs after updating to v.1.4.0:

```
[* DEV *] [SXB_DEV] root@rpr01:/etc/cassandra-reaper # apt install -y reaper=1.4.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  reaper
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 56.8 MB of archives.
After this operation, 1,109 kB of additional disk space will be used.
Get:1 https://dl.bintray.com/thelastpickle/reaper-deb wheezy/main amd64 reaper amd64 1.4.0 [56.8 MB]
Fetched 56.8 MB in 5s (10.9 MB/s) 
(Reading database ... 147748 files and directories currently installed.)
Preparing to unpack .../reaper_1.4.0_amd64.deb ...
997
skipping user
Unpacking reaper (1.4.0) over (1.3.0) ...
Processing triggers for systemd (229-4ubuntu21.15) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up reaper (1.4.0) ...
Installing new version of config file /etc/cassandra-reaper/configs/cassandra-reaper-cassandra-ssl.yaml ...
Installing new version of config file /etc/cassandra-reaper/configs/cassandra-reaper-cassandra.yaml ...
Installing new version of config file /etc/cassandra-reaper/configs/cassandra-reaper-h2.yaml ...
Installing new version of config file /etc/cassandra-reaper/configs/cassandra-reaper-memory.yaml ...
Installing new version of config file /etc/cassandra-reaper/configs/cassandra-reaper-postgres.yaml ...
Installing new version of config file /etc/cassandra-reaper/configs/cassandra-reaper.yaml ...

[* DEV *] [SXB_DEV] root@rpr01:/etc/cassandra-reaper # service cassandra-reaper start
Feb 12 16:58:29 rpr01 cassandra-reaper[23424]: ls: cannot access 'server/target/cassandra-reaper-*.jar': No such file or directory
Feb 12 16:58:29 rpr01 cassandra-reaper[23424]: Looking for reaper in /usr/share/cassandra-reaper/
Feb 12 16:58:30 rpr01 cassandra-reaper[23424]: INFO   [2019-02-12 16:58:30,765] [main] i.c.ReaperApplication - initializing runner thread pool with 15 threads
Feb 12 16:58:30 rpr01 cassandra-reaper[23424]: INFO   [2019-02-12 16:58:30,784] [main] i.c.ReaperApplication - initializing storage of type: postgres
Feb 12 16:58:30 rpr01 cassandra-reaper[23424]: INFO   [2019-02-12 16:58:30,848] [main] o.f.c.i.u.VersionPrinter - Flyway Community Edition 5.1.0 by Boxfuse
Feb 12 16:58:30 rpr01 cassandra-reaper[23424]: INFO   [2019-02-12 16:58:30,915] [main] o.f.c.i.d.DatabaseFactory - Database: jdbc:postgresql://pg01.node.consul/cassandra_reaper (PostgreSQL 9.4)
Feb 12 16:58:30 rpr01 cassandra-reaper[23424]: WARN   [2019-02-12 16:58:30,948] [main] o.f.c.i.s.JdbcTableSchemaHistory - Could not find schema history table "public"."flyway_schema_history", but found "public"."schema_version" instead. You are seeing this message because Flyway changed its default for flyway.table in version 5.0.0 to flyway_schema_history and you are still relying on the old default (schema_version). Set flyway.table=schema_version in your configuration to fix this. This fallback mechanism will be removed in Flyway 6.0.0.
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: INFO   [2019-02-12 16:58:31,018] [main] o.f.c.i.s.JdbcTableSchemaHistory - Repair of failed migration in Schema History table "public"."schema_version" not necessary. No failed migration detected.
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: INFO   [2019-02-12 16:58:31,036] [main] o.f.c.i.c.DbRepair - Successfully repaired schema history table "public"."schema_version" (execution time 00:00.030s).
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: WARN   [2019-02-12 16:58:31,050] [main] o.f.c.i.s.JdbcTableSchemaHistory - Could not find schema history table "public"."flyway_schema_history", but found "public"."schema_version" instead. You are seeing this message because Flyway changed its default for flyway.table in version 5.0.0 to flyway_schema_history and you are still relying on the old default (schema_version). Set flyway.table=schema_version in your configuration to fix this. This fallback mechanism will be removed in Flyway 6.0.0.
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: INFO   [2019-02-12 16:58:31,104] [main] o.f.c.i.c.DbValidate - Successfully validated 11 migrations (execution time 00:00.013s)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: INFO   [2019-02-12 16:58:31,120] [main] o.f.c.i.c.DbMigrate - Current version of schema "public": 11.0.0
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: INFO   [2019-02-12 16:58:31,122] [main] o.f.c.i.c.DbMigrate - Schema "public" is up to date. No migration necessary.
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: ERROR  [2019-02-12 16:58:31,136] [main] o.a.t.j.p.ConnectionPool - Unable to create initial connections of pool.
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: java.sql.SQLException: Unable to load class:  from ClassLoader:sun.misc.Launcher$AppClassLoader@7852e922;ClassLoader:sun.misc.Launcher$AppClassLoader@7852e922
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:292)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:212)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:739)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:671)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:483)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.skife.jdbi.v2.DataSourceConnectionFactory.openConnection(DataSourceConnectionFactory.java:34)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.skife.jdbi.v2.DBI.open(DBI.java:211)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.cassandrareaper.storage.PostgresStorage.isStorageConnected(PostgresStorage.java:124)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:343)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:174)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:80)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.dropwizard.cli.Cli.run(Cli.java:78)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.dropwizard.Application.run(Application.java:93)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:99)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: Caused by: java.lang.ClassNotFoundException: Unable to load class:  from ClassLoader:sun.misc.Launcher$AppClassLoader@7852e922;ClassLoader:sun.misc.Launcher$AppClassLoader@7852e922
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:56)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:281)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011... 19 common frames omitted
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: Caused by: java.lang.ClassNotFoundException:
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at java.lang.Class.forName0(Native Method)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at java.lang.Class.forName(Class.java:348)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:38)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011... 20 common frames omitted
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException: java.sql.SQLException: Unable to load class:  from ClassLoader:sun.misc.Launcher$AppClassLoader@7852e922;ClassLoader:sun.misc.Launcher$AppClassLoader@7852e922
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.skife.jdbi.v2.DBI.open(DBI.java:229)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.cassandrareaper.storage.PostgresStorage.isStorageConnected(PostgresStorage.java:124)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:343)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:174)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:80)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.dropwizard.cli.Cli.run(Cli.java:78)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.dropwizard.Application.run(Application.java:93)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:99)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: Caused by: java.sql.SQLException: Unable to load class:  from ClassLoader:sun.misc.Launcher$AppClassLoader@7852e922;ClassLoader:sun.misc.Launcher$AppClassLoader@7852e922
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:292)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:212)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:739)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:671)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:483)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.skife.jdbi.v2.DataSourceConnectionFactory.openConnection(DataSourceConnectionFactory.java:34)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.skife.jdbi.v2.DBI.open(DBI.java:211)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011... 9 more
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: Caused by: java.lang.ClassNotFoundException: Unable to load class:  from ClassLoader:sun.misc.Launcher$AppClassLoader@7852e922;ClassLoader:sun.misc.Launcher$AppClassLoader@7852e922
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:56)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:281)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011... 19 more
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: Caused by: java.lang.ClassNotFoundException:
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at java.lang.Class.forName0(Native Method)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at java.lang.Class.forName(Class.java:348)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:38)
Feb 12 16:58:31 rpr01 cassandra-reaper[23424]: #011... 20 more
Feb 12 16:58:31 rpr01 systemd[1]: cassandra-reaper.service: Main process exited, code=exited, status=1/FAILURE
Feb 12 16:58:31 rpr01 systemd[1]: cassandra-reaper.service: Unit entered failed state.
Feb 12 16:58:31 rpr01 systemd[1]: cassandra-reaper.service: Failed with result 'exit-code'.
```

**Comment by adejanovski** [comment]
@rsaffi, I've just tried to run the released 1.4.0 jar with postgres as backend and didn't get the exception 🤔 
@michaelsembwever, I remember you fixed this somewhere. Do you have a lead?

**Comment by rsaffi** [comment]
> @rsaffi, I've just tried to run the released 1.4.0 jar with postgres as backend and didn't get the exception 

Odd, but I have double checked and nothing changed on the configuration level. 1.3.0 starts and connects successfully to Postgres. That's only happening with 1.4.0.

**Comment by mnellemann** [comment]
I also upgraded from 1.3.0 to 1.4.0 today, and experienced something similar. Reaper is configured to use a h2 database on filesystem.
```
h2:
  url: jdbc:h2:/var/lib/reaper/reaper-db.h2;MODE=PostgreSQL
  user:
  password:
```
Log output:

```
INFO   [main] i.c.ReaperApplication - initializing runner thread pool with 15 threads 
INFO   [main] i.c.ReaperApplication - initializing storage of type: h2 
INFO   [main] o.f.c.i.u.VersionPrinter - Flyway Community Edition 5.1.0 by Boxfuse 
INFO   [main] o.f.c.i.d.DatabaseFactory - Database: jdbc:h2:/var/lib/reaper/reaper-db.h2 (H2 1.4) 
INFO   [main] o.f.c.i.s.JdbcTableSchemaHistory - Repair of failed migration in Schema History table "PUBLIC"."flyway_schema_history" not necessary. No failed migration detected. 
INFO   [main] o.f.c.i.c.DbRepair - Successfully repaired schema history table "PUBLIC"."flyway_schema_history" (execution time 00:00.108s). 
INFO   [main] o.f.c.i.c.DbValidate - Successfully validated 11 migrations (execution time 00:00.046s) 
INFO   [main] o.f.c.i.c.DbMigrate - Current version of schema "PUBLIC": 11.0.0 
INFO   [main] o.f.c.i.c.DbMigrate - Schema "PUBLIC" is up to date. No migration necessary. 
ERROR  [main] o.a.t.j.p.ConnectionPool - Unable to create initial connections of pool. 
java.sql.SQLException: Unable to load class:  from ClassLoader:sun.misc.Launcher$AppClassLoader@5c647e05;ClassLoader:sun.misc.Launcher$AppClassLoader@5c647e05
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:292)
        at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:212)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:739)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:671)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:483)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131)
        at org.skife.jdbi.v2.DataSourceConnectionFactory.openConnection(DataSourceConnectionFactory.java:34)
        at org.skife.jdbi.v2.DBI.open(DBI.java:211)
        at io.cassandrareaper.storage.PostgresStorage.isStorageConnected(PostgresStorage.java:124)
        at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:343)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:174)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:80)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:99)
Caused by: java.lang.ClassNotFoundException: Unable to load class:  from ClassLoader:sun.misc.Launcher$AppClassLoader@5c647e05;ClassLoader:sun.misc.Launcher$AppClassLoader@5c647e05
        at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:56)
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:281)
        ... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: 
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:38)
        ... 20 common frames omitted
```

**Comment by michaelsembwever** [comment]
The Reaper community is treating this issue as critical. I will be taking a look at it today.

**Comment by michaelsembwever** [comment]
Oh! Memory suddenly kicked in and I remembered what this is!

You must add the `driverClass` option to the database section in the yaml file.
For example:
 - https://github.com/thelastpickle/cassandra-reaper/blob/1.4.0/src/packaging/resource/cassandra-reaper-h2.yaml#L91
 - https://github.com/thelastpickle/cassandra-reaper/blob/1.4.0/src/packaging/resource/cassandra-reaper-postgres.yaml#L91

**Comment by michaelsembwever** [comment]
Fixed via https://github.com/thelastpickle/cassandra-reaper/issues/613
