### ISSUE TITLE
1.4.1 doesn't repair Cassandra 1.2.19/2.0 anymore

### ISSUE THREAD

**Issue by rborer** [thelastpickle/cassandra-reaper#629]
Hi again,

I've just bumped reaper to version 1.4.1 and just discovered that it doesn't repair my cluster on Cassandra 1.2.19 anymore (yeah I know, pretty old version...).

Here are the logs:

```
WARN   [2019-03-18 15:09:54,207] [staging-cluster:00000000-0000-0076-0000-000000000000:00000000-0000-16ed-0000-000000000000] i.c.s.SegmentRunner - Failed to connect to a coordinator node for segment 00000000-0000-16ed-0000-00000000
0000 
java.lang.reflect.UndeclaredThrowableException: null
        at com.sun.proxy.$Proxy56.getCompactionParameters(Unknown Source)
        at io.cassandrareaper.jmx.JmxProxyImpl.getTablesForKeyspace(JmxProxyImpl.java:406)
        at io.cassandrareaper.service.RepairUnitService.getTablesToRepair(RepairUnitService.java:94)
        at io.cassandrareaper.service.SegmentRunner.runRepair(SegmentRunner.java:269)
        at io.cassandrareaper.service.SegmentRunner.run(SegmentRunner.java:143)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
        at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.management.AttributeNotFoundException: No such attribute: CompactionParameters
        at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:81)
        at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1464)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:97)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1328)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1420)
        at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:657)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
        at sun.rmi.transport.Transport$2.run(Transport.java:202)
        at sun.rmi.transport.Transport$2.run(Transport.java:199)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:198)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:567)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.access$400(TCPTransport.java:619)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:684)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:681)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:681)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
```

At a very quick glance it's coming from https://github.com/thelastpickle/cassandra-reaper/blob/1.4/src/server/src/main/java/io/cassandrareaper/jmx/JmxProxyImpl.java#L404-L407 . Seems that commit dfa792f5a9f65d0a21173701d0c87579f1a1a42f (to fix #577) introduced this regression.

I'll try to find some time to dig into it more & hopefully submit a PR. I'm anyway wondering, do you have any plan to officially support 1.2 versions or should I consider to keep a working version and not upgrade reaper without upgrading my clusters first?

**Comment by cswingler** [comment]
I just came here to report the same issue, but our clusters are all 2.0. Failing with the same exception.

**Comment by rborer** [comment]
Indeed, since like it was only added [`ColumnFamilyStoreMBean.getCompactionParameters()`](https://github.com/apache/cassandra/blob/9bb75358dfdf1b9824f9a454e70ee2c02bc64a45/src/java/org/apache/cassandra/db/ColumnFamilyStoreMBean.java#L331) method has been added in Cassandra 2.1

**Comment by michaelsembwever** [comment]
Thanks for the report @rborer .

You're correct that https://github.com/thelastpickle/cassandra-reaper/blob/1.4/src/server/src/main/java/io/cassandrareaper/jmx/JmxProxyImpl.java#L406 is at fault. It needs to be an optional call into the builder.

We should also be looking at duplicating the non-cassandra-storage integration tests to run against the different Cassandra versions we do support repairing of: https://github.com/thelastpickle/cassandra-reaper/blob/master/.travis.yml#L54-L56

Does anyone feel like tackling this?

**Comment by rborer** [comment]
I can have a look at fixing the issue first, I have a test cluster ready to try in real conditions :wink: 

I can also try to have a look at integration tests although I don't know much about travis. Would travis config be enough to increase integration tests coverage @michaelsembwever ?

**Comment by michaelsembwever** [comment]
> Would travis config be enough to increase integration tests coverage @michaelsembwever ?

Yes. Duplicating the three lines, just changing the `CASSANDRA_VERSION` value, will add the extra test runs in travis.

**Comment by michaelsembwever** [comment]
Fixed via https://github.com/thelastpickle/cassandra-reaper/pull/631
