### ISSUE TITLE
Cassandra-Reaper 1.4.0 does not start with Cassandra backend source 

### ISSUE THREAD

**Issue by pradeepsambamurthy** [thelastpickle/cassandra-reaper#634]
Reaper 1.4.0 configured with Cassandra 3.0.14 gives below exception during startup after installation.

.util.concurrent.ExecutionException: org.apache.cassandra.schema.SchemaKeyspace$MissingColumns: Columns not found in schema table for reaper_db.repair_id), defuncting connection. 
org.cognitor.cassandra.migration.MigrationException: Error during migration of script 010_table_properties.cql while executing 'ALTER TABLE repair_run  WITH caching = {'keys':'ALL', 'rows_per_partition':'5000'};'
	at org.cognitor.cassandra.migration.Database.execute(Database.java:178)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.cognitor.cassandra.migration.MigrationTask.migrate(MigrationTask.java:52)
	at io.cassandrareaper.storage.CassandraStorage.initializeAndUpgradeSchema(CassandraStorage.java:239)
	at io.cassandrareaper.storage.CassandraStorage.<init>(CassandraStorage.java:191)
	at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:329)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:174)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:80)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:99)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table repair_run
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at org.cognitor.cassandra.migration.Database.executeStatement(Database.java:186)
	at org.cognitor.cassandra.migration.Database.execute(Database.java:170)
	... 12 more
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table repair_run
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:147)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:198)
	at com.datastax.driver.core.RequestHandler.access$2600(RequestHandler.java:50)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:852)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:686)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1087)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1010)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.datastax.driver.core.InboundTrafficMeter.channelRead(InboundTrafficMeter.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:934)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:397)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

The solution for it is we need to explicitly create the repair_run table and start the reaper

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-385) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-385

**Comment by michaelsembwever** [comment]
This is odd. Maybe similar to https://github.com/thelastpickle/cassandra-reaper/issues/597 ?

**Comment by pradeepsambamurthy** [comment]
Now, after installation the repair does not work, it gives below exception which usually comes when the  schema migration did not happen currectly but it never complained about the schema migration 

ERROR  [dw-32 - PUT /repair_run/850074d0-4b4f-11e9-a289-3fda412ebf9c/state/RUNNING] i.d.j.e.LoggingExceptionMapper - Error handling a request: 6160085b1eddcbba 
com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [bigint <-> java.util.UUID]
	at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:741)
	at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:602)
	at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:582)
	at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:507)
	at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:77)
	at com.datastax.driver.core.BoundStatement.bind(BoundStatement.java:203)
	at com.datastax.driver.core.DefaultPreparedStatement.bind(DefaultPreparedStatement.java:126)
	at io.cassandrareaper.storage.CassandraStorage.getRepairRunsForUnit(CassandraStorage.java:639)
	at io.cassandrareaper.resources.RepairRunResource.isUnitAlreadyRepairing(RepairRunResource.java:512)
	at io.cassandrareaper.resources.RepairRunResource.modifyRunState(RepairRunResource.java:390)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:674)
	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)

**Comment by michaelsembwever** [comment]
`com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [bigint <-> java.util.UUID]`

This is running a version of Reaper on a older version of the schema.
The schema upgrade did not work. 

Are you able to delete the keyspace, restart Reaper so it recreates the schema, and enter in your schedules again.
I know this is a pain, but i'm not sure of many other options there is if the schema upgrade migration fails like this.
(You can look into schema, figure out where the upgrade migration failed, and try to manually `alter` fix/upgrade the schema.)

**Comment by michaelsembwever** [comment]
@pradeepsambamurthy have you had a chance to look at this again?

**Comment by pradeepsambamurthy** [comment]
I have executed schema files with a custom script and created the
schema_migration table separately then started the reaper and it works fine

**Comment by cskarby** [comment]
Hello!

Having the same problem (running reaper 3.0.0) - seems to be some race condition creating the tables?

To aid others having the same issue, here is how I resolved the situation manually: 
1. dropping the tables, creating the schema_migration table, populate it:
```
USE reaper_db;
SELECT table_name FROM system_schema.tables WHERE keyspace_name = 'reaper_db';
DROP TABLE cluster;
DROP TABLE diagnostic_event_subscription;
DROP TABLE leader;
DROP TABLE node_metrics_v1;
DROP TABLE node_metrics_v3;
DROP TABLE node_operations;
DROP TABLE percent_repaired_by_schedule;
DROP TABLE repair_run;
DROP TABLE repair_run_by_cluster;
DROP TABLE repair_run_by_cluster_v2;
DROP TABLE repair_run_by_unit;
DROP TABLE repair_schedule_by_cluster_and_keyspace;
DROP TABLE repair_schedule_v1;
DROP TABLE repair_unit_v1;
DROP TABLE running_reapers;
DROP TABLE running_repairs;
DROP TABLE schema_migration;
DROP TABLE schema_migration_leader;
DROP TABLE snapshot;
CREATE TABLE reaper_db.schema_migration (
    applied_successful boolean,
    version int,
    executed_at timestamp,
    script text,
    script_name text,
    PRIMARY KEY (applied_successful, version)
) WITH CLUSTERING ORDER BY (version ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
INSERT INTO schema_migration (version, applied_successful) VALUES (16, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (17, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (18, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (19, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (20, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (21, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (22, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (23, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (24, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (25, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (26, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (27, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (28, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (29, True);
INSERT INTO schema_migration (version, applied_successful) VALUES (30, True);
SELECT table_name FROM system_schema.tables WHERE keyspace_name = 'reaper_db';
```
2.   then manually apply all the schema migrations (in order) from https://github.com/thelastpickle/cassandra-reaper/tree/master/src/server/src/main/resources/db/cassandra

**Comment by adejanovski** [comment]
Creating the schema_migration table along with the schema_migration_leader table should be enough. The migration library we rely on uses leader election to make sure a single instance can perform a migration, but there can be some race conditions if those tables weren't created.
Failed migrations can also put the db in a state that the migration lib can't recover from.
Starting just a single instance of Reaper can be helpful to ensure migrations are applied without concurrency, and reaper can also be started in schema migration mode for that purpose as well: `java -jar ....jar schema-migration <config-file>` instead of `java -jar ...jar server <config-file>`.
