### ISSUE TITLE
LocalJmxMode Unrecognized Option

### ISSUE THREAD

**Issue by emanuele-leopardi** [thelastpickle/cassandra-reaper#643]
Hello,

for security reasons I was trying to use *localJmxMode* option , as on my cassandra cluster I only have got local access via jmx.
As stated in the documentation,
http://cassandra-reaper.io/docs/configuration/reaper_specific/
it is possibile to force local connection via jmx, but I found out that if I try to use that I get this error

``` 
io.dropwizard.configuration.ConfigurationParsingException: /etc/cassandra-reaper.yml has an error:
  * Unrecognized field at: localJmxMode
    Did you mean?:
      - cassandra
      - storageType
      - jmxAuth
      - logging
      - jmxPorts
        [28 more]

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:140)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:100)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "localJmxMode" (class io.cassandrareaper.ReaperApplicationConfiguration), not marked as ignorable (33 known properties: "purgeRecordsAfterInDays", "segmentCountPerNode", "hangingRepairTimeoutMins", "repairManagerSchedulingIntervalSeconds", "incrementalRepair", "cassandra", "h2", "enableDynamicSeedList", "repairParallelism", "storageType", "repairThreadCount", "accessControl", "scheduleDaysBetween", "segmentCount", "jmxAuth", "logging", "autoScheduling", "repairIntensity", "useAddressTranslator", "jmxConnectionTimeoutInSeconds", "blacklistTwcsTables", "numberOfRunsToKeepPerUnit", "datacenterAvailability", "maxPendingCompactions", "jmxPorts", "enableCrossOrigin", "activateQueryLogger", "repairRunThreadCount", "jmxCredentials", "postgres", "database", "server", "metrics"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.cassandrareaper.ReaperApplicationConfiguration["localJmxMode"])
```
So it seems it's not implemented on version 1.4.1.

Is this a deprecated feature or is still something tha'ts planned to be done?

Thank you!

**Comment by LinPower** [comment]
I have the same confused before. I found the commit below. I think this feature is removed.
https://github.com/thelastpickle/cassandra-reaper/commit/e5dbedff51f29073c73fb852994400e702e6635d

**Comment by michaelsembwever** [comment]
That's correct. It is being reimplemented as `side-car` mode in https://github.com/thelastpickle/cassandra-reaper/pull/622
We should see that arrive in `1.5`
