### ISSUE TITLE
Can't login through spreaper

### ISSUE THREAD

**Issue by eddyaman** [thelastpickle/cassandra-reaper#648]
I am trying to login into reaper using 
`spreaper login admin`
and after I put the password `admin`. it returns:
```
root@d0b68c8d22a0:/var/log/cassandra-reaper# spreaper login admin
Password:
# Logging in...
Traceback (most recent call last):
  File "/usr/local/bin/spreaper", line 883, in <module>
    ReaperCLI()
  File "/usr/local/bin/spreaper", line 413, in __init__
    getattr(self, command)()
  File "/usr/local/bin/spreaper", line 477, in login
    payload=payload)
  File "/usr/local/bin/spreaper", line 115, in postFormData
    return self._http_req("POST_FORM", the_url, params=payload)
  File "/usr/local/bin/spreaper", line 81, in _http_req
    r = requests.post(the_url, data=params)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(99, 'Cannot assign requested address'))
```

Can you please help me what is wrong here?

**Comment by michaelsembwever** [comment]
The output you should see is…
```
$ src/packaging/bin/spreaper login admin
Password:
# Logging in...
You are now authenticated to Reaper.
# JWT saved
```
I can confirm this works for me (against `master`).

Googling the last line 
```
requests.exceptions.ConnectionError: ('Connection aborted.', error(99, 'Cannot assign requested address'))
```
indicates this is a problem with too many requests.

- https://stackoverflow.com/questions/11981933/python-urllib2-cannot-assign-requested-address?lq=1
- https://stackoverflow.com/questions/11190595/repeated-post-request-is-causing-error-socket-error-99-cannot-assign-reques?rq=1
- https://stackoverflow.com/questions/30943866/requests-cannot-assign-requested-address-out-of-ports

**Comment by adejanovski** [comment]
Closing due to I inactivity. Feel free to reopen if you're still affected by this issue.
