### ISSUE TITLE
`BasicSteps.we_can_collect_the_tpstats_from_the_seed_node()` fails often in flapping integration tests

### ISSUE THREAD

**Issue by michaelsembwever** [thelastpickle/cassandra-reaper#659]
I regularly see this failure in the flapping integration tests.

I see also see waiting for segments steps failing because metrics from nodes in the same dc are not available, which could be related to this.

```
  Background:                                                                               # io.cassandrareaper.acceptance/integration_reaper_functionality.feature:18
    Given cluster seed host "127.0.0.1@test" points to cluster with name "test"             # BasicSteps.cluster_seed_host_points_to_cluster_with_name(String,String)
    And cluster "test" has keyspace "booya" with tables "booya1, booya2"                    # BasicSteps.ccm_cluster_has_keyspace_with_tables(String,String,String)
    And cluster "test" has keyspace "booya" with tables "booya_twcs"                        # BasicSteps.ccm_cluster_has_keyspace_with_tables(String,String,String)
    And cluster "test" has keyspace "test_keyspace" with tables "test_table1, test_table2"  # BasicSteps.ccm_cluster_has_keyspace_with_tables(String,String,String)
    And cluster "test" has keyspace "test_keyspace2" with tables "test_table1, test_table2" # BasicSteps.ccm_cluster_has_keyspace_with_tables(String,String,String)
    And cluster "test" has keyspace "test_keyspace3" with tables "test_table1, test_table2" # BasicSteps.ccm_cluster_has_keyspace_with_tables(String,String,String)
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /cluster/ HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 5
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /cluster/ HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 3
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /cluster/ HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 8
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "POST /cluster?seedHost=127.0.0.1%40test&jmxPort=7100 HTTP/1.1" 201 0 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 15
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "POST /cluster?seedHost=127.0.0.1%40test&jmxPort=7100 HTTP/1.1" 201 0 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 21
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "POST /cluster?seedHost=127.0.0.1%40test&jmxPort=7100 HTTP/1.1" 201 0 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 21
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /cluster/test HTTP/1.1" 200 1125 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 11
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /cluster/test HTTP/1.1" 200 1125 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 11
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /cluster/test HTTP/1.1" 200 1125 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 19
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /cluster/test HTTP/1.1" 200 1125 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 11
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /cluster/test HTTP/1.1" 200 1125 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 10
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /cluster/test HTTP/1.1" 200 1125 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 11
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /cluster/test HTTP/1.1" 200 1125 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 13
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /cluster/test HTTP/1.1" 200 1125 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 8
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /cluster/test HTTP/1.1" 200 1125 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 8
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /node/tokens/test/127.0.0.1 HTTP/1.1" 200 89 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 10
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /node/tokens/test/127.0.0.1 HTTP/1.1" 200 89 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 10
127.0.0.1 - - [11/May/2019:03:41:29 +0000] "GET /node/tokens/test/127.0.0.1 HTTP/1.1" 200 89 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 10
127.0.0.1 - - [11/May/2019:03:41:30 +0000] "GET /repair_schedule/cluster/test HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:30 +0000] "GET /repair_schedule/cluster/test HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 5
127.0.0.1 - - [11/May/2019:03:41:30 +0000] "GET /repair_schedule/cluster/test HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 5
127.0.0.1 - - [11/May/2019:03:41:30 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 5
127.0.0.1 - - [11/May/2019:03:41:30 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:30 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 5
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 3
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 3
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 5
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 5
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 3
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 5
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 3
127.0.0.1 - - [11/May/2019:03:41:31 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 3
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 3
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
INFO  [2019-05-11 03:41:32,166] io.cassandrareaper.ReaperApplication: ReaperApplication constructor called with custom AppContext
INFO  [2019-05-11 03:41:32,167] io.cassandrareaper.ReaperApplication: default ReaperApplication constructor called
INFO  [2019-05-11 03:41:32,197] io.cassandrareaper.SimpleReaperClient: calling (GET) Reaper in resource: http://localhost:38843/node/tpstats/test/127.0.0.1
INFO  [2019-05-11 03:41:32,199] io.cassandrareaper.SimpleReaperClient: calling (GET) Reaper in resource: http://localhost:43421/node/tpstats/test/127.0.0.1
INFO  [2019-05-11 03:41:32,199] io.cassandrareaper.SimpleReaperClient: calling (GET) Reaper in resource: http://localhost:43735/node/tpstats/test/127.0.0.1
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 3
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
WARN  [2019-05-11 03:41:32,262] com.datastax.driver.core.CodecRegistry: Ignoring codec DateTimeCodec [timestamp <-> org.joda.time.DateTime] because it collides with previously registered codec DateTimeCodec [timestamp <-> org.joda.time.DateTime]
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 3
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 3
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4
127.0.0.1 - - [11/May/2019:03:41:32 +0000] "GET /node/tpstats/test/127.0.0.1 HTTP/1.1" 200 2 "-" "Jersey/2.25.1 (HttpUrlConnection 1.8.0_181)" 4

  Scenario Outline: Create a cluster and a scheduled repair run and delete them                      # io.cassandrareaper.acceptance/integration_reaper_functionality.feature:62
    Given that reaper  is running                                                                    # BasicSteps.start_reaper(String)
    And that we are going to use "127.0.0.1@test" as cluster seed host                               # BasicSteps.that_we_are_going_to_use_as_cluster_seed_host(String)
    And reaper has no cluster in storage                                                             # BasicSteps.reaper_has_no_cluster_in_storage()
    When an add-cluster request is made to reaper                                                    # BasicSteps.an_add_cluster_request_is_made_to_reaper()
    Then reaper has the last added cluster in storage                                                # BasicSteps.reaper_has_the_last_added_cluster_in_storage()
    And the seed node has vnodes                                                                     # BasicSteps.the_seed_node_has_vnodes()
    And reaper has 0 scheduled repairs for the last added cluster                                    # BasicSteps.reaper_has_scheduled_repairs_for_the_last_added_cluster(int)
    And we can collect the tpstats from the seed node                                                # BasicSteps.we_can_collect_the_tpstats_from_the_seed_node()
      org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.cassandrareaper.acceptance.BasicSteps that uses io.cassandrareaper.acceptance.ReaperTestJettyRunner, io.cassandrareaper.acceptance.ReaperTestJettyRunnerjava.util.concurrent.atomic.AtomicBoolean was not fulfilled within 2 seconds.
      	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:145)
      	at org.awaitility.core.CallableCondition.await(CallableCondition.java:79)
      	at org.awaitility.core.CallableCondition.await(CallableCondition.java:27)
      	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:902)
      	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:860)
      	at io.cassandrareaper.acceptance.BasicSteps.lambda$we_can_collect_the_tpstats_from_the_seed_node$63(BasicSteps.java:1573)
      	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
      	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
      	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
      	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
      	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
      	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
      	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
      	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
      	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
      	at ✽.And we can collect the tpstats from the seed node(io.cassandrareaper.acceptance/integration_reaper_functionality.feature:49) 
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-393) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-393

**Comment by adejanovski** [comment]
This was fixed a while ago.
Closing the ticket.
