### ISSUE TITLE
Have some issue to upgrade `cassandra-reaper` v1.4.2 brew

### ISSUE THREAD

**Issue by chenrui333** [thelastpickle/cassandra-reaper#660]
relates to https://github.com/Homebrew/homebrew-core/pull/39691

I am test the brew installation against both Oracle JDK jdk1.8.0_152 and Oracle JDK 1.8.0_211. But failed both, I wonder if someone can take a look about how to fix the `javax.xml.bind.DatatypeConverter` reference issue.

Thanks!

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-394) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-394

**Comment by chenrui333** [comment]
Anyone?

**Comment by adejanovski** [comment]
Hi, we've removed 1.4.2 as it contained some issues that could prevent Reaper from starting up after the upgrade.

`1.4.3` was released and should be available in Homebrew.

Let us know if you can install it.

**Comment by chenrui333** [comment]
@adejanovski Thanks for your reply. I have tried with 1.4.3, but having the same issue.
```
14:14:53 19:14:45,445 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - openFile(/var/log/cassandra-reaper/reaper.log,true) call failed. java.io.FileNotFoundException: /var/log/cassandra-reaper/reaper.log (No such file or directory)
14:14:53 	at java.io.FileNotFoundException: /var/log/cassandra-reaper/reaper.log (No such file or directory)
14:14:53 	at 	at java.base/java.io.FileOutputStream.open0(Native Method)
14:14:53 	at 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:292)
14:14:53 	at 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
14:14:53 	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
14:14:53 	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
14:14:53 	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
14:14:53 	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
14:14:53 	at 	at io.dropwizard.logging.AbstractOutputStreamAppenderFactory.build(AbstractOutputStreamAppenderFactory.java:30)
14:14:53 	at 	at io.dropwizard.logging.DefaultLoggingFactory.configure(DefaultLoggingFactory.java:143)
14:14:53 	at 	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:83)
14:14:53 	at 	at io.dropwizard.cli.Cli.run(Cli.java:78)
14:14:53 	at 	at io.dropwizard.Application.run(Application.java:93)
14:14:53 	at 	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:100)
14:14:53 19:14:45,445 |-INFO in ch.qos.logback.classic.AsyncAppender[async-file-appender] - Attaching appender named [file-appender] to AsyncAppender.
14:14:53 19:14:45,445 |-INFO in ch.qos.logback.classic.AsyncAppender[async-file-appender] - Setting discardingThreshold to 51
14:14:53 
14:14:53 java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
14:14:53 	at io.cassandrareaper.resources.auth.ShiroJwtProvider.getSigningKey(ShiroJwtProvider.java:63)
14:14:53 	at io.cassandrareaper.resources.auth.ShiroJwtProvider.<init>(ShiroJwtProvider.java:44)
14:14:53 	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:249)
14:14:53 	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:81)
14:14:53 	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
14:14:53 	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
14:14:53 	at io.dropwizard.cli.Cli.run(Cli.java:78)
14:14:53 	at io.dropwizard.Application.run(Application.java:93)
14:14:53 	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:100)
14:14:53 Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
14:14:53 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
14:14:53 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
14:14:53 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
14:14:53 	... 9 more
14:14:53 ==> curl -Im3 -o- http://localhost:8080/webui/
```

**Comment by mbarouski** [comment]
Have the same issue with 1.4.4 version, JDK 11.
Downloaded `cassandra-reaper` from http://cassandra-reaper.io/docs/download/.
https://stackoverflow.com/a/43574427/6575674 says that `JAXB API` is removed from JDK 11 and gives a solution for JDK 11.

**UPDATED:** Downloaded the following jars:
```
"javax.xml.bind:jaxb-api:2.2.11"
"com.sun.xml.bind:jaxb-core:2.2.11"
"com.sun.xml.bind:jaxb-impl:2.2.11"
"javax.activation:activation:1.1.1"
```
and started reaper with:
`java -cp "./target/*:./jars/*" io.cassandrareaper.ReaperApplication server ../resource/cassandra-reaper.yaml`

**Comment by jmooo** [comment]
Ran into this same error, decided it was easier to downgrade from jdk11 to `openjdk-8-jdk` on Ubuntu 18.04

**Comment by adejanovski** [comment]
JDK11 is supported since Reaper 3.1.0.
