### ISSUE TITLE
Reaper startup issue after first install in Centos

### ISSUE THREAD

**Issue by TrueBlueDrive** [thelastpickle/cassandra-reaper#788]
I see below issue post installation and initial cassandra config. Reaper is failing to start with below error.

any pointers or suggestion is welcome.
cassandra-reaper.err

find: './boot/efi': Permission denied
find: './boot/grub2': Permission denied
find: './proc/tty/driver': Permission denied
find: './proc/1/task/1/fd': Permission denied
find: './proc/1/task/1/fdinfo': Permission denied
find: './proc/1/task/1/ns': Permission denied
find: './proc/1/fd': Permission denied
find: './proc/1/map_files': Permission denied
find: './proc/1/fdinfo': Permission denied
find: './proc/1/ns': Permission denied
find: './proc/2/task/2/fd': Permission denied
find: './proc/2/task/2/fdinfo': Permission denied
find: './proc/2/task/2/ns': Permission denied
find: './proc/2/fd': Permission denied
find: './proc/2/map_files': Permission denied
find: './proc/2/fdinfo': Permission denied
find: './proc/2/ns': Permission denied
find: './proc/3/task/3/fd': Permission denied
find: './proc/3/task/3/fdinfo': Permission denied
find: './proc/3/task/3/ns': Permission denied
find: './proc/3/fd': Permission denied
find: './proc/3/map_files': Permission denied
find: './proc/3/fdinfo': Permission denied
find: './proc/3/ns': Permission denied
find: './proc/5/task/5/fd': Permission denied
find: './proc/5/task/5/fdinfo': Permission denied
find: './proc/5/task/5/ns': Permission denied
find: './proc/5/fd': Permission denied
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at com.datastax.driver.core.InboundTrafficMeter.channelRead(InboundTrafficMeter.java:38)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:934)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:397)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency LOCAL_ONE (1 required but only 0 alive)
        at com.datastax.driver.core.Responses$Error$1.decode(Responses.java:50)
        at com.datastax.driver.core.Responses$Error$1.decode(Responses.java:37)
        at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:289)
        at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:269)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        ... 23 more
Thanks in Advance,

**Comment by adejanovski** [comment]
Your replication settings of the reaper_db keyspace might not be correctly configured. Do you have a multi dc cluster, and if so, are you using NetworkTopologyStrategy for the reaper_db keyspace?

**Comment by adejanovski** [comment]
I'll close this issue for now. Feel free to reopen if you're still running into this.
