### ISSUE TITLE
Failed parsing cluster information from the database entry

### ISSUE THREAD

**Issue by Jabbl** [thelastpickle/cassandra-reaper#796]
Upgraded Reaper from 1.3.0 (helm-released version) to 1.4.8 because of some issues regarding hosts complaining that a repair is already in progress.

However, after the update, I get these exceptions:

```
INFO [2019-11-19 10:07:41,750] [ReaperApplication-scheduler] i.c.s.RepairManager - Restarting run id 7feccef0-09e8-11ea-ab11-95940b8565cd that has no runner
INFO [2019-11-19 10:07:41,751] [ReaperApplication-scheduler] i.c.s.RepairManager - Starting a run with id #7feccef0-09e8-11ea-ab11-95940b8565cd with current state 'RUNNING'
INFO [2019-11-19 10:07:41,752] [ReaperApplication-scheduler] i.c.s.RepairManager - re-trigger a running run after restart, with id 7feccef0-09e8-11ea-ab11-95940b8565cd
INFO [2019-11-19 10:07:41,753] [ReaperApplication-scheduler] i.c.s.RepairManager - scheduling repair for repair run #7feccef0-09e8-11ea-ab11-95940b8565cd
ERROR [2019-11-19 10:07:41,764] [ReaperApplication-scheduler] i.c.s.CassandraStorage - Failed parsing cluster information from the database entry
java.lang.IllegalArgumentException: properties is not a column defined in this metadata
at com.datastax.driver.core.ColumnDefinitions.getAllIdx(ColumnDefinitions.java:274)
at com.datastax.driver.core.ColumnDefinitions.getFirstIdx(ColumnDefinitions.java:280)
at com.datastax.driver.core.ArrayBackedRow.getIndexOf(ArrayBackedRow.java:81)
at com.datastax.driver.core.AbstractGettableData.getString(AbstractGettableData.java:159)
at io.cassandrareaper.storage.CassandraStorage.getCluster(CassandraStorage.java:479)
at io.cassandrareaper.service.RepairRunner.<init>(RepairRunner.java:77)
at io.cassandrareaper.service.RepairManager.startRunner(RepairManager.java:331)
at io.cassandrareaper.service.RepairManager.startRepairRun(RepairManager.java:297)
at io.cassandrareaper.service.RepairManager.resumeUnkownRunningRepairRuns(RepairManager.java:135)
at io.cassandrareaper.service.RepairManager.resumeRunningRepairRuns(RepairManager.java:109)
at io.cassandrareaper.ReaperApplication.lambda$scheduleRepairManager$0(ReaperApplication.java:293)
at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
WARN [2019-11-19 10:07:41,770] [ReaperApplication-scheduler] i.c.s.RepairManager - Failed to schedule repair for repair run #7feccef0-09e8-11ea-ab11-95940b8565cd
io.cassandrareaper.ReaperException: java.lang.IllegalArgumentException: properties is not a column defined in this metadata
at io.cassandrareaper.storage.CassandraStorage.getCluster(CassandraStorage.java:492)
at io.cassandrareaper.service.RepairRunner.<init>(RepairRunner.java:77)
at io.cassandrareaper.service.RepairManager.startRunner(RepairManager.java:331)
at io.cassandrareaper.service.RepairManager.startRepairRun(RepairManager.java:297)
at io.cassandrareaper.service.RepairManager.resumeUnkownRunningRepairRuns(RepairManager.java:135)
at io.cassandrareaper.service.RepairManager.resumeRunningRepairRuns(RepairManager.java:109)
at io.cassandrareaper.ReaperApplication.lambda$scheduleRepairManager$0(ReaperApplication.java:293)
at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: properties is not a column defined in this metadata
at com.datastax.driver.core.ColumnDefinitions.getAllIdx(ColumnDefinitions.java:274)
at com.datastax.driver.core.ColumnDefinitions.getFirstIdx(ColumnDefinitions.java:280)
at com.datastax.driver.core.ArrayBackedRow.getIndexOf(ArrayBackedRow.java:81)
at com.datastax.driver.core.AbstractGettableData.getString(AbstractGettableData.java:159)
at io.cassandrareaper.storage.CassandraStorage.getCluster(CassandraStorage.java:479)
... 14 common frames omitted
```

Additionally, the UI seems unable to load information about the cluster

How do I fix it?

**Comment by adejanovski** [comment]
your schema upgrade didn't go as planned, or hasn't propagated to all the nodes it seems. The `reaper_db.cluster` table now has a `properties` column that doesn't seem to be found.

Check `nodetool describecluster` to see if all nodes in the cluster have the same schema version. If so, check the `reaper_db.cluster` table to see if it has a `properties` column, and then restart all your Reaper instances to see if they get the right schema.

**Comment by Jabbl** [comment]
All nodes in the cluster have the same schema version, but the `properties`-column in `reaper_db.cluster`  says `null`, which I presume causes some problems...

**Comment by Jabbl** [comment]
Nevermind, it seems simply restarting Reaper caused it to update it's schema and continue running.
