### ISSUE TITLE
Can't get cassandra backend with auth working in docker

### ISSUE THREAD

**Issue by piotrrybicki** [thelastpickle/cassandra-reaper#810]
When I specify ENV vars for docker:

```
     REAPER_STORAGE_TYPE: "cassandra"
      REAPER_CASS_CLUSTER_NAME: "live"
      REAPER_CASS_AUTH_ENABLED: "true"
      REAPER_CASS_AUTH_USERNAME: "XXX"
      REAPER_CASS_AUTH_PASSWORD: "YYY"
      REAPER_CASS_CONTACT_POINTS: "[\"a.com\",\"b.com\",\"c.com\"]"
      REAPER_CASS_KEYSPACE: "reaper_db"
```
I get this error:

```
+ /usr/local/bin/configure-persistence.sh
/usr/local/bin/configure-persistence.sh: line 21: can't create /etc/cassandra-reaper.yml: Interrupted system call
+ /usr/local/bin/configure-webui-authentication.sh
+ /usr/local/bin/configure-metrics.sh
+ exec java -jar /usr/local/lib/cassandra-reaper.jar server /etc/cassandra-reaper.yml
io.dropwizard.configuration.ConfigurationParsingException: /etc/cassandra-reaper.yml has an error:
  * Unrecognized field at: server.authProvider
    Did you mean?:
      - user
      - uid
      - maxThreads
      - gid
      - minThreads
        [22 more]

        at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:140)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:110)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "authProvider" (class io.dropwizard.server.DefaultServerFactory), not marked as ignorable (27 known properties: "registerDefaultExceptionMappers", "gid", "idleThreadTimeout", "applicationContextPath", "detailedJsonProcessingExceptionMapper", "user", "uid", "nofileHardLimit", "adminMaxThreads", "gzip", "maxQueuedRequests", "umask", "shutdownGracePeriod", "maxThreads", "adminMinThreads", "rootPath", "allowedMethods", "enableThreadNameFilter", "nofileSoftLimit", "adminConnectors", "applicationConnectors", "minThreads", "serverPush", "group", "startsAsRoot", "requestLog", "adminContextPath"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.cassandrareaper.ReaperApplicationConfiguration["server"]->io.dropwizard.server.DefaultServerFactory["authProvider"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189)
        at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:120)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:136)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:252)
        at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:127)
        ... 6 more
```

Starting container without specifing storage type, works as expected (in-memory storage)

image: "thelastpickle/cassandra-reaper:2.0.0"
C* : 3.11.5

image 1.4.8 works as expected

Best regards
Piotr Rybicki

**Comment by uttamkasundara** [comment]
I am facing same issue. 
I have tried with 1.4.8 on the ubuntu service installation working fine. But the same version docker image not working. Getting No Host Available.

**Comment by adejanovski** [comment]
This should be fixed with the latest 2.0.1. 
The `interrupted system call` error should be gone and the yaml file should get configured properly.

**Comment by piotrrybicki** [comment]
@uttamkasundara , I believe You are facing different issue. Perhaps not all docker ENV vars are not set?

**Comment by piotrrybicki** [comment]
2.0.1 Fixes my issue. Thanks!
