### ISSUE TITLE
Persistent Cassandra storage, username and password

### ISSUE THREAD

**Issue by shahriar52** [thelastpickle/cassandra-reaper#83]
If I want to use Cassandra itself as a persistent storage provider of Cassandra-reaper and I have set the different password of default user ‘cassandra’, how can I specify those into the resource/cassandra-reaper.yaml file. Looks like it only works for default Cassandra username/password (cassandra/cassandra).

**Comment by adejanovski** [comment]
Hi @shahriar52 , 

you can specify the username/password combination like done in [this example](https://github.com/composable-systems/dropwizard-cassandra/blob/master/src/test/resources/smoke/auth/authProvider-plainText.yml).

You may have a problem if you're using a release of Reaper that uses the dropwizard-cassandra module v4.0.0 and dropwizard 0.7.x.

The latest master contains the upgrade to Dropwizard 1.1.0 which should allow to specify all of dropwizard-cassandra configuration properties.

Let me know how it goes.

**Comment by shahriar52** [comment]
Hi Alex, @adejanovski

Thanks a lot! That works with Cassandra storage.
But I have got a minor error,

WARN   [2017-04-27 07:50:46,394] [main] c.d.d.c.NettyUtil - Found Netty's native epoll transport in the classpath, but epoll is not available. Using NIO instead.
java.lang.UnsatisfiedLinkError: /tmp/libnetty-transport-native-epoll3242711215409834879.so: /tmp/libnetty-transport-native-epoll3242711215409834879.so: failed to map segment from shared object: Operation not permitted
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:214)
        at io.netty.channel.epoll.Native.<clinit>(Native.java:46)
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:30)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.datastax.driver.core.NettyUtil.<clinit>(NettyUtil.java:68)
        at com.datastax.driver.core.NettyOptions.eventLoopGroup(NettyOptions.java:96)
        at com.datastax.driver.core.Connection$Factory.<init>(Connection.java:713)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1381)
        at com.datastax.driver.core.Cluster.init(Cluster.java:163)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:334)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:309)
        at com.datastax.driver.core.Cluster.connect(Cluster.java:251)
        at systems.composable.dropwizard.cassandra.CassandraHealthCheck.<init>(CassandraHealthCheck.java:42)
        at systems.composable.dropwizard.cassandra.CassandraFactory.build(CassandraFactory.java:484)
        at systems.composable.dropwizard.cassandra.CassandraFactory.build(CassandraFactory.java:428)
        at com.spotify.reaper.storage.CassandraStorage.<init>(CassandraStorage.java:89)
        at com.spotify.reaper.ReaperApplication.initializeStorage(ReaperApplication.java:191)
        at com.spotify.reaper.ReaperApplication.run(ReaperApplication.java:122)
        at com.spotify.reaper.ReaperApplication.run(ReaperApplication.java:62)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:74)
        at io.dropwizard.Application.run(Application.java:89)
        at com.spotify.reaper.ReaperApplication.main(ReaperApplication.java:82)


This is because I have noexec mount option set for /tmp due to security reason. If you could tell me where to change the /tmp directory option, that would be great.

**Comment by adejanovski** [comment]
I actually have no clue :) sorry.

Maybe you can check that with the Datastax java driver team of Stuart who maintains dropwizard-cassandra.
