### ISSUE TITLE
Clear install cassandra-reaper 2.0.2

### ISSUE THREAD

**Issue by therb1** [thelastpickle/cassandra-reaper#843]
When i install cassandra-reaper over version 1.4.8 all changes going right.
When i delete keyspace and create new clear keyspace i have this error.
i try recreare keyspace 8-10 times in row and error still here.

```
Jan 27 18:00:36 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:00:36,863] [main] i.c.s.CassandraStorage - Customization of cassandra's re
try policy is not supported and will be overridden
Jan 27 18:00:37 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:00:37,125] [main] c.d.d.c.p.DCAwareRoundRobinPolicy - Some contact points
don't match local data center. Local DC = ds. Non-conforming contact points: /10.219.139.153:9042 (m1),/10.219.139.152:9042 (m1),/10.219.139.154:9042 (m1)
Jan 27 18:00:37 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:00:37,451] [main] c.d.d.c.CodecRegistry - Ignoring codec DateTimeCodec [ti
mestamp <-> org.joda.time.DateTime] because it collides with previously registered codec DateTimeCodec [timestamp <-> org.joda.time.DateTime]
Jan 27 18:00:38 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:00:38,065] [main] i.c.s.CassandraStorage - Starting db migration from 0 to
 23…
Jan 27 18:00:38 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:00:38,392] [common-transit-cas-worker-1] c.d.d.c.Cluster - Re-preparing al
ready prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='insert into schema_migration(applied_successful, version,
 script_name, script, executed_at) values(?, ?, ?, ?, ?)'
Jan 27 18:00:38 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:00:38,400] [common-transit-cas-worker-0] c.d.d.c.Cluster - Re-preparing al
ready prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='INSERT INTO schema_migration_leader (keyspace_name, leade
r, took_lead_at, leader_hostname) VALUES (?, ?, dateOf(now()), ?) IF NOT EXISTS USING TTL 300'
Jan 27 18:00:38 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:00:38,408] [common-transit-cas-worker-1] c.d.d.c.Cluster - Re-preparing al
ready prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='DELETE FROM schema_migration_leader where keyspace_name =
 ? IF leader = ?'
Jan 27 18:00:42 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:00:42,639] [common-transit-cas-nio-worker-2] c.d.d.c.RequestHandler - /10.
220.10.24:9042 replied with server error (java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (
found 179ee770-4115-11ea-a642-4b614550896f; expected 10734590-4115-11ea-a479-69e9a01cebc0)), defuncting connection.
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]: ERROR  [2020-01-27 18:00:55,105] [main] i.c.ReaperApplication - Storage is not ready yet, trying
 again to connect shortly...
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]: org.cognitor.cassandra.migration.MigrationException: Error during migration of script 016_init_r
eaper_db.cql while executing 'CREATE TABLE IF NOT EXISTS leader (    leader_id timeuuid PRIMARY KEY,    last_heartbeat timestamp,    reaper_instance_host text,    reaper_instance_id uuid) WITH b
loom_filter_fp_chance = 0.1    AND caching = {'keys':'ALL', 'rows_per_partition':'NONE'}    AND compaction = {'class': 'org.apache.cassandra.db.compaction.LeveledCompactionStrategy'}    AND defa
ult_time_to_live = 600    AND gc_grace_seconds = 600;'
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at org.cognitor.cassandra.migration.Database.execute(Database.java:269)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at java.util.Collections$SingletonList.forEach(Collections.java:4822)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at org.cognitor.cassandra.migration.MigrationTask.migrate(MigrationTask.java:68)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.storage.CassandraStorage.migrate(CassandraStorage.java:303)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.storage.CassandraStorage.initializeAndUpgradeSchema(CassandraStora
ge.java:268)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.storage.CassandraStorage.<init>(CassandraStorage.java:227)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:439)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.ReaperApplication.tryInitializeStorage(ReaperApplication.java:310)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:172)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:91)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at io.dropwizard.cli.Cli.run(Cli.java:78)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at io.dropwizard.Application.run(Application.java:93)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:110)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]: Caused by: org.cognitor.cassandra.migration.MigrationException: Schema agreement could not be re
ached. You might consider increasing 'maxSchemaAgreementWaitSeconds'.
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at org.cognitor.cassandra.migration.Database.executeStatement(Database.java:281)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         at org.cognitor.cassandra.migration.Database.execute(Database.java:261)
Jan 27 18:00:55 servername.domain.name cassandra-reaper[7911]:         ... 14 common frames omitted
Jan 27 18:01:05 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:01:05,106] [main] i.c.s.CassandraStorage - Customization of cassandra's re
try policy is not supported and will be overridden
Jan 27 18:01:05 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:01:05,344] [main] c.d.d.c.p.DCAwareRoundRobinPolicy - Some contact points
don't match local data center. Local DC = ds. Non-conforming contact points: /10.219.139.153:9042 (m1),/10.219.139.152:9042 (m1),/10.219.139.154:9042 (m1)
Jan 27 18:01:05 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:01:05,557] [main] c.d.d.c.CodecRegistry - Ignoring codec DateTimeCodec [ti
mestamp <-> org.joda.time.DateTime] because it collides with previously registered codec DateTimeCodec [timestamp <-> org.joda.time.DateTime]
Jan 27 18:01:06 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:01:06,031] [main] i.c.s.CassandraStorage - Starting db migration from 0 to
 23…
Jan 27 18:01:06 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:01:06,420] [common-transit-cas-worker-1] c.d.d.c.Cluster - Re-preparing al
ready prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='insert into schema_migration(applied_successful, version,
 script_name, script, executed_at) values(?, ?, ?, ?, ?)'
Jan 27 18:01:06 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:01:06,428] [common-transit-cas-worker-0] c.d.d.c.Cluster - Re-preparing al
ready prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='INSERT INTO schema_migration_leader (keyspace_name, leade
r, took_lead_at, leader_hostname) VALUES (?, ?, dateOf(now()), ?) IF NOT EXISTS USING TTL 300'
Jan 27 18:01:06 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:01:06,432] [common-transit-cas-worker-1] c.d.d.c.Cluster - Re-preparing al
ready prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='DELETE FROM schema_migration_leader where keyspace_name =
 ? IF leader = ?'
Jan 27 18:01:06 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:01:06,958] [common-transit-cas-worker-0] c.d.d.c.Cluster - Re-preparing al
ready prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='insert into schema_migration(applied_successful, version,
 script_name, script, executed_at) values(?, ?, ?, ?, ?)'
Jan 27 18:01:06 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:01:06,961] [common-transit-cas-worker-1] c.d.d.c.Cluster - Re-preparing al
ready prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='INSERT INTO schema_migration_leader (keyspace_name, leade
r, took_lead_at, leader_hostname) VALUES (?, ?, dateOf(now()), ?) IF NOT EXISTS USING TTL 300'
Jan 27 18:01:06 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:01:06,968] [common-transit-cas-worker-0] c.d.d.c.Cluster - Re-preparing al
ready prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='DELETE FROM schema_migration_leader where keyspace_name =
 ? IF leader = ?'
Jan 27 18:01:07 servername.domain.name cassandra-reaper[7911]: WARN   [2020-01-27 18:01:07,750] [common-transit-cas-nio-worker-0] c.d.d.c.RequestHandler - /10.
220.10.24:9042 replied with server error (java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (
found ca12a680-4115-11ea-a479-69e9a01cebc0; expected c79aefc0-4115-11ea-a30c-b50a6f0c1461)), defuncting connection.
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]: ERROR  [2020-01-27 18:03:07,911] [main] i.c.ReaperApplication - Storage is not ready yet, trying
 again to connect shortly...
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]: org.cognitor.cassandra.migration.MigrationException: Error during migration of script 017_add_cu
stom_jmx_port.cql while executing 'ALTER TABLE cluster ADD properties text;'
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at org.cognitor.cassandra.migration.Database.execute(Database.java:269)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at java.util.Collections$SingletonList.forEach(Collections.java:4822)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at org.cognitor.cassandra.migration.MigrationTask.migrate(MigrationTask.java:68)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.storage.CassandraStorage.migrate(CassandraStorage.java:303)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.storage.CassandraStorage.initializeAndUpgradeSchema(CassandraStora
ge.java:268)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.storage.CassandraStorage.<init>(CassandraStorage.java:227)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:439)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.ReaperApplication.tryInitializeStorage(ReaperApplication.java:310)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:172)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:91)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.dropwizard.cli.Cli.run(Cli.java:78)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.dropwizard.Application.run(Application.java:93)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:110)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]: Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Invalid column name proper
ties because it conflicts with an existing column
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.
java:49)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFu
ture.java:293)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at org.cognitor.cassandra.migration.Database.executeStatement(Database.java:277)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at org.cognitor.cassandra.migration.Database.execute(Database.java:261)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         ... 14 common frames omitted
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]: Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Invalid column name proper
ties because it conflicts with an existing column
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at com.datastax.driver.core.Responses$Error.asException(Responses.java:181)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:215
)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:228)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at com.datastax.driver.core.RequestHandler.access$2600(RequestHandler.java:62)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHa
ndler.java:1005)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.jav
a:808)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1233)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1151)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.
java:105)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandl
erContext.java:356)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandl
erContext.java:342)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandler
Context.java:335)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandl
erContext.java:356)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandl
erContext.java:342)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandler
Context.java:335)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.ja
va:102)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandl
erContext.java:356)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandl
erContext.java:342)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandler
Context.java:335)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java
:312)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286
)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandl
erContext.java:356)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandl
erContext.java:342)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandler
Context.java:335)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipelin
e.java:1304)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandl
erContext.java:356)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandl
erContext.java:342)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:9
21)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel
.java:135)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.ja
va:131)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Jan 27 18:03:07 servername.domain.name cassandra-reaper[7911]:         at java.lang.Thread.run(Thread.java:748)

```

**Comment by adejanovski** [comment]
Hi @therb1,

the above message shows that you had a schema disagreement in Cassandra : `Column family ID mismatch (found 179ee770-4115-11ea-a642-4b614550896f; expected 10734590-4115-11ea-a479-69e9a01cebc0)), defuncting connection.` 

In such a situation, you have to do a rolling restart of the cluster to get back to a consistent schema across all nodes.

**Comment by shaotingcheng** [comment]
I have the same issue even when all schema are aligned. 
Because the migration script didn't wait enough time for the schema agreement. When it retries again, the table has been created so it will encounter the exception "Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Invalid column name proper
ties because it conflicts with an existing column"
