### ISSUE TITLE
Error When Creating Docker Container

### ISSUE THREAD

**Issue by yosiasm** [thelastpickle/cassandra-reaper#845]
Hello,

I'm testing Cassandra_Reaper on my docker using [this tutorial](http://cassandra-reaper.io/docs/download/docker/)
```bash
sudo docker run \
>     -p 8080:8080 \
>     -p 8081:8081 \
>     -e REAPER_JMX_AUTH_USERNAME=admin \
>     -e REAPER_JMX_AUTH_PASSWORD=admin \
>     -e REAPER_STORAGE_TYPE=cassandra \
>     -e REAPER_CASS_CLUSTER_NAME=dela_cluster \
>     -e REAPER_CASS_CONTACT_POINTS=x.x.x.x \
>     -e REAPER_CASS_KEYSPACE=reaper_db \
>     thelastpickle/cassandra-reaper
```
but I got this error 
```bash
+ touch /etc/cassandra-reaper.yml
+ /usr/local/bin/configure-persistence.sh
+ /usr/local/bin/configure-webui-authentication.sh
+ /usr/local/bin/configure-metrics.sh
+ exec java -jar /usr/local/lib/cassandra-reaper.jar server /etc/cassandra-reaper.yml
io.dropwizard.configuration.ConfigurationParsingException: /etc/cassandra-reaper.yml has an error:
  * Failed to parse configuration at: cassandra.contactPoints; Cannot deserialize instance of `java.lang.String[]` out of VALUE_STRING token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.cassandrareaper.ReaperApplicationConfiguration["cassandra"]->systems.composable.dropwizard.cassandra.CassandraFactory["contactPoints"])

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:156)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:110)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String[]` out of VALUE_STRING token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.cassandrareaper.ReaperApplicationConfiguration["cassandra"]->systems.composable.dropwizard.cassandra.CassandraFactory["contactPoints"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.handleNonArray(StringArrayDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:132)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:21)
	at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:47)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:252)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:47)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:252)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:127)
	... 6 more

```

**Comment by jsanda** [comment]
Try wrapping the value in brackets, e.g., `REAPER_CASS_CONTACT_POINTS="[x.x.x.x]"`.

**Comment by yosiasm** [comment]
thank you very much
