### ISSUE TITLE
`handlePotentialStuckRepairs` can cause stuck `RepairJob` threads

### ISSUE THREAD

**Issue by sayap** [thelastpickle/cassandra-reaper#898]
We have a fairly big table (240GB per node) where the reaper repairs would kept failing as they get killed by `handlePotentialStuckRepairs`.

On this cluster (with G1GC), we also experience memory leak, where the old gen would keep growing, until JVM has to do minutes-long full GC, which still couldn't recover much memory from the old gen.

From heapdump, we eventually trace the memory leak to dozens of `RepairJob` threads, each one holding on to hundreds of megabytes of `MerkleTrees` objects.

The threads would look like this in jmap output (cassandra 3.11.4):
```
"Repair#30:1" #14352 daemon prio=5 os_prio=0 tid=0x00007f39f6ac7110 nid=0x1f3d waiting on condition [0x00007f7609ce8000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000243c005a8> (a com.google.common.util.concurrent.AbstractFuture$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:285)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
        at com.google.common.util.concurrent.Futures.getUnchecked(Futures.java:1509)
        at org.apache.cassandra.repair.RepairJob.run(RepairJob.java:160)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.cassandra.concurrent.NamedThreadFactory.lambda$threadLocalDeallocator$0(NamedThreadFactory.java:81)
        at org.apache.cassandra.concurrent.NamedThreadFactory$$Lambda$9/1896622931.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - <0x0000000243c00658> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

After checking the code, we think this is what happens:
1. reaper schedules repair #<span/>1 to node A
2. node A requests merkle trees from neighboring node B and C
3. node B finishes validation phase, sends merkle tree to node A
4. node C finishes validation phase, sends merkle tree to node A
5. reaper schedules repair #<span/>2, calls `handlePotentialStuckRepairs`
6. node A finishes validation phase
7. node A starts sync phase
8. repair #<span/>1 on node A, B, and C all stuck indefinitely, as the `executor` was already shutdown by `handlePotentialStuckRepairs`, and thus nobody would pick up the sync task

Admittedly, our repair schedule might be too aggressive, and the memory leak is technically a bug in cassandra's `ActiveRepairService#terminateSessions`. Anyway, reaper should probably handle this more gracefully.

**Comment by sayap** [comment]
Forgot to mention... this is with reaper 1.4.8

**Comment by sayap** [comment]
From debug.log, it took about 40 minutes to finish a repair run. We will increase `hangingRepairTimeoutMins` to 60 minutes, which should fix the memory-leak issue.

Also, this is a single-token cluster with 3 nodes, and we set "segment" to 10.

**Comment by adejanovski** [comment]
Hi @sayap,

I would say this is, as you mentioned, most probably a bug in Cassandra as terminating repairs should trigger a cleanup of all related objects.
I'd recommend to use a higher number of segments per node (try 20) instead of raising the repair timeout. It's good to have more smaller segments rather than a few big ones, as it gives more control to Reaper over backpressure, it limits overstreaming and is less likely to have segments that will timeout.
Also, the smaller the segments are, the smaller the Merkle trees will be.

I'd recommend opening a Cassandra JIRA describing this issue as I can't find any ticket for that behavior.

As for Reaper, I know we need to make a better job at reacting automatically to segments timing out, which will be tracked in #893 

I'll close this issue for now, as adaptive repairs is the only thing Reaper can improve for this case.
Let me know if you want to discuss this further.

**Comment by sayap** [comment]
Thanks @adejanovski, we will increase segments per node from 10 to 20. I didn't find any Cassandra JIRA either after a cursory search, and we hadn't taken the time to create one.

**Comment by sayap** [comment]
Created https://jira.apache.org/jira/browse/CASSANDRA-15743
