### ISSUE TITLE
Reaper stops to work after one repair

### ISSUE THREAD

**Issue by davidlar** [thelastpickle/cassandra-reaper#904]
Reaper 2.0.4
Cassandra 3.11.6
Compaction strategy: TWCS
Storage backend: Cassandra
Reaper mode: SIDECAR

Hi,

We have a cluster split in 2 DCs with 15 nodes in each. I can run 1 repair without hassle with reaper 2.0.4. (In 2.0.3 it always hanged with segments in STARTED, like in #863.) 
After one successful run, the next repair hangs because metric requests are not replied by some nodes. If I restart all reapers, it will work again for one repair.

In the log files on some nodes, I can find 

```INFO
2 for instance 4cd55261-e2d2-4f98-9547-ebe13ace0f91 
ERROR  [2020-04-16 18:49:53,807] [storage:0002e920-7c9a-11ea-bfff-c7c2968ca922:00170d78-7c9a-11ea-bfff-c7c2968ca922] i.c.s.RepairRunner - Executing SegmentRunner failed 
java.lang.AssertionError: Could not release lead on segment 00170d78-7c9a-11ea-bfff-c7c2968ca922
        at io.cassandrareaper.storage.CassandraStorage.releaseLead(CassandraStorage.java:1440)
        at io.cassandrareaper.service.SegmentRunner.releaseLead(SegmentRunner.java:1226)
        at io.cassandrareaper.service.SegmentRunner.run(SegmentRunner.java:183)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I guess that because we hit this line in CassandraStorage.java

```assert false : "Could not release lead on segment " + leaderId;```

an AssertionError is thrown (not an Exception). This boils up to ReaperApplication and

```private
    scheduler.scheduleWithFixedDelay(
        () -> {
          try {
            context.repairManager.resumeRunningRepairRuns();
          } catch (ReaperException | RuntimeException e) {
            // test-pollution: grim_reaper trashes this log error
            //if (!Boolean.getBoolean("grim.reaper.running")) {
            LOG.error("Couldn't resume running repair runs", e);
            //}
          }
        },
        0,
        10,
        TimeUnit.SECONDS);
  }
```

Since the catch clause doesn't handle the error, the scheduled job is then dead and won't run again.

I disabled assertions in the reaper start script and after that it runs fine.

I guess that the root cause for `Could not release lead on segment`
is some kind of a race between reaper nodes. Maybe multiple reapers tries to release the lead for the same segment at the same time...

Thanks for a great tool!
Regards David

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-431) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-431

**Comment by adejanovski** [comment]
This was fixed in past releases, I'll close this ticket.
Feel free to reopen if you're still experiencing the issue.
