### ISSUE TITLE
Issue while connecting reaper to cassandra using SSL

### ISSUE THREAD

**Issue by vchauhan81** [thelastpickle/cassandra-reaper#922]
Although all keystore and truststore files are at correct location, having correct password - reaper is consistently failing to connect to cassandra. 
I am able to connect to cassandra using following command : 
./cqlsh --ssl --cqlshrc /home/vijay/apache-cassandra/conf/cqlshrc 10.115.10.97 9042

I am getting following error in reaper startup : 

Starting Cassandra Reaper at Sat May 16 13:40:00 IST 2020.

Warning: Specified cqlshrc location `/home/vijay/.cassandra/cqlshrc
/cqlshrc` does not exist.  Using `/home/vijay/.cassandra` instead.

Connection error: ('Unable to connect to any servers', {'10.115.10.97': error(111, "Tried connecting to [('10.115.10.97', 9042)]. Last error: Connection refused")})

Warning: Specified cqlshrc location `/home/vijay/.cassandra/cqlshrc
/cqlshrc` does not exist.  Using `/home/vijay/.cassandra` instead.

<stdin>:1:InvalidRequest: Error from server: code=2200 [Invalid query] message="unconfigured table cluster"

Warning: Specified cqlshrc location `/home/vijay/.cassandra/cqlshrc
/cqlshrc` does not exist.  Using `/home/vijay/.cassandra` instead.

Consistency level set to ONE.
Worker started
Exception in thread "main" java.lang.IllegalStateException: Cannot initialize SSL Context
	at com.datastax.driver.core.JdkSSLOptions.makeDefaultContext(JdkSSLOptions.java:85)
	at com.datastax.driver.core.JdkSSLOptions.<init>(JdkSSLOptions.java:53)
	at com.datastax.driver.core.JdkSSLOptions$Builder.build(JdkSSLOptions.java:133)
	at systems.composable.dropwizard.cassandra.ssl.JDKSSLOptionsFactory.build(JDKSSLOptionsFactory.java:15)
	at systems.composable.dropwizard.cassandra.CassandraFactory$$Lambda$35.00000000851B55A0.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:226)
	at systems.composable.dropwizard.cassandra.CassandraFactory.build(CassandraFactory.java:477)
	at systems.composable.dropwizard.cassandra.CassandraFactory.build(CassandraFactory.java:447)
	at io.cassandrareaper.storage.CassandraStorage.<init>(CassandraStorage.java:143)
	at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:235)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:140)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:67)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:79)
	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:87)
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: IBMJSSE2, class: com.ibm.jsse2.aj)
	at java.security.Provider$Service.newInstance(Provider.java:1628)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:248)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:176)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:6)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:8)
	at com.datastax.driver.core.JdkSSLOptions.makeDefaultContext(JdkSSLOptions.java:83)
	... 16 more
Caused by: java.security.KeyStoreException: IBMKeyManager: Problem accessing key store java.lang.Exception: Keystore file does not exist: /home/vijay/apache-cassandra/conf/keystore.jks
	at com.ibm.jsse2.ah.a(ah.java:84)
	at com.ibm.jsse2.aj.g(aj.java:6)
	at com.ibm.jsse2.aj.<init>(aj.java:7)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:83)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:437)
	at java.security.Provider$Service.newInstance(Provider.java:1606)
	... 21 more
<stdin>:1:InvalidRequest: Error from server: code=2200 [Invalid query] message="unconfigured table cluster"

Warning: Specified cqlshrc location `/home/vijay/.cassandra/cqlshrc
/cqlshrc` does not exist.  Using `/home/vijay/.cassandra` instead.

Consistency level set to ONE.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-442) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-442

**Comment by vchauhan81** [comment]
Reaper version we are using is 1.1.0 & cassandra version is 3.11.0

**Comment by vchauhan81** [comment]
I tried to use reaper version 2.0.4, but I am getting same set of exceptions

**Comment by adejanovski** [comment]
Encryption settings were most probably incorrectly configured.
I'll close this ticket as I guess this should no longer be an issue. Feel free to reopen otherwise.
