### ISSUE TITLE
Possible migration bug (2.0.2 to 2.1)

### ISSUE THREAD

**Issue by gaborauth** [thelastpickle/cassandra-reaper#975]
I've upgraded from 2.0.2 to 2.1 today and found a NullPointerException in the log (otherwise everything is looks okay):

```
INFO   [main] o.c.c.m.MigrationRepository - Found 10 migration scripts
WARN   [main] i.c.s.CassandraStorage - Starting db migration from 23 to 25…
INFO   [main] o.c.c.m.MigrationRepository - Found 10 migration scripts
INFO   [main] o.c.c.m.MigrationTask - Migrated keyspace cassandra_reaper to version 24
INFO   [main] i.c.s.CassandraStorage - Migrated keyspace cassandra_reaper to version 24
INFO   [main] o.c.c.m.MigrationRepository - Found 10 migration scripts
INFO   [main] o.c.c.m.MigrationTask - Migrated keyspace cassandra_reaper to version 25
INFO   [main] i.c.s.CassandraStorage - Migrated keyspace cassandra_reaper to version 25
WARN   [main] i.c.s.c.Migration016 - altering every table to set `dclocal_read_repair_chance` to zero…
WARN   [main] i.c.s.c.Migration016 - alter every table to set `dclocal_read_repair_chance` to zero completed.
INFO   [main] i.c.s.c.Migration024 - Altering node_metrics_v3 to use TWCS...
INFO   [main] i.c.s.c.Migration024 - node_metrics_v3 was successfully altered to use TWCS.
INFO   [main] i.c.s.c.Migration025 - Converting repair_run_by_cluster table...
ERROR  [main] i.c.s.c.Migration025 - Failed transferring rows to repair_run_by_cluster_v2
java.lang.NullPointerException: null
        at io.cassandrareaper.storage.cassandra.Migration025.migrate(Migration025.java:51)
        at io.cassandrareaper.storage.CassandraStorage.initializeCassandraSchema(CassandraStorage.java:302)
        at io.cassandrareaper.storage.CassandraStorage.initializeAndUpgradeSchema(CassandraStorage.java:251)
        at io.cassandrareaper.storage.CassandraStorage.<init>(CassandraStorage.java:239)
        at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:477)
        at io.cassandrareaper.ReaperApplication.tryInitializeStorage(ReaperApplication.java:300)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:179)
        at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:98)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:117)
INFO   [main] i.c.ReaperApplication - no JMX connection factory given in context, creating default
INFO   [main] i.c.ReaperApplication - creating and registering health checks
INFO   [main] i.c.ReaperApplication - creating resources and registering endpoints
INFO   [main] i.c.s.SchedulingManager - Starting new SchedulingManager instance
INFO   [main] i.c.ReaperApplication - Initializing JMX seed list for all clusters...
INFO   [main] i.c.ReaperApplication - Initialized JMX seed list for all clusters.
INFO   [main] i.c.ReaperApplication - resuming pending repair runs
INFO   [main] i.c.ReaperApplication - Initialization complete!
WARN   [main] i.c.ReaperApplication - Reaper is ready to get things done!
```

**Comment by adejanovski** [comment]
Thanks for the notice @gaborauth.

Is Reaper working correctly aside from this? Do you see all your past repair runs in the GUI?

**Comment by gaborauth** [comment]
> Is Reaper working correctly aside from this? Do you see all your past repair runs in the GUI?

Hm, there is 4 rows in the ``repair_run_by_cluster`` table, maybe they ran just before the upgrade... they are missing in the GUI and there is only one row in the ``repair_run_by_cluster_v2``, it is started after the upgrade.

**Comment by adejanovski** [comment]
the migration to the new table failed then... 
The stack trace suggests that you had some entries in `repair_run_by_cluster` that didn't exist in `repair_run`. That shouldn't happen under normal conditions, unless I'm missing something 🤔 
These are the instructions that threw the NPE: https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/java/io/cassandrareaper/storage/cassandra/Migration025.java#L50-L51
Do you see the ids that are in `repair_run_by_cluster` in `repair_run`? Do they all have a value in the `state` column?

**Comment by gaborauth** [comment]
> The stack trace suggests that you had some entries in `repair_run_by_cluster` that didn't exist in `repair_run`. That shouldn't happen under normal conditions, unless I'm missing something 🤔

Bingo, here is one repair from more than two years ago:

```
> select id,totimestamp(id) from cassandra_reaper.repair_run_by_cluster;

 id                                   | system.totimestamp(id)
--------------------------------------+---------------------------------
 84226350-1f24-11e8-a539-91b5c86fed56 | 2018-03-03 20:50:33.093000+0000
 1a4d9b10-12bb-11eb-a826-ff42939b493c | 2020-10-20 10:00:37.441000+0000
 7bb67590-12c3-11eb-a826-ff42939b493c | 2020-10-20 11:00:36.841000+0000
 dd116d60-12cb-11eb-a826-ff42939b493c | 2020-10-20 12:00:36.150000+0000
```

This is the new repair, started with the 2.1 version:

```
> select id,totimestamp(id) from cassandra_reaper.repair_run_by_cluster_v2 ;

 id                                   | system.totimestamp(id)
--------------------------------------+---------------------------------
 425474d0-12d4-11eb-b693-4fc5426ccce5 | 2020-10-20 13:00:42.013000+0000
```

This is the 3 old and a new one:
```
> select distinct id from cassandra_reaper.repair_run ALLOW FILTERING ;

 id
--------------------------------------
 1a4d9b10-12bb-11eb-a826-ff42939b493c
 dd116d60-12cb-11eb-a826-ff42939b493c
 425474d0-12d4-11eb-b693-4fc5426ccce5
 7bb67590-12c3-11eb-a826-ff42939b493c
```

How can I clean the database? Simply migrate the "live" rows from ``repair_run_by_cluster`` to ``repair_run_by_cluster_v2`` by hand is enough?

**Comment by adejanovski** [comment]
Yes, you can manually insert the missing rows in `repair_run_by_cluster_v2`. Don't forget to include the `state` value that you'll find in the `repair_run` table.

**Comment by adejanovski** [comment]
I'm going to create a patch to skip such cases gracefully instead of trashing the whole migration.

**Comment by adejanovski** [comment]
The fix was released.
