### ISSUE TITLE
Upgrading to 2.1 gives me "Storage is not ready yet, trying again to connect shortly..."

### ISSUE THREAD

**Issue by nicholasamorim** [thelastpickle/cassandra-reaper#987]
I'm using Docker version.

When I upgrade to tag `ad53ff3` (because I need this [fix](https://github.com/thelastpickle/cassandra-reaper/pull/972)), the message "Storage is not ready yet, trying again to connect shortly..." keeps appearing on the logs forever and the connection never really happens.

```
ERROR  [2020-11-07 13:11:16,885] [main] i.c.ReaperApplication - Storage is not ready yet, trying again to connect shortly...
java.lang.NullPointerException: null
	at systems.composable.dropwizard.cassandra.CassandraFactory.build(CassandraFactory.java:469)
	at systems.composable.dropwizard.cassandra.CassandraFactory.build(CassandraFactory.java:447)
	at io.cassandrareaper.storage.CassandraStorage.<init>(CassandraStorage.java:225)
	at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:477)
	at io.cassandrareaper.ReaperApplication.tryInitializeStorage(ReaperApplication.java:300)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:179)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:98)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:117)
```

At first I thought it could be a migration issue so I dropped and recreated the `reaper_db` keyspace. The issue is still there.

These are my envvars:

```yaml
REAPER_CASS_CLUSTER_NAME: "myclustername"
REAPER_CASS_CONTACT_POINTS: "[bunch,of,ips]"
REAPER_CASS_LOCAL_DC: "datacenter1"
REAPER_STORAGE_TYPE: cassandra
REAPER_HANGING_REPAIR_TIMEOUT_MINS: "120"
REAPER_BLACKLIST_TWCS_TABLES: "0"
REAPER_REPAIR_MANAGER_SCHEDULING_INTERVAL_SECONDS: "10"
REAPER_JMX_CONNECTION_TIMEOUT_IN_SECONDS: "5"
REAPER_REPAIR_PARALELLISM: "DATACENTER_AWARE"

---
Upon rolling back to 2.0.5 (this might be useful, don't know) on an empty keyspace everything worked fine _up to migration 23 to 24_. That migration keeps giving the same error of "Storage is not ready yet, trying again to connect shortly..." 

Then it says: `java.lang.IllegalStateException: Database migration can not happen with other reaper instances running. Found  [[172.17.0.2]]`

But there's no other instance running. Checked `running_reapers` and it only shows 1 indeed.

```

 reaper_instance_id                   | last_heartbeat                  | reaper_instance_host
--------------------------------------+---------------------------------+----------------------
 59e4b43e-f4f2-4429-bfc0-03dac8f73355 | 2020-11-07 13:17:00.596000+0000 |           172.17.0.2
```

Anyways, truncating the table made the migration finish just fine. I'll keep using 2.0.5 for now.



┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-259) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-259

**Comment by cin** [comment]
I was in a similar position with the `Database migration can not happen with other reaper instances running` error. If you are running a reaper instance in multiple DCs, this gets a bit tricky as you have to stop them before truncating the `running_reapers` table. Then wait for the new (2.1.2) reaper to start and then restart the other reapers in the other DCs.

I'm sure there's a better way to do this, but this worked for me (hopefully temporarily) 🤷 . 

NOTE: expected but you cannot downgrade w/out dropping the reaper_db keyspace (assuming you're using C* backend).

**Comment by nicholasamorim** [comment]
Unfortunately, Reaper is completely broken for me using Docker. I've recently turned on authentication in Cassandra.

If I use an older version, this bug appears: #984

If I use the latest commit master from docker which includes the fix above (ad53ff3), then I get the error I reported. I've also tested it on a brand new single-node cluster - totally empty `reaper_db` keyspace. The same thing happens:

```
WARN   [2020-11-18 14:02:03,113] [main] i.c.s.CassandraStorage - Customization of cassandra's retry policy is not supported and will be overridden
ERROR  [2020-11-18 14:02:03,114] [main] i.c.ReaperApplication - Storage is not ready yet, trying again to connect shortly...
java.lang.NullPointerException: null
	at systems.composable.dropwizard.cassandra.CassandraFactory.build(CassandraFactory.java:469)
	at systems.composable.dropwizard.cassandra.CassandraFactory.build(CassandraFactory.java:447)
	at io.cassandrareaper.storage.CassandraStorage.<init>(CassandraStorage.java:225)
	at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:477)
	at io.cassandrareaper.ReaperApplication.tryInitializeStorage(ReaperApplication.java:300)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:179)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:98)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:117)
```

Any ideas @adejanovski? There doesn't seem to be a way to enable debug logging on Docker, so I'm out of options on diagnosing the issue.

PS: Authentication is irrelevant on the issue. This issue happened before enabling authentication.

**Comment by adejanovski** [comment]
Hi @nicholasamorim, that doesn't ring any bell but I'll try to investigate the issue shortly.
Sorry for the inconvenience...

**Comment by nicholasamorim** [comment]
Just an update here: the non-docker version works just fine. Installed it via `apt` - `2.2.0-BETA-20201106` and it runs fine.

Maybe add a way to set the logging level in docker first? (if there isn't one already)

**Comment by Gurpartap** [comment]
echoing @nicholasamorim's findings… cassandra-reaper dockers images are a no-go for me as well.

\- images `2.1` to `latest (2.1.2)` due to #984
\- current `master` image (9f66308220de – 2020-11-06) due to #987

**Comment by Gurpartap** [comment]
the master image is possibly affected by changes in ad53ff3f2fc5ea88aea5c25fb93f9e4b9a43fd67

**stderr**:
```
/usr/local/bin/configure-persistence.sh: line 29: syntax error: unexpected redirection
```

**stdout**:
```
WARN   [2020-12-10 07:42:37,715] [main] i.c.s.CassandraStorage - Customization of cassandra's retry policy is not supported and will be overridden 
ERROR  [2020-12-10 07:42:37,716] [main] i.c.ReaperApplication - Storage is not ready yet, trying again to connect shortly... 
java.lang.NullPointerException: null
	at systems.composable.dropwizard.cassandra.CassandraFactory.build(CassandraFactory.java:469)
	at systems.composable.dropwizard.cassandra.CassandraFactory.build(CassandraFactory.java:447)
	at io.cassandrareaper.storage.CassandraStorage.<init>(CassandraStorage.java:225)
	at io.cassandrareaper.ReaperApplication.initializeStorage(ReaperApplication.java:477)
	at io.cassandrareaper.ReaperApplication.tryInitializeStorage(ReaperApplication.java:300)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:179)
	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:98)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:117)
```

**Comment by adejanovski** [comment]
ok, that's a solid lead @Gurpartap, thanks!

Looking at this now.

**Comment by Gurpartap** [comment]
switching to a preceding commit `thelastpickle/cassandra-reaper:150fffe`, it finally summoned the space invaders… 👾

```
_________                                          .___               __________
\_   ___ \_____    ______ ___________    ____    __| _/___________    \______   \ ____ _____  ______   ___________
/    \  \/\__  \  /  ___//  ___/\__  \  /    \  / __ |\_  __ \__  \    |       _// __ \\__  \ \____ \_/ __ \_  __ \
\     \____/ __ \_\___ \ \___ \  / __ \|   |  \/ /_/ | |  | \// __ \_  |    |   \  ___/ / __ \|  |_> >  ___/|  | \/
 \______  (____  /____  >____  >(____  /___|  /\____ | |__|  (____  /  |____|_  /\___  >____  /   __/ \___  >__|
        \/     \/     \/     \/      \/     \/      \/            \/          \/     \/     \/|__|        \/
 ```

**Comment by adejanovski** [comment]
I'm unable to reproduce the issue, using the 2.1.2 docker image on an Ubuntu 18.04 instance 🤔 
So this is not a general problem but it affects some setups.
According to [this SO page](https://stackoverflow.com/questions/2462317/bash-syntax-error-redirection-unexpected), the unexpected redirection seems to be due to the shebang we use in configure-persistence.sh which is `#!/bin/sh` instead of `#!/bin/bash`. 
I guess the fix here would be to switch to a base docker image that includes bash as default.
