### ISSUE TITLE
SchedulingManager failed. Exiting JVM when no nodes available

### ISSUE THREAD

**Issue by albundy83** [thelastpickle/cassandra-reaper#989]
Hello,

we encounter an issue when network is not stable.
When our reaper loose connection to Cassandra DB, it fails and we have this issue :
`ERROR  [2020-11-09 23:22:08,476]  [SchedulingManagerTimer] i.c.s.SchedulingManager - SchedulingManager failed. Exiting JVM`
We are under last reaper version 2.1.2 at the writing time and on Ubuntu 16.04.
Our Cassandra is a single DC under version 3.11.3 with the following nodes :

```
10.234.167.14
10.234.167.15
10.234.167.18
10.234.167.19
10.234.167.20
10.234.167.21
```

Here the full output when the issue happens :

```
INFO   [2020-11-09 23:10:38,290]  [ReaperApplication-scheduler] i.c.ReaperApplication - Purged 0 repair runs from history
ERROR  [2020-11-09 23:22:08,470]  [SchedulingManagerTimer] i.c.s.SchedulingManager - failed managing schedule for run with id: null
ERROR  [2020-11-09 23:22:08,475]  [ReaperApplication-scheduler] i.c.ReaperApplication - Couldn't resume running repair runs
io.cassandrareaper.ReaperException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.234.167.14:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.234.167.14:9042] Connection has been closed), /10.234.167.15:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.234.167.15:9042] Connection has been closed), /10.234.167.20:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.234.167.20:9042] Timed out waiting for server response), /10.234.167.18:9042 [only showing errors of first 3 hosts, use getErrors() for more details])
        at io.cassandrareaper.service.RepairManager.resumeRunningRepairRuns(RepairManager.java:141)
        at io.cassandrareaper.ReaperApplication.lambda$scheduleRepairManager$2(ReaperApplication.java:417)
        at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.234.167.14:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.234.167.14:9042] Connection has been closed), /10.234.167.15:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.234.167.15:9042] Connection has been closed), /10.234.167.20:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.234.167.20:9042] Timed out waiting for server response), /10.234.167.18:9042 [only showing errors of first 3 hosts, use getErrors() for more details])
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:83)
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:37)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:293)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
        at io.cassandrareaper.storage.CassandraStorage.getClusters(CassandraStorage.java:588)
        at io.cassandrareaper.storage.CassandraStorage.getRepairRunsWithState(CassandraStorage.java:930)
        at io.cassandrareaper.service.RepairManager.resumeRunningRepairRuns(RepairManager.java:134)
        ... 9 common frames omitted
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.234.167.14:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.234.167.14:9042] Connection has been closed), /10.234.167.15:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.234.167.15:9042] Connection has been closed), /10.234.167.20:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.234.167.20:9042] Timed out waiting for server response), /10.234.167.18:9042 [only showing errors of first 3 hosts, use getErrors() for more details])
        at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:283)
        at com.datastax.driver.core.RequestHandler.access$1200(RequestHandler.java:61)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:375)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.retry(RequestHandler.java:563)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.processRetryDecision(RequestHandler.java:545)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onException(RequestHandler.java:947)
        at com.datastax.driver.core.Connection$Dispatcher.errorOutAllHandler(Connection.java:1368)
        at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1455)
        at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1436)
        at com.datastax.driver.core.Connection.defunct(Connection.java:619)
        at com.datastax.driver.core.Connection$12.fail(Connection.java:1432)
        at com.datastax.driver.core.Connection$12.onTimeout(Connection.java:1425)
        at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1633)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted
ERROR  [2020-11-09 23:22:08,476]  [SchedulingManagerTimer] i.c.s.SchedulingManager - catch exception
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.234.167.14:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.234.167.14:9042] Timed out waiting for server response), /10.234.167.21:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.234.167.21:9042] Connection has been closed), /10.234.167.19:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.234.167.19:9042] Timed out waiting for server response))
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:83)
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:37)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:293)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
        at io.cassandrareaper.storage.CassandraStorage.getAllRepairSchedules(CassandraStorage.java:1370)
        at io.cassandrareaper.service.SchedulingManager.run(SchedulingManager.java:97)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.234.167.14:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.234.167.14:9042] Timed out waiting for server response), /10.234.167.21:9042 (com.datastax.driver.core.exceptions.TransportException: [/10.234.167.21:9042] Connection has been closed), /10.234.167.19:9042 (com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.234.167.19:9042] Timed out waiting for server response))
        at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:283)
        at com.datastax.driver.core.RequestHandler.access$1200(RequestHandler.java:61)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:375)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.retry(RequestHandler.java:563)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.processRetryDecision(RequestHandler.java:545)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onException(RequestHandler.java:947)
        at com.datastax.driver.core.Connection$Dispatcher.errorOutAllHandler(Connection.java:1368)
        at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1455)
        at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1436)
        at com.datastax.driver.core.Connection.defunct(Connection.java:619)
        at com.datastax.driver.core.Connection$12.fail(Connection.java:1432)
        at com.datastax.driver.core.Connection$12.onTimeout(Connection.java:1425)
        at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1633)
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
ERROR  [2020-11-09 23:22:08,476]  [SchedulingManagerTimer] i.c.s.SchedulingManager - SchedulingManager failed. Exiting JVM.
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-258) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-258

**Comment by albundy83** [comment]
Hello,

here some logs as it's still happen:
```
INFO   [2020-12-14 22:44:43,493]  [preprodcassandrapns:564b65b0-3e36-11eb-bbbc-5f403e24cd4d:564c9e8f-3e36-11eb-bbbc-5f403e24cd4d] i.c.s.SegmentRunner - Repair for segment 564c9e8f-3e36-11eb-bbbc-5f403e24cd4d started, status wait will timeout in 1800000 millis
WARN   [2020-12-14 22:45:07,601]  [JMX client heartbeat 33] j.m.r.misc - Failed to check connection: java.net.NoRouteToHostException: No route to host (Host unreachable)
WARN   [2020-12-14 22:45:07,601]  [JMX client heartbeat 33] j.m.r.misc - stopping
WARN   [2020-12-14 22:45:25,724]  [Test Cluster Cassandra3 PNS ADV-worker-38] c.d.d.c.RequestHandler - Unexpected error while querying /10.234.167.15:9042 - [com.datastax.driver.core.exceptions.ConnectionException: [/10.234.167.15:9042] Pool is shutdown]. Find next host to query.
WARN   [2020-12-14 22:45:25,726]  [Test Cluster Cassandra3 PNS ADV-worker-38] c.d.d.c.RequestHandler - Unexpected error while querying /10.234.167.15:9042 - [com.datastax.driver.core.exceptions.ConnectionException: [/10.234.167.15:9042] Pool is shutdown]. Find next host to query.
WARN   [2020-12-14 22:45:25,728]  [Test Cluster Cassandra3 PNS ADV-worker-38] c.d.d.c.RequestHandler - Unexpected error while querying /10.234.167.15:9042 - [com.datastax.driver.core.exceptions.ConnectionException: [/10.234.167.15:9042] Pool is shutdown]. Find next host to query.
WARN   [2020-12-14 22:45:25,728]  [Test Cluster Cassandra3 PNS ADV-worker-38] c.d.d.c.RequestHandler - Unexpected error while querying /10.234.167.15:9042 - [com.datastax.driver.core.exceptions.ConnectionException: [/10.234.167.15:9042] Pool is shutdown]. Find next host to query.
WARN   [2020-12-14 22:45:25,729]  [Test Cluster Cassandra3 PNS ADV-worker-38] c.d.d.c.RequestHandler - Unexpected error while querying /10.234.167.15:9042 - [com.datastax.driver.core.exceptions.ConnectionException: [/10.234.167.15:9042] Pool is shutdown]. Find next host to query.
```

It will be nice to have some parameters to retry connection to Cassandra DB, I mean the Cassandra which is used has backend not the one we are trying to repair :)

**Comment by Algieba4** [comment]
Hi,

We are using Cassandra Reaper version 3.1.1 and are seeing this as well. We are running nodetool status on our Cassandra VM and both the backend VM and Cassandra process is running without issue though it doesn't seem like the Reaper client isn't able to reconnect unless we restart the client.

**Comment by adejanovski** [comment]
@adutra, would you know how we could setup the driver to work around that issue?

**Comment by adutra** [comment]
Are you using the default reconnection policy or a custom one? With the default one, the driver is going to keep reconnecting to the down node until it succeeds, or the node is permanently removed. 

If network is unreachable and all nodes appear down, then it is normal to get back a `NoHostAvailableException`. I would suggest that Reaper should be made resilient to that situation. It could e.g. wait a while and retry, or consider the repair as failed or uncertain.

Also, the `Unexpected error while querying` error can also happen when the node has just transitioned to down but there was an in-flight query to it that failed mid-course.

**Comment by adejanovski** [comment]
We're using the default reconnection policy, which can be overridden in config.
The problem seems to be that the SchedulingManager code is too sensitive and will kill the JVM as soon as there's an uncaught exception: https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/java/io/cassandrareaper/service/SchedulingManager.java#L122-L135

We'd need to relax that behavior and display the error in the logs and let the driver recover.
