### ISSUE TITLE
JMX Timeout with firewall between reaper and cassandra nodes

### ISSUE THREAD

**Issue by manhein-lav** [thelastpickle/cassandra-reaper#995]
Hello,
i have a problem when trying to get reaper working with a Multi-DC cassandra cluster that is in a different network segment than reaper with active firewall rules allowing only certain IP's and Ports through. When I open up the firewall rule to allow all ports and services through, everything works fine, but when I restrict the rule to Port 7199/TCP, reaper begins throwing Timeout exceptions when trying via JMX.

`ERROR  [2020-11-16 16:22:02,052] [ClusterResource] i.c.j.JmxConnectionFactory - Failed creating a new JMX connection to 10.10.100.61:7199 
java.lang.RuntimeException: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 10.10.100.61:7199
	at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:240)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectImpl(JmxConnectionFactory.java:103)
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectAny(JmxConnectionFactory.java:138)
	at io.cassandrareaper.jmx.ClusterFacade.connectImpl(ClusterFacade.java:836)
	at io.cassandrareaper.jmx.ClusterFacade.connect(ClusterFacade.java:820)
	at io.cassandrareaper.jmx.ClusterFacade.getNodesStatus(ClusterFacade.java:207)
	at io.cassandrareaper.resources.ClusterResource.lambda$getEndpointState$4(ClusterResource.java:426)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 10.10.100.61:7199
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:286)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:179)
	at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:231)
	... 14 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at io.cassandrareaper.jmx.JmxProxyImpl.connectWithTimeout(JmxProxyImpl.java:304)
	at io.cassandrareaper.jmx.JmxProxyImpl.connect(JmxProxyImpl.java:242)
	... 16 common frames omitted
`

I have traced the packages going from reaper to a cassandra node, and they are all going to Port 7199 over TCP, which is allowed by my firewall rule and should be the only port used by JMX/RMI.

The cassandra is v3.11.2, Java is OpenJDK "1.8.0_265" and the JMX settings are set explicitly to:
-Dcom.sun.management.jmxremote.authenticate=true"
-Dcassandra.jmx.remote.port=7199"
-Dcom.sun.management.jmxremote.rmi.port=7199"

Am i missing something? I have been going over my setup since 2 days, maybe you have an idea what could be the problem?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-251) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-251

**Comment by adejanovski** [comment]
I'll close this ticket as it's been inactive for a while.
Feel free to reopen if needed.
